### ISSUE TITLE
Clarification on how to use flash decoding, is it available when calling `flash_attn_func`?

### ISSUE THREAD

**Issue by btruhand** [Dao-AILab/flash-attention#1002]
Based on prior issues it seems we can use flash decoding by calling `flash_attn_with_kvcache`. But wondering, is it also available if we just call `flash_attn_func`?

@tridao

**Comment by tridao** [comment]
There's a heuristic to pick the number of splits to choose whichever is faster.
https://github.com/Dao-AILab/flash-attention/blob/320fb59487658f033f56711efd3d61b7c7a6f8f3/csrc/flash_attn/flash_api.cpp#L452
num_splits > 1 means flash-decoding is running.

**Comment by btruhand** [comment]
Thank you! Since `num_splits` is passed as `0` to `set_params_splitkv` for `flash_attn_func`, it looks like it will use a heuristic. Stating that a bit more clearly in the README will probably help. Will look to open a PR for it when I can. Thank you!
