### ISSUE TITLE
Question on FA-2 worker scheme

### ISSUE THREAD

**Issue by DianCh** [Dao-AILab/flash-attention#1015]
Hi authors, may I ask why the figure for worker scheme in the FA-2 paper has a lower-triangle pattern? I thought the double loop should cover the entire rectangle?

<img width="754" alt="Screenshot 2024-06-27 at 5 58 24 PM" src="https://github.com/Dao-AILab/flash-attention/assets/32043460/016e7360-6075-4377-83f8-981370c4eb5a">

Thanks!

**Comment by tridao** [comment]
The figure is for the case with causal mask. Without the causal mask then it would cover the entire rectangle.

**Comment by DianCh** [comment]
Makes sense, thank you!
