### ISSUE TITLE
Logit soft-capping

### ISSUE THREAD

**Issue by kabachuha** [Dao-AILab/flash-attention#1016]
As you probably know, yesterday Google released Gemma2 with superior performance and robustness https://storage.googleapis.com/deepmind-media/gemma/gemma-2-report.pdf

One of the key changes was logit soft-capping, however it's not implemented in flash-attention, and the implementations using flash-attention have to resort to the slow native pytorch variant

I think it would be useful for all to include the option to insert logit soft-capping into this library

The native pytorch implementation is provided along with the new Gemma 2 model architecture at https://github.com/google/gemma_pytorch/blob/main/gemma/model.py

**Comment by tridao** [comment]
Right, we just need someone to implement it :D

**Comment by lucidrains** [comment]
@kabachuha @tridao i can take a look at this next week

**Comment by Narsil** [comment]
Before diving can we confirm the plan: ? (I might be able to take a look too).

We need:
- Adding a optional f32 flag: https://github.com/Dao-AILab/flash-attention/blob/main/csrc/flash_attn/src/flash.h#L51
- Adding the softcapping 
  - here: https://github.com/Dao-AILab/flash-attention/blob/main/csrc/flash_attn/src/flash_fwd_kernel.h#L316-L319
  - and here: https://huggingface.slack.com/archives/C06AF1RUV8F/p1719822936637759?thread_ts=1719586808.938379&cid=C06AF1RUV8F
  
 I'm assuming the softcapping can happen at the tile level, is that safe to assume ?

**Comment by Narsil** [comment]
Created a first draft in #1025 if anyone has time for a quick review in the approach.

Core of the changes : https://github.com/Dao-AILab/flash-attention/pull/1025/files#diff-9e1775131ae22a74dc4e0333c57539573394a059db8097ef74fae24243347ce1R47
Most of the current changes in the PR are just a simple way for me to cut compile times (which are still excruciatingly slow :(, if there are better ways to speed up iteration process I'm taking them)

**Comment by lucidrains** [comment]
@Narsil circling back this morning and see that you already made some progress! i also struggled with the long compilation times trying to slip in `tanh` in the right places 😭 

i'll let you do the honors then 😃 

do you plan on tackling the backwards pass (for training)?

**Comment by Oxi84** [comment]
Awesome, now when i turn on flash attention I get 100% random response. Is this normal or softcapping can be turned off with the latest version of transformers?
