### ISSUE TITLE
Can flash-attn be compiled on cpu?

### ISSUE THREAD

**Issue by Meshwa428** [Dao-AILab/flash-attention#1022]
I need to use flash attn for my project, but I don't have any GPU or Cuda.

My project is for cpu and I want to squeeze out the best performance from my model on cpu devices like RPi.

Can I install/compile flash-attn on cpu if so then please guide me through!

Thanks🙏

**Comment by tridao** [comment]
No we only support GPU.

**Comment by Meshwa428** [comment]
😟 ok np thanks 👍

**Comment by Originalimoc** [comment]
But does the algorithm compatible with modern CPU architecture?

**Comment by gautam-e** [comment]
Can flash-attn be compiled on the CPU for a Blackwell GPU (RTX Pro 6000)?
