### ISSUE TITLE
Why multiply with 3 when generate kv cache?

### ISSUE THREAD

**Issue by Luke20000429** [Dao-AILab/flash-attention#1024]
Hello, I am using flash-attn with paged attention. I am quite confused why we need a `* 3` here? Is that just to allocate more space in case it needs more blocks?
https://github.com/Dao-AILab/flash-attention/blob/9486635c926ad1443c5c536d90e9cefaee3db9b4/tests/test_flash_attn.py#L2084

**Comment by tridao** [comment]
It's just a test for the case where there are more blocks. No reason you should `* 3` in practice.

**Comment by Luke20000429** [comment]
Thanks for your quick response.
