### ISSUE TITLE
Does HuaWei 910B support?

### ISSUE THREAD

**Issue by lucasjinreal** [Dao-AILab/flash-attention#1034]
Does HuaWei 910B support?

**Comment by lucasjinreal** [comment]
thanks for the reply. does there any way to make flashatten able to run on 910B?

**Comment by tridao** [comment]
Idk anything about 910B

**Comment by lucasjinreal** [comment]
Haha, thanks anyway!

**Comment by QiqianFu** [comment]
@lucasjinreal Flash Attention is based on H100 chip, which is designed by NV, so of course 910B doesn't support. But usually Huawei will develop their own version which has the similar performance as FA3, u just need to wait for some time.
