### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by Achazwl** [Dao-AILab/flash-attention#1035]
I modified some of the cuda code and need to debug it.

I added a `printf` to it, added `cudaDeviceSynchronize()` after the kernel launch, and changed setup.py compile_args from `-O3` to `-O0` and `-g`. I use `rm -rf build` and use `python3 setup.py install` to rebuild, with `FLASH_ATTENTION_FORCE_BUILD=TRUE`.
But the `printf` is still not working, `assert` neither.

What else should I modify? Seems like RELEASE mode is set somewhere.

**Comment by tridao** [comment]
printf always works for me. I'm guessing you'd need to remove the existing flash-attn installation to make sure the newly-compiled version is running

**Comment by ziyuhuang123** [comment]
I tried methods above but still get error because of printf:
```
[ ERROR: CUDA Runtime ] /home/zyhuang/temp_can/flash-attention/csrc/cutlass/include/cutlass/cluster_launch.hpp:170: an illegal instruction was encountered
CUDA error (/home/zyhuang/temp_can/flash-attention/hopper/flash_fwd_launch_template.h:111): an illegal instruction was encountered
```
By the way, I find no "FLASH_ATTENTION_FORCE_BUILD=TRUE". I changed my nvcc_flags in setup.py:
```
    nvcc_flags = [
        # "-O3",
        "-O0",
        "-g", # for debug printf
        "-std=c++17",
        "-U__CUDA_NO_HALF_OPERATORS__",
        "-U__CUDA_NO_HALF_CONVERSIONS__",
        "-U__CUDA_NO_BFLOAT16_OPERATORS__",
        "-U__CUDA_NO_BFLOAT16_CONVERSIONS__",
        "-U__CUDA_NO_BFLOAT162_OPERATORS__",
        "-U__CUDA_NO_BFLOAT162_CONVERSIONS__",
        "--expt-relaxed-constexpr",
        "--expt-extended-lambda",
        "--use_fast_math",
        "--ptxas-options=-v",  # printing out number of registers
        "--ptxas-options=--verbose,--register-usage-level=10,--warn-on-local-memory-usage",  # printing out number of registers
        "-lineinfo",
        "-DCUTLASS_DEBUG_TRACE_LEVEL=0",  # Can toggle for debugging
        # "-DNDEBUG",  # Important, otherwise performance is severely impacted             
    ]
```
