### ISSUE TITLE
[FA3] Performance confusion

### ISSUE THREAD

**Issue by endurehero** [Dao-AILab/flash-attention#1051]
@tridao  I compared the performance between fa2 and fa3。Here is my testcase: 
(B, S, H, D) = (4, 8k, 8, 128), (1, 16k, 8, 128), (1, 32k, 8, 128), (1, 64k, 8, 128), (1, 128k, 8, 128)

Fwd stage is much faster than fa2, but it seems to be slower than the data indicated in fa3 paper. Bwd stage is even slower than fa2's.  

take the case (1, 32k, 8, 128) on H100 as an example:
fa2: fwd: 355TFlops, bwd: 337TFlops
![image](https://github.com/user-attachments/assets/21975cec-1415-434f-aee2-6fcc357799b4)
fa3: fwd: 500TFlops, bwd: 305TFlops
![image](https://github.com/user-attachments/assets/10fae0c9-483a-46ee-a0db-3462b0e3b045)

This is the function I used: https://github.com/Dao-AILab/flash-attention/blob/main/hopper/test_flash_attn.py#L181
Is it because the current code is incomplete?

**Comment by endurehero** [comment]
Is it because the current code is incomplete?

**Comment by endurehero** [comment]
take the case (1, 32k, 8, 128) as an example:
fa2: fwd: 355TFlops, bwd: 337TFlops
![image](https://github.com/user-attachments/assets/21975cec-1415-434f-aee2-6fcc357799b4)
fa3: fwd: 500TFlops, bwd: 305TFlops
![image](https://github.com/user-attachments/assets/10fae0c9-483a-46ee-a0db-3462b0e3b045)

it seems like the bwd of fa3 is slower than fa2, and the fwd of fa3 is not as fast as the paper suggests

**Comment by MustafaFayez** [comment]
I am also seeing significant performance difference from the paper especially with causal, would be great if a benchmarking script is given that can reproduce the results from the paper.

**Comment by tridao** [comment]
There's a persistent scheduler that's not yet enabled for causal, we'll update it soon.

**Comment by endurehero** [comment]
Is the same reason for bwd's performance which is slower than fa2's

**Comment by Lzhang-hub** [comment]
@endurehero 
![image](https://github.com/user-attachments/assets/70b59279-9bf6-464a-b8cf-475ba3fd07d7)
which tools are you used for get the time cost, thank you.

**Comment by endurehero** [comment]
> @endurehero ![image](https://private-user-images.githubusercontent.com/57925599/350891412-70b59279-9bf6-464a-b8cf-475ba3fd07d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjYxMjMsIm5iZiI6MTcyMTcyNTgyMywicGF0aCI6Ii81NzkyNTU5OS8zNTA4OTE0MTItNzBiNTkyNzktOWJmNi00NjRhLWI4Y2YtNDc1YmEzZmQwN2Q3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA5MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNDdhOTRlNzRhYzdmOTcxOTkwNzYxZGZjYWVhOTQyMTUyZDdmZTg1Nzg5NGU5YmMzYjA0MDM5Mzc2Zjg2YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VBcIVR3YU4J_FH3n9vowKf6Mbi8WkmgOBRr4BBC4UkI) which tools are you used for get the time cost, thank you.

nsys

**Comment by endurehero** [comment]
> Is the same reason for bwd's performance with causal which is slower than fa2's ?

I have made it clear that bwd does not support causal at present, so the performance data obtained at present is nocausal. Current performance can be aligned with the fa3 paper, thank you

**Comment by endurehero** [comment]
I have made it clear that bwd does not support causal at present, so the performance data obtained at present is nocausal. Current performance can be aligned with the fa3 paper, thank you
