### ISSUE TITLE
Would Flash Attention V3 support H20?

### ISSUE THREAD

**Issue by guanzhchen** [Dao-AILab/flash-attention#1059]
H20 is a weakened Hopper GPU. Would it involve the speedup from Flash Attention v3?

**Comment by tridao** [comment]
Probably

**Comment by Edenzzzz** [comment]
![image](https://github.com/user-attachments/assets/046b2915-3dec-41ce-8fb7-c8879e352c28)

**Comment by JincanDeng** [comment]
@tridao Similar Question. Will the A100 benefit from acceleration by `Flash Attention v3`?

**Comment by tridao** [comment]
No, FA2 on A100 is already at around 70% theoretical max FLOPS and there's not much to do.

**Comment by guanzhchen** [comment]
Thanks for your reply!
