### ISSUE TITLE
what does the word commit means in FA3 algorithms?

### ISSUE THREAD

**Issue by QiqianFu** [Dao-AILab/flash-attention#1060]
What does the word commit means in algorithms? Like "Commit and wait". Who is the thread commiting to? Thanks for your answering!

**Comment by tridao** [comment]
https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#asynchronous-multiply-and-accumulate-instruction-wgmma-commit-group

**Comment by QiqianFu** [comment]
thank you so much!
