### ISSUE TITLE
Flash Attention 

### ISSUE THREAD

**Issue by tchaton** [Dao-AILab/flash-attention#108]
Hey @tridao and al.

Thanks a lot for this amazing work ! Very inspiring.

I have just integrated Flash Attention + DeepSpeed with Stable Diffusion. Here is the PR: https://github.com/Lightning-AI/stablediffusion/pull/8 as I needed T4 support and DeepSpeed Triton failed with this error: https://github.com/openai/triton/issues/1054
 
I had to re-implement a Flash Attention nn.Layer. I didn't find the block I was looking for in the repo.

I have several questions about the current implementation of Flash Attention:

* Why is Flash Attention supported only if head_dim <= 128: https://github.com/Lightning-AI/stablediffusion/pull/8/files#diff-265a3c539db9e48afdf52256108d37ea414537b683d252e96e9595a207e4f090R344. I found this logic in both DeepSpeed and this repo.
* Do you know if there are any fixes for this one: https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/flash_attn_triton.py#L175
* With Stable Diffusion, Flash Attention are skipped when a context is passed. I wonder if the kernels could be made more flexible to accelerate the entire model. I believe it is possible to gain some X00 ms on the inference.

Again, thanks a lot !

Best regards,
T.C

**Comment by tridao** [comment]
Hi T.C., thanks for the kind words. Glad to see you guys are using it.

> * Why is Flash Attention supported only if head_dim <= 128: https://github.com/Lightning-AI/stablediffusion/pull/8/files#diff-265a3c539db9e48afdf52256108d37ea414537b683d252e96e9595a207e4f090R344. I found this logic in both DeepSpeed and this repo.

Our approach loads blocks of the input in shared memory (SRAM) to reduce GPU HBM reads/writes. When head dim is too large, we can't fit things in SRAM efficiently. As a result, we only support headdim <= 128.

> * Do you know if there are any fixes for this one: https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/flash_attn_triton.py#L175

That was a workaround for a bug in the Triton compiler. I hear the new Triton rewrite doesn't need this workaround, but I haven't tried.

**Comment by tchaton** [comment]
Hey @tridao. Thanks for the answer.

> Our approach loads blocks of the input in shared memory (SRAM) to reduce GPU HBM reads/writes. When head dim is too large, we can't fit things in SRAM efficiently. As a result, we only support headdim <= 128.

Do you believe this could be supported with lopping and extra padding ?

> With Stable Diffusion, Flash Attention are skipped when a context is passed. I wonder if the kernels could be made more flexible to accelerate the entire model. I believe it is possible to gain some X00 ms on the inference.

Do you have any thoughts on this one ? Only half of the attention layers are converted.

**Comment by tridao** [comment]
> Do you believe this could be supported with lopping and extra padding ?

No, headdim > 128 is probably much more difficult to get speedup (and much harder to implement).
 
> > With Stable Diffusion, Flash Attention are skipped when a context is passed. I wonder if the kernels could be made more flexible to accelerate the entire model. I believe it is possible to gain some X00 ms on the inference.
> 
> Do you have any thoughts on this one ? Only half of the attention layers are converted.

If I understand correctly, when `context` is passed in your case, you're doing cross-attention instead of self-attention. We support cross-attention ([here](https://github.com/HazyResearch/flash-attention/blob/f68d41ec7768db6c5578ca8718d081de36fa1246/flash_attn/modules/mha.py#L108) as an example).

**Comment by DanFu09** [comment]
If you’re interested, we integrated FlashAttention into stable diffusion in
the diffusers repo. You can see this diff for how we did it, it may help:
https://github.com/HazyResearch/diffusers/commit/fd45ca2afb26d013e954ccbeba8b639c4783b270?diff=unified#diff-852d5806e41c100ee99c68c9e1059bfad9c0177e6f4416f0faf5a2f2a6a64067

**Comment by tchaton** [comment]
Hey @tridao @DanFu09 Thanks a lot ! I will benchmark them and give back my results. Very much appreciated.

**Comment by tchaton** [comment]
Hey @DanFu09. I just tried for folks of diffusers and got the following issue:

```
Traceback (most recent call last):
  File "scripts/txt2img_hf.py", line 59, in <module>
    pipe = diffusers.StableDiffusionPipeline.from_pretrained(
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/diffusers/pipeline_utils.py", line 496, in from_pretrained
    raise ValueError(
ValueError: The component <class 'transformers.models.clip.image_processing_clip.CLIPImageProcessor'> of <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> cannot be loaded as it does not seem to have any of the loading methods defined in {'ModelMixin': ['save_pretrained', 'from_pretrained'], 'SchedulerMixin': ['save_config', 'from_config'], 'DiffusionPipeline': ['save_pretrained', 'from_pretrained'], 'OnnxRuntimeModel': ['save_pretrained', 'from_pretrained'], 'PreTrainedTokenizer': ['save_pretrained', 'from_pretrained'], 'PreTrainedTokenizerFast': ['save_pretrained', 'from_pretrained'], 'PreTrainedModel': ['save_pretrained', 'from_pretrained'], 'FeatureExtractionMixin': ['save_pretrained', 'from_pretrained']}.
```

Anyway, I will just copy your code over a more recent version and give it a try.

**Comment by tchaton** [comment]
I am getting this one now.

```python
    return self.unet(sample, timestamp, encoder_hidden_states, return_dict)
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 424, in forward
    sample, res_samples = downsample_block(
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 777, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/diffusers/models/attention.py", line 227, in forward
    hidden_states = block(hidden_states, encoder_hidden_states=encoder_hidden_states, timestep=timestep)
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/deepspeed/ops/transformer/inference/diffusers_transformer_block.py", line 102, in forward
    out_attn_1 = self.attn_1(out_norm_1)
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/diffusers/models/attention.py", line 657, in forward
    hidden_states = self._attention(query, key, value, attention_mask)
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/diffusers/models/attention.py", line 688, in _attention
    out, _ = self.flash_attn(qkv)
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thomas/flash-attention/flash_attn/flash_attention.py", line 47, in forward
    output = flash_attn_unpadded_qkvpacked_func(
  File "/home/thomas/flash-attention/flash_attn/flash_attn_interface.py", line 267, in flash_attn_unpadded_qkvpacked_func
    return FlashAttnQKVPackedFunc.apply(qkv, cu_seqlens, max_seqlen, dropout_p, softmax_scale,
  File "/home/thomas/flash-attention/flash_attn/flash_attn_interface.py", line 58, in forward
    out, softmax_lse, S_dmask = _flash_attn_forward(
  File "/home/thomas/flash-attention/flash_attn/flash_attn_interface.py", line 21, in _flash_attn_forward
    softmax_lse, *rest = flash_attn_cuda.fwd(
RuntimeError: Expected (head_size % 8 == 0) && (head_size <= 128) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

Investigating if this is a bug on my side.

**Comment by DanFu09** [comment]
We don’t support head size larger than 128, so you need to manually check
before running flash attention. I believe it’s only a few layers of the
unet that are affected.

**Comment by tchaton** [comment]
Sure. But I thought your implementation in diffusers already skipped this case. My bad.

**Comment by DanFu09** [comment]
It should with this line: https://github.com/HazyResearch/diffusers/blob/main/src/diffusers/models/attention.py#L270

And this line: https://github.com/HazyResearch/diffusers/blob/main/src/diffusers/models/attention.py#L317

Do you have the equivalents in your implementation? Let me know if it still triggers that bug with that gating!

**Comment by tchaton** [comment]
Yes, I copied your code exactly and it happened. I will try again next week to add cross attention. I will keep you updated.

**Comment by roywei** [comment]
Hi, I had the exact same error when trying to train GPT using Megatron-LM, I see flash attn is recently integrated, @DanFu09 @tridao could you point to me where should I add a check for dim size? Thanks! 
https://github.com/NVIDIA/Megatron-LM
my launch command:
```
python /fsx/Megatron-LM/pretrain_gpt.py \
  --tensor-model-parallel-size 8 \
  --pipeline-model-parallel-size 8 \
  --num-layers 24 \
  --hidden-size 4096 \
  --num-attention-heads 16 \
  --micro-batch-size 4 \
  --global-batch-size $((8*$NNODES)) \
  --seq-length 1024 \
  --max-position-embeddings 1024 \
  --train-iters 1000 \
  --lr-decay-iters 320000 \
  --save $CHECKPOINT_PATH \
  --load $CHECKPOINT_PATH \
  --data-path $DATA_PATH \
  --vocab-file ${VOCAB_FILE} \
  --merge-file ${MERGES_FILE} \
  --data-impl mmap \
  --split 949,50,1 \
  --distributed-backend nccl \
  --lr 0.00015 \
  --lr-decay-style cosine \
  --min-lr 1.0e-5 \
  --weight-decay 1e-2 \
  --clip-grad 1.0 \
  --lr-warmup-fraction .01 \
  --recompute-granularity=full --recompute-method=uniform \
  --log-interval 100 \
  --save-interval 10000 \
  --eval-interval 1000 \
  --eval-iters 10 \
  --fp16 \
  --use-flash-attn
```

**Comment by tridao** [comment]
We support head dimensions <= 128.
You could add a check [here](https://github.com/NVIDIA/Megatron-LM/blob/285068c8108e0e8e6538f54fe27c3ee86c5217a2/megatron/model/transformer.py#L379).

**Comment by roywei** [comment]
raise a PR to Megatron, @tridao could you help take a look? thanks!
