### ISSUE TITLE
Does it support RelPositionMultiHeadedAttention in Transformer-XL?

### ISSUE THREAD

**Issue by hexisyztem** [Dao-AILab/flash-attention#1080]
flash attn calculates: (softmax(Q @ K^T * softmax_scale) @ V), but RelPositionMultiHeadedAttention replaces Q @ K^T with (Q + pos_bias_u) @ K^T + (Q + pos_bias_v) @ P^T.
So now, how can I use flash attn to optimize RelPositionMultiHeadedAttention?
https://arxiv.org/pdf/1901.02860

**Comment by tridao** [comment]
Probably not

**Comment by hexisyztem** [comment]
> Probably not

Ok, Thanks

**Comment by hexisyztem** [comment]
> Probably not

https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/attention.py#L413
I saw an interesting implementation that uses a mask to achieve the goal. Typically, the mask factor is ignored in the SDPA expression. This implementation is intriguing, but this approach is not commonly used.

**Comment by raman-r-4978** [comment]
Hi @tridao 

I was curious if the `flash_attn_varlen_func` method could resolve this or if there is another technique/trick available?

**Comment by tridao** [comment]
I don't think so.

**Comment by raman-r-4978** [comment]
Ok Thanks.

I use the implementation from here https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/parts/submodules/multi_head_attention.py#L159 and was wondering if there's a way to speed up the process since using `RelPositionMultiHeadAttention` tends to be quite slow overall.

**Comment by raman-r-4978** [comment]
Ok Thanks.

I use the implementation from here https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/parts/submodules/multi_head_attention.py#L159 and was wondering if there's a way to speed up the process since using `RelPositionMultiHeadAttention` tends to be quite slow overall.


@tridao You have any plans to support TransformerXL attention type in the future?

**Comment by tridao** [comment]
I personally don't, but feel free to work on it if you need it.
