### ISSUE TITLE
In Appendix B, I'm curious why the normalization constants of the softmax are defined as \( q^T k \) instead of \( q k^T \).

### ISSUE THREAD

**Issue by koreajiyeon** [Dao-AILab/flash-attention#1082]
In Appendix B, I'm curious why the normalization constants of the softmax are defined as \( q^T k \) instead of \( q k^T \).

**Comment by tridao** [comment]
If you treat q and k as vectors of shape (headdim), then q^T k makes sense (dot product between vectors).
If you treat Q and K as matrices of shape (seqlen, headdim), then Q K^T makes sense (to produce a score of shape seqlen x seqlen).
