### ISSUE TITLE
Unclear install instructions for ROCm backend

### ISSUE THREAD

**Issue by garrettbyrd** [Dao-AILab/flash-attention#1086]
The install instructions for ROCm in the `README` recommend usage in a Docker container, but do not accurately list specific requirements otherwise. This impedes usage on non-containerized systems.

Specific install steps such as `pip install packaging` [are provided in the CUDA install instructions](https://github.com/Dao-AILab/flash-attention/blob/59594f2a67eb6a9de730b4f8fe90baa89c5439d3/README.md?plain=1#L78); conversely, [this is not even listed as a requirement](https://github.com/Dao-AILab/flash-attention/blob/59594f2a67eb6a9de730b4f8fe90baa89c5439d3/README.md?plain=1#L440) in the ROCm instructions.

Similarly, the CUDA instructions [recommend installing `ninja`](https://github.com/Dao-AILab/flash-attention/blob/59594f2a67eb6a9de730b4f8fe90baa89c5439d3/README.md?plain=1#L79); is this required or recommended for ROCm installation?

I.e, it is unclear to the user which packages should be installed prior to running `python setup.py install`.

**Comment by carlushuang** [comment]
cc @rocking5566

**Comment by rocking5566** [comment]
I suggest to use this docker
 rocm/pytorch:rocm6.1.3_ubuntu22.04_py3.10_pytorch_release-2.1.2
If you have MI200 or MI300 with this docker, just `python setup.py install`, everything should be ok.

**Comment by garrettbyrd** [comment]
@rocking5566 Not everyone wants to use Docker all the time. Also, does the ROCm installation work with ninja to do multithreaded compilation? I have seen others posting about long compilation times (for me personally, this has been 15+ hours, compared to the ~10 minute compilation time for CUDA with ninja). Any communication on this would be nice.

**Comment by rocking5566** [comment]
@garrettbyrd 
1. we share the same required python package, because we share the same python api. In addition, packaging are listed in [setup.py](https://github.com/Dao-AILab/flash-attention/blob/59594f2a67eb6a9de730b4f8fe90baa89c5439d3/setup.py#L528-L530)
2. About the compilation method, ROCm FA2 and CUDA FA2 share the same setup.py. Hence, ROCm also support multithreaded compilation. However, we know the compilation time of ROCm backend is stiil too long....  we will improve it in the future

**Comment by garrettbyrd** [comment]
@rocking5566 Right now for AMD GPU/ROCm Support all that is listed under requirements is:

> Requirements:
> - ROCm 6.0+
> - PyTorch 1.12.1+

This is just a partial list of requirement that causes confusion; the user needs more than just ROCm and PyTorch. Either explicit say that all Python dependencies can be found in `setup,py` + ROCm 6.0+ (the less user friendly way of documenting things), or explicitly list out dependencies.

It should also be clear that ROCm DOES support multithreaded compilation.

> About the compilation method, ROCm FA2 and CUDA FA2 share the same setup.py. Hence, ROCm also support multithreaded compilation.

**Comment by rocking5566** [comment]
The required python package listed here is same as original flash attention, except to replace CUDA with ROCm. 
I will noted this in next sending PR to upstream.

**Comment by garrettbyrd** [comment]
The main install instructions do mention `packaging` and `ninja` ([link](https://github.com/Dao-AILab/flash-attention?tab=readme-ov-file#installation-and-features)):

> 1. Make sure that PyTorch is installed.
> 2. Make sure that `packaging` is installed (`pip install packaging`)
> 3. Make sure that `ninja` is installed and that it works correctly (e.g. `ninja --version` then `echo $?` should return exit code 0). If not (sometimes `ninja --version` then `echo $?` returns a nonzero exit code), uninstall then reinstall `ninja` (`pip uninstall -y ninja && pip install ninja`). Without `ninja`, compiling can take a very long time (2h) since it does not use multiple CPU cores. With `ninja` compiling takes 3-5 minutes on a 64-core machine.

This all could be cleared up with a line like "If you are not using Docker, follow the normal install steps for `flash attention`.", and perhaps mentioning that multithreaded compilation is supported for ROCm as well.

**Comment by garrettbyrd** [comment]
@rocking5566 Actually an even more elegant solution would just be to provide different subsections for CUDA and ROCm support in the `Installation and Features` section. (Currently there are two `Installation and Features` sections.) This would be a bit more readable regardless of backend. 

A solution might look something like the README I've adjusted and provide [here](https://github.com/garrettbyrd/flash-attention). Let me know if I should PR.

**Comment by garrettbyrd** [comment]
Went ahead and made a [PR](https://github.com/Dao-AILab/flash-attention/pull/1147).

**Comment by rocking5566** [comment]
> Went ahead and made a [PR](https://github.com/Dao-AILab/flash-attention/pull/1147).

Good job! @garrettbyrd 
It looks elegant now.

**Comment by garrettbyrd** [comment]
PR was merged, so I'm closing this.
