### ISSUE TITLE
AssertionError pytest -q -s test_flash_attn.py

### ISSUE THREAD

**Issue by praveenperfecto** [Dao-AILab/flash-attention#1102]
E       AssertionError: assert 3.92578125 <= (2 * 0.001953125)
E        +  where 3.92578125 = <built-in method item of Tensor object at 0x7f52ee095120>()
E        +    where <built-in method item of Tensor object at 0x7f52ee095120> = tensor(3.9258, device='cuda:0', dtype=torch.float16, grad_fn=<MaxBackward1>).item
E        +      where tensor(3.9258, device='cuda:0', dtype=torch.float16, grad_fn=<MaxBackward1>) = <built-in method max of Tensor object at 0x7f52ee097470>()
E        +        where <built-in method max of Tensor object at 0x7f52ee097470> = tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 4.8828e-04,\n           0.0000e+00, 0.0000e+00],\n          [1.2207...0.0000e+00,\n           0.0000e+00, 0.0000e+00]]]], device='cuda:0', dtype=torch.float16,\n       grad_fn=<AbsBackward0>).max
E        +          where tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 4.8828e-04,\n           0.0000e+00, 0.0000e+00],\n          [1.2207...0.0000e+00,\n           0.0000e+00, 0.0000e+00]]]], device='cuda:0', dtype=torch.float16,\n       grad_fn=<AbsBackward0>) = <built-in method abs of Tensor object at 0x7f52ee094bd0>()
E        +            where <built-in method abs of Tensor object at 0x7f52ee094bd0> = (tensor([[[[-1.5469e+00, -1.0078e+00,  8.1641e-01,  ...,  6.7432e-01,\n            9.5898e-01, -2.3071e-01],\n          [...000e+00,\n            0.0000e+00,  0.0000e+00]]]], device='cuda:0', dtype=torch.float16,\n       grad_fn=<ViewBackward0>) - tensor([[[[-1.5469e+00, -1.0078e+00,  8.1641e-01,  ...,  6.7480e-01,\n            9.5898e-01, -2.3071e-01],\n          [...0e+00,\n            0.0000e+00,  0.0000e+00]]]], device='cuda:0', dtype=torch.float16,\n       grad_fn=<ToCopyBackward0>)).abs
E        +  and   0.001953125 = <built-in method item of Tensor object at 0x7f52ee0d1b20>()
E        +    where <built-in method item of Tensor object at 0x7f52ee0d1b20> = tensor(0.0020, device='cuda:0', dtype=torch.float16, grad_fn=<MaxBackward1>).item
E        +      where tensor(0.0020, device='cuda:0', dtype=torch.float16, grad_fn=<MaxBackward1>) = <built-in method max of Tensor object at 0x7f52ee0d1620>()
E        +        where <built-in method max of Tensor object at 0x7f52ee0d1620> = tensor([[[[9.7656e-04, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,\n           0.0000e+00, 0.0000e+00],\n          [2.4414...0.0000e+00,\n           0.0000e+00, 0.0000e+00]]]], device='cuda:0', dtype=torch.float16,\n       grad_fn=<AbsBackward0>).max
E        +          where tensor([[[[9.7656e-04, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,\n           0.0000e+00, 0.0000e+00],\n          [2.4414...0.0000e+00,\n           0.0000e+00, 0.0000e+00]]]], device='cuda:0', dtype=torch.float16,\n       grad_fn=<AbsBackward0>) = <built-in method abs of Tensor object at 0x7f52ee0d2840>()
E        +            where <built-in method abs of Tensor object at 0x7f52ee0d2840> = (tensor([[[[-1.5479e+00, -1.0078e+00,  8.1641e-01,  ...,  6.7480e-01,\n            9.5898e-01, -2.3071e-01],\n          [...00,\n            0.0000e+00,  0.0000e+00]]]], device='cuda:0', dtype=torch.float16,\n       grad_fn=<AsStridedBackward0>) - tensor([[[[-1.5469e+00, -1.0078e+00,  8.1641e-01,  ...,  6.7480e-01,\n            9.5898e-01, -2.3071e-01],\n          [...0e+00,\n            0.0000e+00,  0.0000e+00]]]], device='cuda:0', dtype=torch.float16,\n       grad_fn=<ToCopyBackward0>)).abs

test_flash_attn.py:304: AssertionError
================================================================= short test summary info =================================================================
FAILED test_flash_attn.py::test_flash_attn_varlen_output[1024-1024-256-mha-True-dtype0] - AssertionError: assert 4.6875 <= (2 * 0.001953125)
FAILED test_flash_attn.py::test_flash_attn_varlen_output[1024-1024-256-gqa-True-dtype0] - AssertionError: assert 3.287109375 <= (2 * 0.001953125)
FAILED test_flash_attn.py::test_flash_attn_varlen_output[1023-1024-256-mha-True-dtype0] - AssertionError: assert 4.43359375 <= (2 * 0.001953125)
FAILED test_flash_attn.py::test_flash_attn_varlen_output[1023-1024-256-mqa-True-dtype0] - AssertionError: assert 3.57421875 <= (2 * 0.001953125)
FAILED test_flash_attn.py::test_flash_attn_varlen_output[1023-1024-256-gqa-True-dtype0] - AssertionError: assert 3.53125 <= (2 * 0.001953125)
FAILED test_flash_attn.py::test_flash_attn_varlen_output[1024-1023-256-mha-True-dtype0] - AssertionError: assert 4.234375 <= (2 * 0.001953125)
FAILED test_flash_attn.py::test_flash_attn_varlen_output[1024-1023-256-mqa-True-dtype0] - AssertionError: assert 3.50390625 <= (2 * 0.001953125)
FAILED test_flash_attn.py::test_flash_attn_varlen_output[2048-2048-256-mha-True-dtype0] - AssertionError: assert 3.521484375 <= (2 * 0.001953125)
FAILED test_flash_attn.py::test_flash_attn_varlen_output[2048-2048-256-mqa-True-dtype0] - AssertionError: assert 3.265625 <= (2 * 0.001953125)
FAILED test_flash_attn.py::test_flash_attn_varlen_output[2048-2048-256-gqa-True-dtype0] - AssertionError: assert 3.92578125 <= (2 * 0.001953125)
10 failed, 908 passed in 7.23s

**Comment by peiji1981** [comment]
I also got this AssertionError, cuda12.5+torch  2.4.0a0+3bcc3cddb5.nv24.7
E           AssertionError: assert 0.0078125 <= ((2 * 0.0) + 3e-05)
E            +  where 0.0078125 = <built-in method item of Tensor object at 0x7fa74b5fa2f0>()
E            +    where <built-in method item of Tensor object at 0x7fa74b5fa2f0> = tensor(0.0078, device='cuda:0', dtype=torch.float16).item
E            +      where tensor(0.0078, device='cuda:0', dtype=torch.float16) = <built-in method max of Tensor object at 0x7fa74b5fb420>()
E            +        where <built-in method max of Tensor object at 0x7fa74b5fb420> = tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0...., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.]]]], device='cuda:0',\n       dtype=torch.float16).max
E            +          where tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0...., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.]]]], device='cuda:0',\n       dtype=torch.float16) = <built-in method abs of Tensor object at 0x7fa50cafe0c0>()
E            +            where <built-in method abs of Tensor object at 0x7fa50cafe0c0> = (tensor([[[[ 42.0625,   0.7002,   0.4998,  ..., -23.4062,   2.9160, -15.3984],\n          [-12.4141,  -6.9219, -31.0469,...    [-13.4219,  14.6875,  19.7188,  ..., -32.6250,  29.8125,   6.9141]]]],\n       device='cuda:0', dtype=torch.float16) - tensor([[[[ 42.0625,   0.7002,   0.4998,  ..., -23.4062,   2.9160, -15.3984],\n          [-12.4141,  -6.9219, -31.0469,...    [-13.4219,  14.6875,  19.7188,  ..., -32.6250,  29.8125,   6.9141]]]],\n       device='cuda:0', dtype=torch.float16)).abs
E            +  and   0.0 = <built-in method item of Tensor object at 0x7fa731a5bb00>()
E            +    where <built-in method item of Tensor object at 0x7fa731a5bb00> = tensor(0., device='cuda:0', dtype=torch.float16).item
E            +      where tensor(0., device='cuda:0', dtype=torch.float16) = <built-in method max of Tensor object at 0x7fa749378c20>()
E            +        where <built-in method max of Tensor object at 0x7fa749378c20> = tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0...., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.]]]], device='cuda:0',\n       dtype=torch.float16).max
E            +          where tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0...., 0., 0.,  ..., 0., 0., 0.],\n          [0., 0., 0.,  ..., 0., 0., 0.]]]], device='cuda:0',\n       dtype=torch.float16) = <built-in method abs of Tensor object at 0x7fa4b8832e80>()
E            +            where <built-in method abs of Tensor object at 0x7fa4b8832e80> = (tensor([[[[ 42.0625,   0.7002,   0.4998,  ..., -23.4062,   2.9160, -15.3984],\n          [-12.4141,  -6.9219, -31.0469,...    [-13.4219,  14.6875,  19.7188,  ..., -32.6250,  29.8125,   6.9141]]]],\n       device='cuda:0', dtype=torch.float16) - tensor([[[[ 42.0625,   0.7002,   0.4998,  ..., -23.4062,   2.9160, -15.3984],\n          [-12.4141,  -6.9219, -31.0469,...    [-13.4219,  14.6875,  19.7188,  ..., -32.6250,  29.8125,   6.9141]]]],\n       device='cuda:0', dtype=torch.float16)).abs

**Comment by tridao** [comment]
it's fine

**Comment by Selimonder** [comment]
> it's fine

are you sure?

I recently ran a previous baseline (FA2) and later FA3, both **varlen**. Despite the identical setup, FA3 loss performs consistently worse.

**Comment by tridao** [comment]
Can you post a short script with a test to help us reproduce the difference?

**Comment by PoCCRK** [comment]
Hi, I have similar unit test fail on FlashAttention recently.
Test on H100, in a container nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04.
PyTorch and packaging are installed by pip, FlashAttention is compile from source.

```
python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
python3 -m pip install packaging pillow requests jinja2 triton networkx numpy tqdm urllib3 certifi setuptools --index-url https://download.pytorch.org/whl/cu124
git clone https://github.com/Dao-AILab/flash-attention.git /tmp/flash-attention
cd /tmp/flash-attention
git submodule update --init --recursive
python3 setup.py install
pytest -q -s tests/test_flash_attn.py
```

Here is the log

```
FAILED tests/test_flash_attn.py::test_flash_attn_splitkv[1-339-True-160-False-False-True-False-dtype0] - AssertionError: assert 0.00390625 <= ((8 * 0.0) + 0.0002)
FAILED tests/test_flash_attn.py::test_flash_attn_splitkv[1-339-True-160-False-False-True-True-dtype0] - AssertionError: assert 0.00390625 <= ((8 * 0.0) + 0.0002)
FAILED tests/test_flash_attn.py::test_flash_attn_splitkv[16-100000-False-96-True-False-True-False-dtype0] - AssertionError: assert 0.0020751953125 <= ((2 * 0.0009765625) + 1e-05)
FAILED tests/test_flash_attn.py::test_flash_attn_splitkv[16-100000-False-96-True-False-True-True-dtype0] - AssertionError: assert 0.0020751953125 <= ((2 * 0.0009765625) + 1e-05)
4 failed, 312352 passed, 196416 skipped in 5006.33s (1:23:26)
```

I also test FlashAttention-3, shown below

```
git clone https://github.com/Dao-AILab/flash-attention.git /tmp/flash-attention
cd /tmp/flash-attention
git submodule update --init --recursive
cd hopper
python3 setup.py install
export PYTHONPATH=$PWD
pytest -q -s test_flash_attn.py
```

```
FAILED test_flash_attn.py::test_flash_attn_output[257-1-128-False-False-mha-dtype0] - AssertionError: assert 0.0078125 <= ((2 * 0.0) + 3e-05)
FAILED test_flash_attn.py::test_flash_attn_output[257-1-128-True-False-mha-dtype0] - AssertionError: assert 0.0078125 <= ((2 * 0.0) + 3e-05)
2 failed, 1726 passed in 29.76s
```

**Comment by tridao** [comment]
Those differences are fine.
