### ISSUE TITLE
Resampler is not used in Monkey?

### ISSUE THREAD

**Issue by cpystan** [Dao-AILab/flash-attention#1117]
You have done a great work. And I have a few questions.
In your figure of Monkey, the embeddings are processed with Resampler before feeding to the Qwen-VL.
But when I run the code, I find no resample code in Monkey.
In modeling_monkey.py, line 80, image features are directly given to the Qwen-VL.
I would be so grateful if you could give me some guidance.

**Comment by tridao** [comment]
I'm guessing you meant to post in a different repo

**Comment by cpystan** [comment]
sorry, it is my fault
