### ISSUE TITLE
[FA3] compile error of bwd kernel  in latest update

### ISSUE THREAD

**Issue by endurehero** [Dao-AILab/flash-attention#1118]
I meet the complie error like below when using nvcc12.3
![image](https://github.com/user-attachments/assets/296c5ac8-2067-4919-afa4-521c90ba059e)
It doesn't seem necessary to wrap another layer with aligned struct, since all member variables are already aligned?

**Comment by tridao** [comment]
Ha, strange. I compiled with nvcc 12.3.107 (gcc 11.4.0 on Ubuntu 22.04) and it was fine.
I wonder if it's an issue with gcc version as well.

**Comment by LaurentMazare** [comment]
As another datapoint, I was running into the same issue on an ubuntu 22.04 with the following setting:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0

# The ccbin used by nvcc by default
$ .../conda-envs/jax3/bin/x86_64-conda-linux-gnu-c++ --version
x86_64-conda-linux-gnu-c++ (conda-forge gcc 12.3.0-13) 12.3.0
```
The actual error I got:
```
.../csrc/flash_bwd_kernel.h:75:8: error: anonymous struct with base classes
   75 |         struct : cute::aligned_struct<1024> {
      |        ^
.../csrc/flash_bwd_kernel.h:82:8: error: anonymous struct with base classes
   82 |         struct : cute::aligned_struct<16> {
      |        ^

```

Switching to clang via `-ccbin clang-14` seemed to have fixed the issue for me (and now the backward appears to work well :tada: ).

**Comment by tridao** [comment]
I'm guessing it's an issue with gcc 12. Will investigate

**Comment by tridao** [comment]
I'm removing the `struct : cute::aligned_struct<1024>` for now.

**Comment by LaurentMazare** [comment]
> I'm removing the `struct : cute::aligned_struct<1024>` for now.

Thanks, that fixed it for me and I don't need the `-ccbin` flag anymore.
