### ISSUE TITLE
 Why FA3 extension need to add compile Flag NDEBUG?

### ISSUE THREAD

**Issue by MARD1NO** [Dao-AILab/flash-attention#1120]
I found in hopper extension, it need to add compile FLAG NDEBUG, but it is no need in origin FA2 extension. 

I also test there exist performance gap with/without NDEBUG compile flag in FA3, and I'm not very clear the mechanism, since I have not found some clues about NDEBUG in cutlass code, can you explain this ? :D

**Comment by tridao** [comment]
"NDEBUG" is what Cutlass recommends. You can search for it in cutlass.

**Comment by MARD1NO** [comment]
> "NDEBUG" is what Cutlass recommends. You can search for it in cutlass.

Thanks for your quick reply! :D
