### ISSUE TITLE
FA3 setup failed: flash_bwd_hdim128_bf16_sm90.o  flash_fwd_hdim128_bf16_sm90.o ,... compilation terminated.

### ISSUE THREAD

**Issue by GMALP** [Dao-AILab/flash-attention#1131]
H800 CUDA12.3 FA3 test 

cd hopper
python setup.py install

FAILED: /test/flash-attention/hopper/build/temp.linux-x86_64-cpython-310/flash_fwd_hdim64_fp16_sm90.o
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /test/flash-attention/hopper/build/temp.linux-x86_64-cpython-310/flash_fwd_hdim64_fp16_sm90.o.d -I/test/flash-attention/csrc/cutlass/include -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c -c /test/flash-attention/hopper/flash_fwd_hdim64_fp16_sm90.cu -o /test/flash-attention/hopper/build/temp.linux-x86_64-cpython-310/flash_fwd_hdim64_fp16_sm90.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS_-U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v --ptxas-options=--verbose,--register-usage-level=10,--warn-on-local-memory-usage -lineinfo -DCUTLASS_DEBUG_TRACE_LEVEL=0 -DNDEBUG -gencode arch=compute_90a,code=sm_90a --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1016"' -DTORCH_EXTENSION_NAME=flashattn_hopper_cuda -D_GLIBCXX_USE_CXX11_ABI=1
In file included from /test/flash-attention/hopper/flash_fwd_hdim64_fp16_sm90.cu:4:
/test/flash-attention/hopper/flash_fwd_launch_template.h:7:10: fatal error: cute/tensor.hpp: No such file or directory
    7 | #include "cute/tensor.hpp"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /test/flash-attention/hopper/flash_fwd_hdim64_fp16_sm90.cu:4:
/test/flash-attention/hopper/flash_fwd_launch_template.h:7:10: fatal error: cute/tensor.hpp: No such file or directory
    7 | #include "cute/tensor.hpp"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
fatal   : Could not open input file /tmp/tmpxft_00000f4d_00000000-7_flash_fwd_hdim64_fp16_sm90.cpp1.ii
![1](https://github.com/user-attachments/assets/c31f7a6d-85d5-4d35-8003-8695da1cf2cd)

**Comment by foreverlms** [comment]
Question:
1. A100 isn't hooper Arch. Why would this happen?
2. It seems there are problems with cutlass. Have you synced cutlass?

**Comment by GMALP** [comment]
> Question:
> 
> 1. A100 isn't hooper Arch. Why would this happen?
       ok, will test on the H800.
> 2. It seems there are problems with cutlass. Have you synced cutlass? 
       yes

**Comment by foreverlms** [comment]
> > Question:
> > 
> > 1. A100 isn't hooper Arch. Why would this happen?
> >    ok, will test on the H800. H800 same error...
> > 2. It seems there are problems with cutlass. Have you synced cutlass?
> >    cutlass 3.5.0 and  same error again.
> 
> ![image](https://private-user-images.githubusercontent.com/92301386/356441695-8adaf6c5-4915-4bff-b4df-fdd2f4979340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzIyMjAsIm5iZiI6MTcyMzE3MTkyMCwicGF0aCI6Ii85MjMwMTM4Ni8zNTY0NDE2OTUtOGFkYWY2YzUtNDkxNS00YmZmLWI0ZGYtZmRkMmY0OTc5MzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAyNTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNGY4NDczYTljODI3NmYxY2JmYzhiNzM1ZDBkZGRjMjJkODc5MWVlODY3M2NhMjVlMWY4Yjc4N2FlYWVlMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sUpEUzB6bU3ohv0hvqtx8i9dTt4nV-hxZSVFHp0G5k8)

This is installed on your system? FA2 uses its own cutlass in `csrc/cutlass`. You should clone this submodule and have a try.

**Comment by GMALP** [comment]
> > > Question:
> > > 
> > > 1. A100 isn't hooper Arch. Why would this happen?
> > >    ok, will test on the H800. H800 same error...
> > > 2. It seems there are problems with cutlass. Have you synced cutlass?
> > >    cutlass 3.5.0 and  same error again.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/92301386/356441695-8adaf6c5-4915-4bff-b4df-fdd2f4979340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzIyMjAsIm5iZiI6MTcyMzE3MTkyMCwicGF0aCI6Ii85MjMwMTM4Ni8zNTY0NDE2OTUtOGFkYWY2YzUtNDkxNS00YmZmLWI0ZGYtZmRkMmY0OTc5MzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAyNTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNGY4NDczYTljODI3NmYxY2JmYzhiNzM1ZDBkZGRjMjJkODc5MWVlODY3M2NhMjVlMWY4Yjc4N2FlYWVlMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sUpEUzB6bU3ohv0hvqtx8i9dTt4nV-hxZSVFHp0G5k8)
> 
> This is installed on your system? FA2 uses its own cutlass in `csrc/cutlass`. You should clone this submodule and have a try.
    ok, thanks very much.


test results are 2 failed, 1726 passed , is this result normal?
![image](https://github.com/user-attachments/assets/29b89a7a-2810-4c19-9e1c-b9190b5e19f8)

**Comment by tridao** [comment]
Yes, I'll relax those tests.
