### ISSUE TITLE
The impact of setting head dim to an unconventional value on the algorithm's running speed

### ISSUE THREAD

**Issue by CSlearnerZM** [Dao-AILab/flash-attention#1141]
When we used megatron to pretrain a LLM model, we accidentally set `head_dim` to 132, and found that the training speed dropped significantly. Considering that the conventional setting of `head_dim` is generally 64, 128, 256, etc., I would like to ask whether some unconventional values ​​should not be set when using the flash-attn v2 algorithm? We also tried several other sets of unconventional values, and it seems that the results are all significantly reduced in speed.

environment setup:
1.GPU: 16*8 H100
2.model: 70B using GQA(similar to llama)
3.TP(Tensor Parallelism)=4, PP(Parallel Parallelism)=4, seq_len=8192

result:
head_dim=132->219 tflops
head_dim=128->370 tflops

**Comment by tridao** [comment]
That makes sense. Similarly if you try matrix multiply with some dimension being 132 instead of 128 you'll see speed difference. Most implementation would implicitly pad the dimensions to be multiples of 32 or 64 or 128 since that's what the tensor cores operate on.
