### ISSUE TITLE
CUDA Error： no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by qiuqiu10** [Dao-AILab/flash-attention#1146]
Hi I'm currently using jetson agx orin and i've just installed the latest version of flash-attention via "pip install flash-attn". It went smoothly but when i tried to use it in QServe i got the message: CUDA Error： no kernel image is available for execution on the device

I suppose it was due to the fact that gpu on jetson agx orin is of sm87 instead of sm80, which is the structure of A100. I looked into setup.py and found the '-gencode' option, maybe with this and 'code=sm_80' it points directly at sm_80, so sm_87 is not available. I'm not sure if my suspicion is correct, looking forward to any reply.

**Comment by tridao** [comment]
You can try changing setup.py and compiling from scratch.

**Comment by qiuqiu10** [comment]
thx i've changed setup.py and add my "code=sm87", it works!

**Comment by PeterBaelish** [comment]
> thx i've changed setup.py and add my "code=sm87", it works!

Hi, could you provide more details? I changed line 171 below in setup.py, but it still report the same error
> cc_flag.append("arch=compute_80,code=sm_80") -> cc_flag.append("arch=compute_87,code=sm_87")

**Comment by qiuqiu10** [comment]
Hi the solution is due to the fact that option '-gencode' needs the structure to be exactly the designated one, for example 

_cc_flag.append("-gencode")
cc_flag.append("arch=compute_80,code=sm_80")_

needs the structure to be exacly sm80. My jetson agx orin is of sm87 so changing it to 87 works. I can only provide you with the following explanation because i am not sure you are facing the exacly same problem, hope this helps

**Comment by PeterBaelish** [comment]
Thanks you, I uninstalled and follow your code again, it works!

**Comment by falkbene** [comment]
Thank you @qiuqiu10 for this tip. Just for anyone stumbling across this issue a clarification of what todo:

Add this to the setup.py file:
``` 
if "87" in cuda_archs(): 
        cc_flag.append("-gencode")
        cc_flag.append("arch=compute_87,code=sm_87")
```

and set your `FLASH_ATTN_CUDA_ARCHS` environment variable to `87`. Then build from source again:
`python setup.py install`. This should resolve the issue.
