### ISSUE TITLE
[Question] If I manually invoke backward, do I need to a specific stride for the gradients?

### ISSUE THREAD

**Issue by vedantroy** [Dao-AILab/flash-attention#1149]
I'm invoking the backwards pass of flash attention's `flash_attn_varlen_kvpacked_func` as follows:
```
flash_attn_output.backward(rearrange(grad, 'B N H D -> (B N) H D'))
```

where `grad` is some tensor created w/ `torch.randn`. But I'm getting results that differ from a vanilla re-implementation of attention. I'm wondering, does the grad tensor need a specific stride (maybe it has to match the stride of the output or something similar)? Seems unlikely, but wanted to check.

**Comment by vedantroy** [comment]
From looking at the code -- it seems like flash attention makes tensors contiguous if they aren't already, so this shouldn't be an issue, but ... maybe I'm missing something.

**Comment by tridao** [comment]
Only the last dimension needs to be contiguous (i.e. have stride 1).
