### ISSUE TITLE
Understanding the copy of return_softmax tensor P from register to global memory

### ISSUE THREAD

**Issue by phantaurus** [Dao-AILab/flash-attention#1154]
Hello! Could you help me understand in flash::compute_attn_1rowblock, why tOrP_copy can be directly copied to tPgP using gmem_tiled_copy_P?

```
if (Return_softmax) {
      Tensor tOrP_copy = make_fragment_like(tOrP);
      cute::copy(tOrP, tOrP_copy);
      // flash::apply_dropout</*encode_dropout_in_sign_bit=*/true>(
      //     tOrP_copy, params.p_dropout_in_uint8_t, seed, offset,
      //     block_row_idx, block_col_idx, kNWarps
      // );
      flash::write_softmax_to_gmem(tOrP_copy, tPgP, gmem_tiled_copy_P);
      tPgP.data() = tPgP.data() + (-kBlockN);
    }
```

tPgP is simply the gP tensor partitioned based on block index and thread index, which is quite continuous per thread.
However, tOrP is the MMA output per thread, and its layout doesn't seem to be continuous given the MMA used.

Could you help me figure out if this output strictly follow the layout of the tensor S = QxK? I tried to compare this tensor with my manually written algorithm, it seems that the values are mis-aligned. 

It seems more intuitive to use something like `auto smem_tiled_copy_O = make_tiled_copy_C(typename Kernel_traits::SmemCopyAtomO{}, tiled_mma);` first to copy P register value back to shared memory, because make_tiled_copy_C acutally considered the output layout of tiled_mma.

Thank you so much!

**Comment by tridao** [comment]
I don't think you're looking at the latest code. Please check the latest version.
In general `return_softmax` is purely for testing and we don't make any effort to make that fast.

**Comment by phantaurus** [comment]
I see. Thank you so much!
The latest version uses 
```
Tensor tSgS  = thr_mma.partition_C(gP);
```
which matches the layout of acc_s.
The values also match manual result.
