### ISSUE TITLE
Will FA3 mha_varlen_fwd support torch::kFloat8_e4m3fn?

### ISSUE THREAD

**Issue by goldhuang** [Dao-AILab/flash-attention#1157]
Is there a plan to support torch::kFloat8_e4m3fn in FA3 mha_**varlen**_fwd?

**Comment by tridao** [comment]
Yes

**Comment by goldhuang** [comment]
Thanks! Great to hear!
Will the support be available in few weeks or months?

**Comment by tridao** [comment]
Probably on the order of weeks
