### ISSUE TITLE
How to select a specific headdim file for quick compilation

### ISSUE THREAD

**Issue by eljrte** [Dao-AILab/flash-attention#1165]
I am trying to change the value of kBlockM/kBlockN etc. when debugging the csrc. However , everytime I change the value and compile the project, It will recompile all relevant files(like hdim32,hdim64,hdim128~~) and take quite long time. If I prefer to fix the hdim=64, what should I do to avoid complie all those things?really appreciate your ans.

**Comment by tridao** [comment]
you can comment out the code for the dimensions you don't need
https://github.com/Dao-AILab/flash-attention/blob/32792d37ec66902e5d82e149971daacbee8b55d7/csrc/flash_attn/src/flash_fwd_launch_template.h#L199

**Comment by eljrte** [comment]
really appreciate！However , after I comment out relevant code, delete relevent .cu file, change the setup.py , python setup.py build_ext --inplace, I run the pytest and fail ： It says import error, undefined symbol for ~~.

**Comment by eljrte** [comment]
It says: undefined symbol: _Z12run_mha_fwd_IN7cutlass6half_tELi256ELb1EEvR16Flash_fwd_paramsP11CUstream_st
(void run_mha_fwd_<cutlass::half_t, 256, true>(Flash_fwd_params&, CUstream_st*    using c++filt)
And I use ldd -r, finding it is undefined.
But actually I cant find this function anywhere(as I have removed .cu file)

**Comment by eljrte** [comment]
I have cleaned the old build document and build the module from scratch again, still facing the same problem.I check the code carefully but cant figure out why(I didn't instantiate the template using other parameters than 64,but the pytest just tells me there is undefined symbol like run_mha_fwd<256,32~~>).really appreciate your tips.I have been troubled for days :(

**Comment by tridao** [comment]
You can comment out the body of `run_mha_fwd_hdim96` for example so that when it's called it does nothing. No need to change setup.py or deleting the .cu files.

**Comment by eljrte** [comment]
> You can comment out the body of `run_mha_fwd_hdim96` for example so that when it's called it does nothing. No need to change setup.py or deleting the .cu files.

Really appreciate your tips.Though it still needs to compile all the files, it is much faster. However , it seems not working on the run_mha_splitkv_dispatch, as all headdims go to the same function(I cant comment out run_mha_splitkv_dispatch )

**Comment by tridao** [comment]
You can just add `if constexpr (kHeadDim == 64) { // code here }` so it won't do anything for hdim other than 64.

**Comment by eljrte** [comment]
Really helful idea! It is much faster though still needs to compile all the files.
I have found another way to only compile the specific headdim file: I change the file of static_swith.h and comment out other headdim in macro HEADDIM_SWITCH. It actually works.
Thanks a lot.

**Comment by jpli02** [comment]
Hi, I am experience a slow compilation issue. Can you tell me what is the comilation time like when pip install from source after you comment other dim such as run_mha_fwd_hdim96. And how do you change the HEADDIM_SWITCH? I have changed into the following, but it still compile all the files.
`/** modification to only compile dim32 files */
#define HEADDIM_SWITCH(HEADDIM, ...)   \
  [&] {                                    \
    if (HEADDIM <= 32) {                   \
      constexpr static int kHeadDim = 32;  \
      return __VA_ARGS__();                \
    } \
  }()`

**Comment by eljrte** [comment]
> Hi, I am experience a slow compilation issue. Can you tell me what is the comilation time like when pip install from source after you comment other dim such as run_mha_fwd_hdim96. And how do you change the HEADDIM_SWITCH? I have changed into the following, but it still compile all the files.
> 
> #define HEADDIM_SWITCH(HEADDIM, ...) \
> 
> [&] { \
> 
> ```
> if (HEADDIM <= 32) {                   \
> 
>   constexpr static int kHeadDim = 32;  \
> 
>   return __VA_ARGS__();                \
> 
> } \
> ```
> 
> }()

Hellohello. After I install from source, everytime I change the csrc file I need to run "python setup.py build_ext --inplace " to recompile the csrc. I only concentrate on the inference phase , so I first commont out all the bwd-related function. Then, as I mentioned above, I know in advance that  I only need headdim=64, so I comment out all the other headdim function in flash_fwd_launch_template.h. To deal with the lambda in the function _run_mha_fwd_ in flash_api.cpp, I change the file static switch.h, where in HEADDIM_SWITCH I only provide kHeadDim=32 , in FP16_SWITCH I only provide cutlass::half_t. Then you need to change the setup.py file to only include the specific .cu file you need.
After all the operation , everytime I need to recompile, it only compiles 4-5files (as u can see, originally, most time is spent on compiling.cu file due to somany template), and it just takes like 3mins.
