### ISSUE TITLE
only the first wrap in the first wrap group do load Q K V

### ISSUE THREAD

**Issue by baoqianmagik** [Dao-AILab/flash-attention#1168]
static_assert(Ktraits::kNWarps == 12 || Ktraits::kNWarps == 16);
    if (warp_group_idx == 0) {  // Producer
        cutlass::arch::warpgroup_reg_dealloc<Ktraits::kNWarps == 12 ? 24 : 32>();
        // cutlass::arch::warpgroup_reg_dealloc<56>();

        int warp_idx_in_warpgroup = __shfl_sync(0xffffffff, (threadIdx.x / 32) % 4, 0);
        if (warp_idx_in_warpgroup == 0) {  // Load Q, K, V

I noticed that only the first wrap in the first wrap group do load Q K V,the other three wrap in the first wrap group do nothing,is there any possible to use the other three wrap to compute

**Comment by tridao** [comment]
No I don't think so. 
`warpgroup_reg_dealloc` applies to the entire warpgroup (4 warps) so warp 1, 2, 3 have very few registers.
