### ISSUE TITLE
[Feature] FA2 support for attention mask(shape: (seq_len, seq_len))

### ISSUE THREAD

**Issue by efsotr** [Dao-AILab/flash-attention#1177]
as titled cc @tridao @jayhshah

**Comment by tridao** [comment]
You're welcome to work on it if you need it

**Comment by efsotr** [comment]
@tridao Could you please point out the execution order of flash_attn and the files that need to be modified?

**Comment by tridao** [comment]
The fwd kernel is here:
https://github.com/Dao-AILab/flash-attention/blob/c92ca63268836a6ea519e9892eda4895fc31811d/csrc/flash_attn/src/flash_fwd_kernel.h#L49
