### ISSUE TITLE
[Question] Can doing context parallelism with flash attention yield slightly different results due to numerical error?

### ISSUE THREAD

**Issue by vedantroy** [Dao-AILab/flash-attention#1178]
I have `M` queries and `N` key/value pairs.

Is it possible I'll get different results by splitting the the queries in half along the sequence length, doing cross-attention (with flash attention) on each half, and then concatenating the output along the sequence length versus doing a single call to flash attention?

I am using `flash_attn_varlen_kvpacked_func` from FA2.

**Comment by tridao** [comment]
There's no guarantee that you'll get bitwise exactly the same result if you calculate the same quantities in two different ways. That's the nature of floating point math.
Example: `a + 0.3 - 0.3` is not exactly the same as `a`:
```
In [4]: import torch

In [5]: a = torch.rand(10, dtype=torch.bfloat16, device='cuda')

In [6]: (a + 0.3 - 0.3 - a).abs().max().item()
Out[6]: 0.00390625
```

**Comment by vedantroy** [comment]
Does flash attention use different kernels based on the number of queries? For context, I'm using `flash_attn_varlen_kvpacked_func`, and results are bitwise identical to ground truth when using context parallelism of size 2, but different when using context parallelism of size 4. (Splitting a 10K sequence into either 2 or 4 chunks).

**Comment by tridao** [comment]
It might use different kernel tile sizes. It has certain optimization of seqlen_q = 1 (and in the future this optimization can generalize to other values of seqlen_q). Similarly matmul (e.g. cuBLAS) will dispatch to different GEMM kernels depending on the matrix dimension, so there's no guarantee of bitwise identical results.
