### ISSUE TITLE
A question about softcap.

### ISSUE THREAD

**Issue by alex-ht** [Dao-AILab/flash-attention#1181]
in [csrc/flash_attn/src/utils.h](https://github.com/Dao-AILab/flash-attention/blob/c92ca63268836a6ea519e9892eda4895fc31811d/csrc/flash_attn/src/utils.h#L397)
`tensor(i) = cutlass::fast_tanh(tensor(i) * softcap);`
Should it be rewritten as `tensor(i) = cutlass::fast_tanh(tensor(i)) * softcap;`?

**Comment by tridao** [comment]
No, you can see the original discussion in the PR
https://github.com/Dao-AILab/flash-attention/pull/1025#issuecomment-2211414707

**Comment by alex-ht** [comment]
thank!
