### ISSUE TITLE
A question about better transformer, flash attention , Nvidia TensorRT

### ISSUE THREAD

**Issue by bzr1** [Dao-AILab/flash-attention#1183]
Sorry, got a question. In the optimum doc i saw example using " better transformer" and "flash attention" at the same time. but in the better transformer it says, if use llama2 you don't need better transformer just the flash attention ( seems like). So should I use just the flash attention? and there is also a fastertransformer and  Nvidia TensorRT.  don't know which to use/combine

**Comment by tridao** [comment]
Idk how these libraries (better transformer, tensorrt) use which attention code exactly.
