### ISSUE TITLE
TiledMMA scales KNWarps times on the M dimension

### ISSUE THREAD

**Issue by phantaurus** [Dao-AILab/flash-attention#1204]
Hello! Could you help me understand why TiledMMA scales kNWarps times exclusively on the M dimension?
```
using TiledMma = TiledMMA<typename Base::MMA_Atom_Arch,
      // DEBUG: YIHE
      Layout<Shape<Int<kNWarps>, _1, _1>>,  // 4x1x1 or 8x1x1 thread group
      typename Base::ValLayoutMNK>;  // 1x2x1 or 1x2x2 value group for 16x16x16
                                     // MMA and LDSM
```

Could it be something like <_2, Int<kNWarps/2>, _1>?
Thanks!

**Comment by tridao** [comment]
`<_2, Int<kNWarps/2>, _1>` means some warps need to communicate w each other to do the online softmax.  You can see section 3.3 in the FlashAttenion-2 paper.

**Comment by phantaurus** [comment]
Thank you for your response! That makes a lot of sense. 
Flash attention uses __shfl_xor_sync for warp-level reduction, but it doesn't handle reductions across warps. 
Cross-warp reductions are expensive, as they require writing register data back to shared memory, which is less efficient.
