### ISSUE TITLE
Increase TensorCore Active % for Flash Attention Kernels

### ISSUE THREAD

**Issue by phantaurus** [Dao-AILab/flash-attention#1205]
Hello!

I am profiling flash attention using Nsys, and when enabling the '--gpu-metrics-device=all' flag for nsys, the 'Tensor Active %' metric reveals the activeness of the TensorCore pipeline. This metric can be leveraged to estimate the FLOPs by combining the Tensor Active % with the maximum TensorCore FLOPs and kernel execution time. After verifying the results, I found that the calculated FLOPs closely align with the theoretical FLOPs derived from the input dimensions of the attention mechanism.

i.e., Tensor Active % * GPU Max TensorCore FLOPS * kernel exec time ~= 4 * batch_size * seqlen^2 * num_heads * head_size / 1e12

However, I've observed that most flash attention kernels achieve around 50% TensorCore Active % on GPUs such as 3080, 4080, and Orin. Meanwhile, GEMM or convolution kernels generated by cuDNN/cuBLAS can reach ~90% TensorCore Active %.

Based on both Nsys profiling and my manual logic analysis, it’s clear that flash attention is compute-bound. Furthermore, the total number of FLOPs for flash attention should be similar to the combined FLOPs of the two matmuls involved in the attention mechanism. This suggests that increasing TensorCore Active % could directly speed up flash attention kernels.

I’m curious whether it’s possible to boost TensorCore Active %. From what I understand, a major limiting factor seems to be the volume of shared memory consumed per thread block, which limits the number of thread blocks running concurrently on each SM. For example, on 3080, if we set kBlockM = 128, kBlockN = 128, and kBlockK = 64, each thread block requires around 49KB of shared memory (3 * 128 * 64 * 2). Given that each SM has approximately 100KB of shared memory, only two blocks can run concurrently on one SM. Assuming each block has 4 warps, this results in only 8 warps running on an SM, despite the fact that up to 48 warps are allowed per SM.

This could underutilize the pipeline. For instance, if the pipeline is capable of issuing one new instruction every clock cycle (i.e., generating more FLOPs for different warps), now it may instead sit idle, waiting for previously issued instructions (from the same warp) to complete. As a result, the TensorCore is unable to reach the maximum FLOPs advertised by Nvidia.

However, reducing the block size increases occupancy but doesn’t seem to improve TensorCore Active %. I suspect this could be due to the increased tiling overhead... Or generating more data movements, or maybe each thread block now does not have enough computation to fill the pipeline...

Ideally, I'd like to reach a conclusion such as 'due to xx, the flash attention kernel utilizes about half of the available TensorCore computing power'. However, despite my observations, I haven't been able to identify a clear xx yet.

Could you provide some insights in what might be constraining TensorCore Active % for the flash attention kernel, and if it would be possible to increase the TensorCore Active %  for flash attention kernels?

Thank you so much!

**Comment by tridao** [comment]
Yes the main way to get faster is to keep the tensor cores busy. How to do that, is complicated.

The bottlenecks depend on which GPU, which version (FA2 or FA3), which headdim. Nsight compute might be able to show which pipelines are the bottlenecks (smem, gmem, etc.).
As an example, for FA3 forward pass on H100, hdim 64 BF16/FP8, one of the bottlenecks is the MUFU.EX2 instruction throughput. For hdim 256 BF16, we can reach very high tensor core utils (up to 80-85%).
For the backward pass, we're mostly constrained by smem size and number of registers, forcing us to use smaller blocks -> more smem read/write compared to mma instructions -> lower tensor core usage.

It's hard to make a blanket statement about what the bottlenecks are. All the components need to be working well: efficient register usage, vectorized smem read/write, coalesced gmem read/write, as large of a block size as possible without spilling registers, good warp/warpgroup scheduling, etc.

**Comment by tridao** [comment]
Btw for compute bound kernels one usually uses 4 or 8 warps (you can check cublas etc). One limitation is the large number of registers to hold the accumulator. It's rarely a good idea to use more than 8 or 12 warps for matmul since that decrease the number of registers.

**Comment by phantaurus** [comment]
Thank you so much for your responses! Your insights are incredibly valuable to me!

My take is that the following factors contribute to TensorCore Active %:

1. Within one warp, data movement cannot fully overlap with computation
- For gmem-to-smem data transfer, the copy must be completed before smem-to-register copy and MMA operations. This is because gmem-to-smem copy and smem-to-regster copy follow different tiling patterns, such that different threads work on different data indices. As a result, the gmem to smem copy must finish before the subsequent operations can begin.
- For smem-to-register data transfer, even though it can overlap with MMA operations, the throughput of MMA instructions might not fully compensate for the overhead of memory copies. Therefore, the smem-to-register copy may consume more clock cycles than the MMA operations.

2. Inter-warp: occupancy limitations
Ideally, the GPU should issue instructions for other warps while the current warp is waiting on memory transfers or GEMM output. However, limitations such as shared memory size and the register usage per warp restrict the number of warps that can run concurrently on a single SM. 
For example, 3080 can support up to 48 warps per SM, but due to shared memory and register constraints, fewer than 20 warps might actually be scheduled, reducing GPU occupancy to less than 50%. Without sufficient parallelism, warps cannot effectively hide each other's idle/waiting cycles, leading to relatively lower TensorCore Active % compared with full occupancy.

Please feel free to correct me or add anything I may have missed. Thank you so much!

**Comment by tridao** [comment]
I would not focus on occupancy. You can check that e.g. cublas will only use 4 or 8 or at most 12 warps, never more than that.
Occupancy is much less relevant to kernels that use tensor cores.

You can read cutlass's docs on what matters for efficient gemm: https://github.com/NVIDIA/cutlass/blob/main/media/docs/efficient_gemm.md

They also have many talks at GTC about this.

**Comment by phantaurus** [comment]
Thank you so much! I'm still fairly new to this area, and I'll definitely check these out!

**Comment by phantaurus** [comment]
I would like to add to our discussion that in flash attention, the max occupancy (i.e. the num. of warps per SM) should be a fixed value:

For each thread block, we consumes SmemSizePerThreadBlock = 2(kBlockM x kDimK + 2xkBlockN x kDimK)

So there can be maximally TotalSmemSIze / SmemSizePerThreadBlock thread blocks.

Within each thread block, since we can only scale the number of warps on M dimension, we have NWarpsPerThreadBlock = kBlockM / 16.

Therefore, MaxNWarpsPerSM = TotalSmemSize / (2(kBlockM x kDimK + 2xkBlockN x kDimK)) x (kBlockM / 16)

which gives us MaxNWarpsPerSM = TotalSmemSize / (32kDimK x (1 + 2 kBlockN/kBlockM))

This is relatively fixed value.
If we assume kBlockN == kBlockM,  then the number is TotalSmemSize / (96 x kDimK)
If TotalSmemSize =100K, kDimK = 64, then the max number of warps in each SM is 16.

Therefore, I think you are correct that we shouldn't focus on the occupancy.

**Comment by WanchaoYao** [comment]
> Therefore, MaxNWarpsPerSM = TotalSmemSize / (2(kBlockM x kDimK + 2xkBlockN x kDimK)) x (kBlockM / 16)
> 
> which gives us MaxNWarpsPerSM = TotalSmemSize / (32kDimK x (1 + 2 kBlockN/kBlockM))
@phantaurus I think you lost kBlockM, it should be:
MaxNWarpsPerSM = TotalSmemSize / (32kDimK x kBlockM x (1 + 2 kBlockN/kBlockM))
