### ISSUE TITLE
[QST]When params.deterministic is true, why backward prop still use atomicAdd？

### ISSUE THREAD

**Issue by zhang22222** [Dao-AILab/flash-attention#1245]
![image](https://github.com/user-attachments/assets/36f40364-43e2-4732-8e55-021ce815023b)
![image](https://github.com/user-attachments/assets/d6628daf-c050-4146-acff-e12e03ac2929)
![image](https://github.com/user-attachments/assets/a774a339-98fd-44a8-89ed-d8528bd7739d)

When params.deterministic is true，different block add acc_dq to different tdQgdQaccum，within one block，the for loop add acc_dq to tdQgdQaccum Sequentially. 
so why need **atomicAdd** here？I don't understand. Maybe we can remove **atomicAdd** here？

when params.deterministic is false and Seq_parallel is true，different block add acc_dq to the same tdQgdQaccum address，so there exist race condition problem，so it is necessary to use atomicAdd under this condition.  

@tridao

**Comment by tridao** [comment]
The alternative to atomic add is to read from gmem, do the add, then write to gmem. That's slower.
There's no reason not to do atomicadd here since it's still deterministic.

**Comment by zhang22222** [comment]
> The alternative to atomic add is to read from gmem, do the add, then write to gmem. That's slower. There's no reason not to do atomicadd here since it's still deterministic.

thanks for you quick reply!
do you means that if read tdQgdQaccum from gmem，do the add，then write to gmem，the result is still  correct and deterministic，but the performance will decrease？
Is this correct understanding?

**Comment by tridao** [comment]
Yes that's correct.
