### ISSUE TITLE
AttributeError: 'Qwen2FlashAttention2' object has no attribute '_flash_attention_forward'

### ISSUE THREAD

**Issue by zhangyuqi-1** [Dao-AILab/flash-attention#1246]
ms-swift version: 2.4.2
flash_attn version: 2.5.8
Python version: 3.10.14
PyTorch version: 2.4.0+cu121 (GPU)
Transformers version: 4.44.2
Datasets version: 2.20.0
Accelerate version: 0.32.1
PEFT version: 0.12.0
TRL version: 0.9.6
GPU type: NVIDIA GeForce RTX 4090
DeepSpeed version: 0.14.4
Bitsandbytes version: 0.43.3
vLLM version: 0.6.0

**Comment by tridao** [comment]
Not related to this repo. We don't have anything related to `Qwen2FlashAttention2` here
