### ISSUE TITLE
dropout in FA3 needs get fixed?

### ISSUE THREAD

**Issue by jundaf2** [Dao-AILab/flash-attention#1251]
it seems the current flash-attn-3 gives different dropout mask in its forward and backward kernel.

**Comment by tridao** [comment]
FA3 doesn't have dropout

**Comment by jundaf2** [comment]
i see, thanks. will FA3 officially support dropout?

**Comment by tridao** [comment]
Not any time soon unless someone volunteers to work on it.

**Comment by jundaf2** [comment]
i see, thanks!
