### ISSUE TITLE
how to remove softmax operations?

### ISSUE THREAD

**Issue by ziyuhuang123** [Dao-AILab/flash-attention#1255]
Hi! I am a learner of FA3 and I am trying to remove all softmax operations. I noticed flash-attention/hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp has many softmax, I commented softmax in it. But I find the result is all nan now. I am confused... Any comments?

Thanks!

**Comment by ziyuhuang123** [comment]
If I print out tOrP, the result will be mostly real value and only 128 nan values... very strange...

**Comment by tridao** [comment]
You probably want to change the masking as well. With softmax, we mask the scores with -infinity. Without softmax you probably want to mask with 0.

**Comment by ziyuhuang123** [comment]
> You probably want to change the masking as well. With softmax, we mask the scores with -infinity. Without softmax you probably want to mask with 0.

exactly! That solved my problem!
