### ISSUE TITLE
Can I print value within function? (like load function)

### ISSUE THREAD

**Issue by ziyuhuang123** [Dao-AILab/flash-attention#1257]
I am debugging, so I need to print something....
temp_can/flash-attention/hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp
load function, If I add printf(".....\n"); I will get error:
CUDA error (/home/zyhuang/temp_can/flash-attention/hopper/flash_fwd_launch_template.h:111): an illegal instruction was encountered

I added #include <stdio.h> in many files. Strange... I can print in outer function like compute_attn_ws

**Comment by ziyuhuang123** [comment]
Oh, I noticed that relates to:
```
cutlass::arch::warpgroup_reg_dealloc<Ktraits::kNWarps == 12 ? 24 : 32>();
```
If I changed it to 56, sometimes it can print out, but sometimes it print out and then stall forever...?

**Comment by ziyuhuang123** [comment]
OK. I find out we have to also limit consumer's register usage. It seems that if we use too much register, the kernel can start, but will stall forever.......Well, that introduce a new extra expense, if I want to print more, I will have to change producer-consumer's register number again and again....

**Comment by tridao** [comment]
Yup we mentioned that here
https://github.com/Dao-AILab/flash-attention/blob/be6c1b98c40785fa39d73954f5e84a7e1657d261/hopper/flash_bwd_kernel.h#L69

**Comment by ziyuhuang123** [comment]
Wow, very clever!
