### ISSUE TITLE
Intra-Warpgroup Overlapping GEMMs and Softmax in FA3

### ISSUE THREAD

**Issue by ziyuhuang123** [Dao-AILab/flash-attention#1265]
Looking at the diagram below, since it mentions intra-warpgroup, what exactly does WGMMA0 and WGMMA1 mean in this context? I thought a single warpgroup could only run one WGMMA at a time.

Also, there seems to be a conflict between the upper and lower parts of this diagram. The upper part suggests that WG1 completes its work independently, with the same color representing the same iteration (intermediate results being passed through registers). However, the lower part suggests that WG0 does part of the work and passes the intermediate result to WG1 (with the intermediate result being passed through shared memory, SMEM).

Could you clarify this apparent conflict and how the mechanism works in the FA3 pipeline?
![1c7ee89ade4c3687eb881e2e40758f4](https://github.com/user-attachments/assets/567a5954-ab80-44d5-815c-27c358abf3f9)

**Comment by ziyuhuang123** [comment]
Given the strategy shown in the upper diagram, where softmax and GEMM are already overlapped, why is the additional overlapping mechanism in the lower diagram still necessary? Compared to the upper diagram, the lower one introduces the disadvantage of passing values through shared memory (SMEM) rather than registers, without theoretically increasing the overlap.

**Comment by ziyuhuang123** [comment]
I've noticed that the published code uses convert_layout_acc_Aregs, which seems to indicate that intermediate results are being passed using registers. Given this, could you clarify if Policy 2 (from the lower diagram) is fully implemented in the code?

**Comment by ziyuhuang123** [comment]
Oh, I think I partially understand the question now. intra-warp is just like figure below. But where in the code demonstrate the inter-warp policy...

![image](https://github.com/user-attachments/assets/abc6caec-e736-4638-844a-dca32c7e4004)

**Comment by tridao** [comment]
The 2 WGs don't really interact (except for the warp scheduler sync), so there's no passing through smem. WG1 does its own gemm0, uses that output in registers to do softmax & gemm1. WG2 does the same thing with its own gemm0.

**Comment by ziyuhuang123** [comment]
yes! And warpgroup<1> means the waiting wg is 1, <0> means no waiting, so both is finished.

**Comment by tridao** [comment]
No, you can read this tutorial on what warpgroup_wait does
https://research.colfax-intl.com/cutlass-tutorial-wgmma-hopper/

**Comment by ziyuhuang123** [comment]
yes! <1> means only one wg is waiting(but not specify it must be wg1 or 0, just because we commit which first and then..). Thanks!
