### ISSUE TITLE
RuntimeError: Only support head size 64, 128, and 256 for now [flashattn_hopper_cuda]

### ISSUE THREAD

**Issue by NiuMa-1234** [Dao-AILab/flash-attention#1290]
Thank you for your wonderful work! I encountered an error with the latest flashattn3-hopper and the details  are below. Could you please help me?
attn_output = flash_attn_func(
 File "/usr/local/lib/python3.10/dist-packages/flash_attn_interface.py", line 369, in flash_attn_func
      return FlashAttnFunc.apply(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 573, in apply
      return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/flash_attn_interface.py", line 183, in forward
      out, q, k, v, out_padded, softmax_lse, S_dmask = _flash_attn_forward(
  File "/usr/local/lib/python3.10/dist-packages/flash_attn_interface.py", line 19, in _flash_attn_forward
      out, q, k, v, out_padded, softmax_lse, S_dmask = flashattn_hopper_cuda.fwd(
 RuntimeError: Only support head size 64, 128, and 256 for now

**Comment by NiuMa-1234** [comment]
Solved.Just rectify the head_size of my qkv to 64 or 128 (no 256 cuz the backward supports a max size of 128 only)

**Comment by uygnef** [comment]
Hi, I'm encountering the same issue. When training an 8B model on an H100, the head number is 16 and I can't use flashattn_hopper_cuda. Any solutions?

**Comment by NiuMa-1234** [comment]
Hi, the head number of mine is 16, too. the head_size mentioned above is the  head dimension, maybe you could check  this parameter

**Comment by uygnef** [comment]
thanks a lot!
