### ISSUE TITLE
Fail to initialize the TMA descriptor for head_dim of 192

### ISSUE THREAD

**Issue by NiuMa-1234** [Dao-AILab/flash-attention#1296]
Hi, I added some lines in hopper to support the head dim of 192, but it didn't work. Could you plz help me? And I wonder if this relates to the reason that you currently experiment on the head_dim of just 64 and 128 for bf16.

The forward process works  well, but the backward always ends up at the initialization of the first kernel.

The program errors at the line:
```
hopper/flash_bwd_launch_template.h:
......
    if (smem_size >= 48 * 1024) {
        CHECK_CUDA(cudaFuncSetAttribute(kernel, cudaFuncAttributeMaxDynamicSharedMemorySize, smem_size));
    }
```
The details of the  error are:
```
globalDim      (32,49152,16,1,1)
globalStrides  (4,128,6291456,100663296,0)
boxDim         (32,384,1,1,1)
elementStrides (1,1,1,1,1)
interleave     0
swizzle        3
l2Promotion    2
oobFill        0
Error: Failed to initialize the TMA descriptor 1
```
The information of kernel's needed smem_size is :
` smem_size = 215040, q = 49152, k = 24576, v = 24576, do = 49152, ds = 16384, dqacc = 49152`

I'm confused cuz the size of 215040  is smaller than the max maxSharedMemory (227Kb) of a kernel in Hopper. I've tried to lower down the size of kBlockM and kBlockN, the smem_size  decreased but the backward process still errors.

Btw, the smem_size is 198656 when the head_dim is 128.

**Comment by tridao** [comment]
You can try the `tdd` branch, which supports bwd for hdim up to 256. We'll merge it soon.

**Comment by NiuMa-1234** [comment]
Thank you very much!
