### ISSUE TITLE
Different nr. of KV and Q tokens

### ISSUE THREAD

**Issue by kilianhaefeli** [Dao-AILab/flash-attention#1298]
Does the variable length kernel support computing variable length attention when the sequences in Q are shorter than the sequences in KV? e.g. q consists of 10 tokens and KV consists of 20. If so how would this work, especially with `is_causal=True`?
Would token j in Q attend to all tokens 10+j in K? And then the first Q token attends to the first 11 K tokens?

**Comment by tridao** [comment]
Yes it's supported. The precise attention pattern is described in the function docstring.
https://github.com/Dao-AILab/flash-attention/blob/c1d146cbd5becd9e33634b1310c2d27a49c7e862/flash_attn/flash_attn_interface.py#L1358

**Comment by kilianhaefeli** [comment]
Thanks for the answer and the amazing work!
