### ISSUE TITLE
Error in line 21 O_i adjustment in Algorithm 1 in FlashAttention-3 Paper

### ISSUE THREAD

**Issue by hasanunlu** [Dao-AILab/flash-attention#1303]
@tridao, I just noticed minor thing in the FlashAttention3 paper. If we look at line 10 in Algorithm 1 in FlashAttention-2, O_i adjustment has diag(exp(m_{j-1} - m_i)). However same adjustment in FlashAttention-3 paper described as diag(exp(m_old - m_i))^(-1), instead of diag(exp(m_old - m_i)). There should be no reciprocal operation to adjust O_i in the for loop of 0<= j <= T_c. CUDA code is correct. It is just different in the paper.
<img width="1382" alt="flash_attn3" src="https://github.com/user-attachments/assets/2ea2744d-278c-4ce8-9f8e-c5e186611841">

**Comment by jayhshah** [comment]
Thanks for reporting this, it will be fixed in the upcoming revision of the paper.
