### ISSUE TITLE
Benchmark perf in cuda-12.6

### ISSUE THREAD

**Issue by JamesLim-sy** [Dao-AILab/flash-attention#1322]
hi, i have done FA3 benchmark in cuda-12.6 env with the given param setting in chart of https://tridao.me/blog/2024/flash3/, but i found that its peak tflop being around just 550 TFlops not 630, for head_dim=128, with casual mask. Is it induced by FA3 not being in good compatibility with cuda-12.6 ?

**Comment by tridao** [comment]
you can try cuda 12.3
