### ISSUE TITLE
breaking change for head size non divisble by 8

### ISSUE THREAD

**Issue by felix-red-panda** [Dao-AILab/flash-attention#1347]
I'm updating flash attention to the new version and I was surprised to learn that no head dimensions that are not multiples of 8 stopped working. Is it a deliberate choice, why was this changed?

(I know that I can pad it myself like it was previously 🙃 )

https://github.com/Dao-AILab/flash-attention/commit/53a4f341634fcbc96bb999a3c804c192ea14f2ea#diff-c86bcd35189d987950b790888d5b8fe454255d75263d0b211f0a1d69c152e29aL11

**Comment by tridao** [comment]
The padding is done in Python (instead of C++) now for compatibility w Torch compile.
If you use the Python interface then nothing has changed.
https://github.com/Dao-AILab/flash-attention/blob/7153673c1a3c7753c38e4c10ef2c98a02be5f778/flash_attn/flash_attn_interface.py#L807
