### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by yingtongxiong** [Dao-AILab/flash-attention#135]
hello, when I compiler flash attention, I occurs some bugs.
In file included from /mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/src/ln_fwd_1024.cu:1:
/mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/include/ln_fwd_kernels.cuh:9:10: **fatal error: ATen/cuda/detail/UnpackRaw.cuh: No such file or directory**
    9 | #include <ATen/cuda/detail/UnpackRaw.cuh>  // For at::cuda::philox::unpack
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/src/ln_fwd_1024.cu:1:
/mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/include/ln_fwd_kernels.cuh:9:10: **fatal error: ATen/cuda/detail/UnpackRaw.cuh: No such file or directory**
    9 | #include <ATen/cuda/detail/UnpackRaw.cuh>  // For at::cuda::philox::unpack
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/src/ln_fwd_1024.cu:1:
/mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/include/ln_fwd_kernels.cuh:9:10: **fatal error: ATen/cuda/detail/UnpackRaw.cuh: No such file or directory**
    9 | #include <ATen/cuda/detail/UnpackRaw.cuh>  // For at::cuda::philox::unpack
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[13/26] /mnt/petrelfs/share/cuda-11.6/bin/nvcc -ccbin /mnt/petrelfs/share/gcc/gcc-10.2.0/bin/gcc -DTORCH_EXTENSION_NAME=flash_attn_layernorm -DTORCH_API_INCLUDE_EXTENSION_H -I/mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/include -isystem /mnt/petrelfs/xiongyingtong/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/include -isystem /mnt/petrelfs/xiongyingtong/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /mnt/petrelfs/xiongyingtong/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/include/TH -isystem /mnt/petrelfs/xiongyingtong/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/include/THC -isystem /mnt/petrelfs/share/cuda-11.6/include -isystem /mnt/petrelfs/xiongyingtong/anaconda3/envs/pytorch1.7/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math -DOLD_GENERATOR_PATH -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 --threads 4 -std=c++14 -c /mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/src/ln_fwd_2048.cu -o ln_fwd_2048.cuda.o 
FAILED: ln_fwd_2048.cuda.o 
/mnt/petrelfs/share/cuda-11.6/bin/nvcc -ccbin /mnt/petrelfs/share/gcc/gcc-10.2.0/bin/gcc -DTORCH_EXTENSION_NAME=flash_attn_layernorm -DTORCH_API_INCLUDE_EXTENSION_H -I/mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/include -isystem /mnt/petrelfs/xiongyingtong/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/include -isystem /mnt/petrelfs/xiongyingtong/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /mnt/petrelfs/xiongyingtong/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/include/TH -isystem /mnt/petrelfs/xiongyingtong/anaconda3/envs/pytorch1.7/lib/python3.8/site-packages/torch/include/THC -isystem /mnt/petrelfs/share/cuda-11.6/include -isystem /mnt/petrelfs/xiongyingtong/anaconda3/envs/pytorch1.7/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math -DOLD_GENERATOR_PATH -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 --threads 4 -std=c++14 -c /mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/src/ln_fwd_2048.cu -o ln_fwd_2048.cuda.o 
In file included from /mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/src/ln_fwd_2048.cu:1:
/mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/include/ln_fwd_kernels.cuh:9:10: fatal error: ATen/cuda/detail/UnpackRaw.cuh: No such file or directory
    9 | #include <ATen/cuda/detail/UnpackRaw.cuh>  // For at::cuda::philox::unpack
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/src/ln_fwd_2048.cu:1:
/mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/include/ln_fwd_kernels.cuh:9:10: fatal error: ATen/cuda/detail/UnpackRaw.cuh: No such file or directory
    9 | #include <ATen/cuda/detail/UnpackRaw.cuh>  // For at::cuda::philox::unpack
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/src/ln_fwd_2048.cu:1:
/mnt/petrelfs/xiongyingtong/uniscale/uniscale/ops/csrc/flash_attn_layernorm/include/ln_fwd_kernels.cuh:9:10: fatal error: ATen/cuda/detail/UnpackRaw.cuh: No such file or directory
    9 | #include <ATen/cuda/detail/UnpackRaw.cuh>  // For at::cuda::philox::unpack
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

and cuda version is 11.6, gcc version is 10.2 and pytorch version is 1.7
how can we solve it?

**Comment by tridao** [comment]
Your pytorch version is too old, we support Pytorch >= 1.12.
