### ISSUE TITLE
Question About Initial sync Behavior Without Prior arrive in Warpgroup Scheduling

### ISSUE THREAD

**Issue by ziyuhuang123** [Dao-AILab/flash-attention#1371]
I have a question regarding the diagram below:

At the very beginning, the sync function is called directly, but there is no prior arrive. Wouldn't this cause the program to deadlock? (Assuming for argument's sake that the first sync does not result in a deadlock.)

In this case, isn’t it uncertain which warp group starts first? For example, it’s not necessarily Warpgroup 1 that begins. The startup sequence seems random, doesn’t it?

That said, it seems to work either way. Even if the roles of Warpgroup 1 and Warpgroup 2 are reversed, the ping-pong mechanism would still function as intended. Could someone clarify this behavior?
![9c9031a5b2af61d11c7c867060b37ce](https://github.com/user-attachments/assets/fb3a63fa-7b37-477d-9924-4aab23a1ce45)

**Comment by tridao** [comment]
The first arrive is in `mma_init`

**Comment by ziyuhuang123** [comment]
Wow, I get it. This is really very bueatiful!
