### ISSUE TITLE
seq_lens variable used in the attention kernel

### ISSUE THREAD

**Issue by chakpongchung** [Dao-AILab/flash-attention#1378]
trying to understand the seq_lens variable used in the attention kernel.

https://github.com/vllm-project/vllm/blob/main/tests/kernels/test_flash_attn.py#L75

why 
@pytest.mark.parametrize("kv_lens", [[1328, 18, 463], [1, 54, 293, 70]]) is used here? I expect them to sum to multiples of 1024 or the amount of the cache size to be used here as offsets given starting positions of the k-cache and v-cache

https://github.com/vllm-project/vllm/blob/main/tests/kernels/test_flash_attn.py#L131

**Comment by tridao** [comment]
You'll probably get better response asking on the vllm repo
