### ISSUE TITLE
FA-3 installation errors

### ISSUE THREAD

**Issue by asahni04** [Dao-AILab/flash-attention#1387]
@tridao 

when i try to install FA-3 as per the instructions
cd hopper
python setup.py install
To run the test:

export PYTHONPATH=$PWD
pytest -q -s test_flash_attn.py

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import flash_attn

File adfscszc/flash-attention/flash_attn/__init__.py:3
      1 __version__ = "2.7.2.post1"
----> 3 from flash_attn.flash_attn_interface import (
      4     flash_attn_func,
      5     flash_attn_kvpacked_func,
      6     flash_attn_qkvpacked_func,
      7     flash_attn_varlen_func,
      8     flash_attn_varlen_kvpacked_func,
      9     flash_attn_varlen_qkvpacked_func,
     10     flash_attn_with_kvcache,
     11 )

File /adfscszc/flash-attention/flash_attn/flash_attn_interface.py:15
     13     from .flash_attn_triton_amd import interface_fa as flash_attn_gpu
     14 else:
---> 15     import flash_attn_2_cuda as flash_attn_gpu
     17 # isort: on
     19 def maybe_contiguous(x):

ModuleNotFoundError: No module named 'flash_attn_2_cuda'

**Comment by lyzhongcrd** [comment]
Hey, I encountered the same error, how did you resolve this?
