### ISSUE TITLE
Why triton version of flash_attn doesn't support dropout?

### ISSUE THREAD

**Issue by flymark2010** [Dao-AILab/flash-attention#176]
Hi,  you mentioned that the triton version of flash_attn doesn't support dropout [here](https://github.com/HazyResearch/flash-attention/blob/96d10f654527cc82c81022e16f77a8d9564f7eba/flash_attn/flash_attn_triton.py#L34), could you please explain why?

Is that possible to be supported sooner or later?

**Comment by tridao** [comment]
The Triton version doesn't support dropout because I think it'd be hard to implement (efficiently). I don't have plan to implement that, but if you play with the Triton version and figure out something, let me know!

**Comment by flymark2010** [comment]
Thanks for you relay. 

I am using the Triton version because it supports attention bias. For now, it doesn't support attention bias, so I digged into the code and learnt the Triton basics, and found a [Low-Memory Dropout](https://triton-lang.org/main/getting-started/tutorials/04-low-memory-dropout.html#low-memory-dropout) tutorial using seeded dropout.   I think we may generate a random seed in [FlashAttnFunc::forward](https://github.com/HazyResearch/flash-attention/blob/96d10f654527cc82c81022e16f77a8d9564f7eba/flash_attn/flash_attn_triton.py#L800)，and then using the seed in the fwd & bwd kernel to generate dropout mask. I'm wondering if it's a feasible and efficient way?

**Comment by tridao** [comment]
Yeah that could work. You can try it out.
I haven't tried it in Triton but for the CUDA implementation generating the dropout mask requires a lot of registers and can make things a lot slower (because of register spilling) if one is not careful.
You can try to add the step to generate the dropout mask in the Triton forward pass and see how that affects performance.

**Comment by flymark2010** [comment]
I had tried adding the following snip [here](https://github.com/HazyResearch/flash-attention/blob/3da42d24b1678b3ed930ab86e801b4ee851af1d2/flash_attn/flash_attn_triton.py#L175):

```
# dropout
if USE_DROPOUT:
    num_block_m = tl.cdiv(seqlen_q, BLOCK_M)
    block_idx = off_hb * num_block_m + start_m # column major
    rnd_index = tl.reshape(tl.arange(0, BLOCK_M * BLOCK_N), (BLOCK_M, BLOCK_N))
    rnd_index = block_idx * BLOCK_M * BLOCK_N + rnd_index
    random = tl.rand(dropout_seed, rnd_index)
    x_keep = random > dropout_p
    p = tl.where(x_keep, p / (1. - dropout_p), 0.0)
```

but got error:
```
Traceback (most recent call last):
  File "<string>", line 21, in _fwd_kernel
KeyError: ('2-.-0-.-0-0afa0fd697019085a7525fcab2503fcf-2b0c5161c53c71b37ae20a9996ee4bb8-c1f92808b4e4644c1732e8338187ac87-42648570729a4835b21c1c18cebedbfe-12f7ac1ca211e037f62a7c0c323d9990-5c5e32ff210f3b7f56c98ca29917c25e-06f0df2d61979d629033f4a22eff5198-0dd03b0bd512a184b3512b278d9dfa59-d35ab04ae841e2714a253c523530b071', (torch.float16, torch.float16, torch.float16, None, torch.float16, torch.float32, torch.float32, 'fp32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'fp32', 'i32', 'i32', 'i32'), ('none', True, True, 64, True, True, True, 128, 128), (True, True, True, (False,), True, True, True, (False,), (True, False), (True, False), (True, False), (True, False), (True, False), (True, False), (True, False), (True, False), (True, False), (True, False), (True, False), (True, False), (True, False), (True, False), (True, False), (False, False), (True, False), (True, False), (True, False), (True, False), (False,), (False, False), (True, False), (True, False)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tmp.py", line 27, in <module>
    output_0 = flash_attn_func(q, k, v, bias, causal, attention_dropout=0.1)
  File "/workspace/project/flash-attention/flash_attn/flash_attn_triton.py", line 852, in flash_attn_func
    return FlashAttnFunc.apply(q, k, v, bias, causal, softmax_scale, attention_dropout)
  File "/workspace/project/flash-attention/flash_attn/flash_attn_triton.py", line 826, in forward
    o, lse, ctx.softmax_scale = _flash_attn_forward(
  File "/workspace/project/flash-attention/flash_attn/flash_attn_triton.py", line 635, in _flash_attn_forward
    _fwd_kernel[grid](
  File "/usr/local/lib/python3.8/dist-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/triton/runtime/autotuner.py", line 200, in run
    return self.fn.run(*args, **kwargs)
  File "<string>", line 41, in _fwd_kernel
  File "/usr/local/lib/python3.8/dist-packages/triton/compiler.py", line 1256, in compile
    asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
  File "/usr/local/lib/python3.8/dist-packages/triton/compiler.py", line 901, in _compile
    name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
IndexError: map::at
```
I am struggling with this as not familiar with cuda kernel programming. Any tips or suggestions would be greatly appreciated.

**Comment by tridao** [comment]
I'm not an expert in Triton, you might have better luck asking on the Triton github.
