### ISSUE TITLE
When will there be an ALiBi? 

### ISSUE THREAD

**Issue by ScottishFold007** [Dao-AILab/flash-attention#179]
When will there be an ALiBi? This is valuable?When will there be ALiBi? This is valuable, especially when it comes to long text, and can effectively reduce the consumption of video memory.

**Comment by tridao** [comment]
The triton [implementation](https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/flash_attn_triton.py) supports attention bias, so it should work with ALiBi.

**Comment by vchiley** [comment]
The [MosaicML examples LLM model uses Alibi with the triton implementation](https://github.com/mosaicml/examples/blob/main/examples/llm/src/models/mosaic_gpt/configuration_mosaic_gpt.py#L151)

**Comment by vmarkovtsev** [comment]
:facepalm: my bad, sorry. Do you mind if I prepare a PR with a similar `linear_attention_bias` scheme in `fmha_*_launch_template.h`?

**Comment by tridao** [comment]
> 🤦 my bad, sorry. Do you mind if I prepare a PR with a similar `linear_attention_bias` scheme in `fmha_*_launch_template.h`?

I'm not sure how easy it is to do. For FlashAttention the product QK^T is stored in registers in a "permuted layout" to match the accumulator of the matrix multiply (mma) instruction. E.g. thread 0 holds elements at column 0, 1, 8, 9, etc, thread 1 holds elements at column 2, 3, 10, 11, etc. The layout is described in Nvidia's docs [here](https://docs.nvidia.com/cuda/parallel-thread-execution/#matrix-fragments-for-mma-m16n8k16-with-floating-point-type). So when we read in the linear bias we'll need to take this "permuted layout" into account (it's not a straightforward thread 0 uses bias[0], thread 1 uses bias[1], etc.)

If you figure it out then ofc a PR would be very welcome.

**Comment by tridao** [comment]
Alibi is supported in FlashAttention as of v2.4.0
