### ISSUE TITLE
Support for NVIDIA GeForce RTX 3090 with Compute Capability 8.6

### ISSUE THREAD

**Issue by ericzhou571** [Dao-AILab/flash-attention#190]
Issue description:

Hello,

I am using the flash_attn package on a system with two NVIDIA GeForce RTX 3090 GPUs, both of which have a Compute Capability of 8.6. When trying to run the package, I encountered the following RuntimeError:

vbnet
Copy code
RuntimeError: Expected is_sm80 || is_sm90 to be true, but got false.
I have already tried setting the TORCH_CUDA_ARCH_LIST environment variable to "8.6" and recompiling the package, but the issue persists. I have also attempted to modify the source code to include support for Compute Capability 8.6 but have been unsuccessful in resolving the error.

Could you please let me know if the flash_attn package supports NVIDIA GeForce RTX 3090 with Compute Capability 8.6? If not, could you provide guidance on how to add support for this specific GPU?

Your assistance would be greatly appreciated. Thank you in advance!

more information about gpu:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| 44%   33C    P2   159W / 350W |    630MiB / 24268MiB |     39%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by tridao** [comment]
As mentioned in the README, "Head dim > 64 backward requires A100 or H100". The forward for head dim <= 128, and backward for head dim <= 64 works on other GPUs.

**Comment by ericzhou571** [comment]
> As mentioned in the README, "Head dim > 64 backward requires A100 or H100". The forward for head dim <= 128, and backward for head dim <= 64 works on other GPUs.

Thanks a lot for quick rely!

So that means current it is impossible to train a llama 7B or 13B using RTX3090 with Compute Capability 8.6?

**Comment by tridao** [comment]
That's correct.

**Comment by samarthsarin** [comment]
Is there a possibility of adding support for that?

**Comment by codender** [comment]
@tridao Hi,this is my input for `flash_attn_unpadded_func`
query shape: torch.Size([241, 32, 128])
key shape: torch.Size([241, 32, 128])
value shape: torch.Size([241, 32, 128])

The head dim is 32 ,but still `RuntimeError: FlashAttention backward for head dim > 64 requires A100 or H100 GPUs as the implementation needs a large amount of shared memory.`

**Comment by tridao** [comment]
The head dimension here is 128.

**Comment by codender** [comment]
Oh, i misunderstand, thx

**Comment by ehartford** [comment]
> We currently don't have the bandwidth for that.

shouldn't the issue be left open then, and maybe someone will step up to contribute a PR?

**Comment by samarthsarin** [comment]
Majority of the audience of this library is using lower end GPUs it would be great if we can add support for them as it will help out alot of people.

Thank you

**Comment by tridao** [comment]
We welcome contributions from the community :D

**Comment by ehartford** [comment]
> > As mentioned in the README, "Head dim > 64 backward requires A100 or H100". The forward for head dim <= 128, and backward for head dim <= 64 works on other GPUs.
> 
> Thanks a lot for quick rely!
> 
> So that means current it is impossible to train a llama 7B or 13B using RTX3090 with Compute Capability 8.6?

@ericzhou571 not impossible - just not currently implemented.

If you could please reactivate this issue, I think it's a good place to track it.

**Comment by ftgreat** [comment]
Does flash_attn(used flash_attn_unpadded_qkvpacked_func) support A800 when head dim = 128? @tridao 
Thanks.

**Comment by tridao** [comment]
> Does flash_attn(used flash_attn_unpadded_qkvpacked_func) support A800 when head dim = 128? @tridao Thanks.

If A800 is considered SM80 (similar to A100) then it would work. I suspect A800 is SM80, but I couldn't find any official documentation. 
If you have Pytorch installed, `torch.cuda.get_device_capability` should give you the SM number (for A100 that would return `(8, 0)`).

**Comment by FarisHijazi** [comment]
@tridao it's understandable that you may not have the bandwidth to implement this yourself, but could you at least share your initial thoughts for where the community should start to get this supported, I'm planning to work on this but I'd appreciate it if you saved us time be explaining what needs to be done

**Comment by tridao** [comment]
The main constraint is the size of shared memory.
For head dim > 64, we round it up to 128 internally.
We process a block of 16 rows and 128 columns at a time, with 8 warps (256 threads). Because we use tensor cores, which can do matmul of size 16 x 16 per warp, 16 x 128 is the smallest block size here.

As mentioned in the [code](https://github.com/HazyResearch/flash-attention/blob/eff9fe6b8076df59d64d7a3f464696738a3c7c24/csrc/flash_attn/src/fmha_dgrad_kernel_1xN_loop.h#L205), here's the shared memory layout.
```
    //  dO | Q | K | V | dQ | S | dP | dP_sum
```
Let's figure out the sizes of each (I'm doing this from memory, so some numbers below might not be exactly right, but they're in the ballpark):
- dO has size 16 x 128, with 2 buffers, each element is 2 bytes (fp16/bf16) -> 8KB.
- Q: same size as dO -> 8KB.
- K has size 128 x 128, each element is 2 bytes -> 32KB.
- V: same size as K -> 32KB.
- dQ: used to sum the dQ values held by 8 different warps. It has size 16 x 128 x 8 (warps), each element is 4 bytes (we store in float to reduce numerical error) -> 64KB.
- S has size 16 x 128, each element is 2 bytes -> 4KB.
- dP: same size as S -> 4KB.
- dP_sum: I think I got rid of this already.

Total is **152KB**. On A100 you can have shared memory of size up to 163KB, so this is fine (H100 also works). On sm86 and sm89, shared memory is limited to 99KB.

There are a couple things one can do to make things fit in 99KB of shared memory:
- Keep V in registers. This would save 32KB, but increase register usage and might lead to register spilling and potentially slowing things down.
- Reduce the size of the shared memory used to sum up dQ. We know that we need to sum up 16 x 128 values from each of the 8 warps. We can sum them up iteratively. For example, for each wrap, write 16 x 16 values from registers to shared memory, sync all warps, sum these 16 x 16 values, then repeat until we finish summing all 16 x 128 values. This way dQ only needs to be of size 16 x 16 x 8 warps  x 4 bytes = 8KB and things would fit.

**Comment by ftgreat** [comment]
> A100

If we switch from A100(40G) to A800(80G), should we need reinstall and update flash-atten? @tridao 
thanks.

**Comment by tridao** [comment]
> If we switch from A100(40G) to A800(80G), should we need reinstall and update flash-atten? @tridao
> thanks.

If it's on the same machine you shouldn't need to, but I've never been in that situation.

**Comment by codender** [comment]
> Does flash_attn(used flash_attn_unpadded_qkvpacked_func) support A800 when head dim = 128? @tridao Thanks.

works fine in A800

**Comment by tridao** [comment]
> I am curious though, since L2 cache is tens or hundreds of MB and is also very fast, can we just leverage L2 cache?

Yeah I think there are ways to leverage L2 cache (e.g. by repeatedly loading from L2 to L1 instead of keeping things in L1). It just takes some time and effort to experiment with.

**Comment by tridao** [comment]
L2 cache isn't programmable I think. It's just if you load from global memory (HBM) to L1 cache then it goes through L2 cache. So if you load the same thing again to L1, it'll fetch from L2 cache instead of global memory (HBM).

**Comment by stonyhu** [comment]
> 

Hope this issue could be addressed in future, it would be great to help out the lower-end GPU users :)

**Comment by tridao** [comment]
I don't have the bandwidth to work on it, but we welcome community's contribution.

**Comment by 152334H** [comment]
would a small bounty (say $1k) incentivize anyone to work on this?

**Comment by lucasjinreal** [comment]
Any updates? please add support for v100, xformers seems already supported

**Comment by tridao** [comment]
> Any updates? please add support for v100, xformers seems already supported

Feel free to use whatever works for your system.

**Comment by 152334H** [comment]
ok looks like this is no longer needed with flash attn 2 lmao

**Comment by vgoklani** [comment]
@152334H probably need to test it first.

**Comment by lucasjinreal** [comment]
@152334H  It desn't fix, just no warnings, v100 still not support.

**Comment by 152334H** [comment]
this is an issue for 3090s, not v100s, I don't know what you are pinging me for

the README is very clear on what is currently supported:
> Ampere, Ada, or Hopper GPUs (e.g., A100, RTX 3090, RTX 4090, H100). Support for Turing GPUs (T4, RTX 2080) is coming soon, please use FlashAttention 1.x for Turing GPUs for now.

**Comment by tridao** [comment]
Ampere (e.g. RTX 3090) and Ada (e.g. RTX 4090) should all support headdim <= 256 for the forward pass and headdim <= 192 for the backward pass, as of version 2.0.0.
