### ISSUE TITLE
ALiBi Support on flash-attetion

### ISSUE THREAD

**Issue by 2003pro** [Dao-AILab/flash-attention#214]
ALiBi can support long inference context length. Implement ALiBi with flash attention will be very helpful.

**Comment by tridao** [comment]
I agree. We welcome community's contribution.

**Comment by research4pan** [comment]
I am wondering if there are any plans of supporting ALiBi with flash attention in a near future?

**Comment by PiotrNawrot** [comment]
Bringing this up, I saw that the roadmap has changed. Have you tested the Triton implementation with ALIBI?

**Comment by tridao** [comment]
As mentioned in the README, we also have an experimental implementation in Triton that support attention bias (e.g. ALiBi): https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/flash_attn_triton.py

Feel free to play with it.

**Comment by Lhemamou** [comment]
Hey @tridao  Thanks you for all the work ! I am able to do a fwd pass with alibi. Is it normal than I can't do a backward pass ?

Thanks,

**Comment by tridao** [comment]
Backward pass with the Triton implementation should work (for 1D bias). What error do you see?

**Comment by Lhemamou** [comment]
I get this specific error : 

```
/usr/local/lib/python3.10/dist-packages/torch/_tensor.py:488: in backward
    torch.autograd.backward(
/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py:197: in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py:267: in apply
    return user_fn(self, *args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

ctx = <torch.autograd.function.FlashAttnFuncBackward object at 0x7fcbfffaca90>
do = tensor([[[[-5.9605e-08, -0.0000e+00, -5.9605e-08,  ..., -5.9605e-08,
            0.0000e+00, -0.0000e+00],
          [...   [-0.0000e+00, -0.0000e+00,  0.0000e+00,  ...,  5.9605e-08,
            0.0000e+00,  0.0000e+00]]]], device='cuda:0')

    @staticmethod
    def backward(ctx, do):
        q, k, v, o, lse, bias = ctx.saved_tensors
>       assert not ctx.needs_input_grad[3], 'FlashAttention does not support bias gradient yet'
E       IndexError: tuple index out of range

src/flash_attn_triton.py:820: IndexError
```

Maybe I am messing something with the architecture. I have disabled all biais in layer as I didn't understand well what bias gradient mean. The error is still there.

The test I am doing :

```
def test_fwd_and_bwd():
    model = get_transformer_flash_attention(config)
    model.to(0)
    BATCH=1
    SEQ=500
    VOCAB=model.config.vocab_size
    x = (torch.rand((BATCH, SEQ)) * VOCAB).abs().to(torch.int).to('cuda:0')
    y=model(x)
    loss=y.mean()
    loss.backward()
    assert loss is not None
```

If you have any clue I can investigate more during the day.

Final idea is just to reproduce T5.

Thanks Tridao !

**Comment by tridao** [comment]
Yeah gradient of the bias isn't supported, so T5 won't work. For 1D bias such as key padding mask and Alibi you shouldn't need gradient. 
Feel free to play with the implementation.

**Comment by Lhemamou** [comment]
All good, understood 👍

**Comment by tridao** [comment]
Alibi is supported in FlashAttention as of v2.4.0
