### ISSUE TITLE
rebuild and compile errors

### ISSUE THREAD

**Issue by brewswang** [Dao-AILab/flash-attention#271]
After I modify cpp file,I need rebuild project,but got many errors,
g++: error: /home/chat_glm6b/soft/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/fmha_api.o: No such file or directory
g++: error: /home/chat_glm6b/soft/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/src/fmha_block_dgrad_fp16_kernel_loop.sm80.o: No such file or directory
g++: error: /home/chat_glm6b/soft/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/src/fmha_block_fprop_fp16_kernel.sm80.o: No such file or directory
g++: error: /home/chat_glm6b/soft/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/src/fmha_bwd_hdim128.o: No such file or directory
g++: error: /home/chat_glm6b/soft/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/src/fmha_bwd_hdim32.o: No such file or directory
g++: error: /home/chat_glm6b/soft/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/src/fmha_bwd_hdim64.o: No such file or directory
g++: error: /home/chat_glm6b/soft/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/src/fmha_fwd_hdim128.o: No such file or directory
g++: error: /home/chat_glm6b/soft/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/src/fmha_fwd_hdim32.o: No such file or directory
g++: error: /home/chat_glm6b/soft/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/src/fmha_fwd_hdim64.o: No such file or directory
error: command '/opt/rh/devtoolset-9/root/usr/bin/g++' failed with exit code 1
How to solve its?

**Comment by tridao** [comment]
Idk what's wrong. You can try removing the build folder before rebuilding (`rm -rf build && python setup.py install`).

**Comment by brewswang** [comment]
I have already done this, but it doesn't work。

**Comment by tridao** [comment]
Then idk what's wrong. We recommend the [Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) container from Nvidia, which has all the required tools to install FlashAttention.

**Comment by brewswang** [comment]
I would like to adapt to the SM70 V100 GPU card. I'm not sure how your official progress is. Do you have any suggestions?

**Comment by tridao** [comment]
I'm not working on V100. I wrote some suggestions on the difference between V100 and A100 [here](https://github.com/HazyResearch/flash-attention/issues/148#issuecomment-1574090582) (mma instruction and shared memory load/store).

**Comment by brewswang** [comment]
Thanks,handsome boy!

**Comment by mru4913** [comment]
@brewswang 
how do you fix this problem ?
