### ISSUE TITLE
Support for sequence 32k

### ISSUE THREAD

**Issue by whychristy** [Dao-AILab/flash-attention#275]
Hi there!
I am trying to work with the FlashMHA example written in the readme (How to use FlashAttention section). 

However, for the case with batch = 1, seqlen = 32768, embed_dim = 12288, num_heads = 96, when viewing the kernel summary, fmha_fwd_loop_kernel doesn't exist. (I have tested with seqlen of 4k, 8k,16k and fmha_fwd_loop_kernel does exist)

The following are the exisiting kernels in this 32k case:
![image](https://github.com/HazyResearch/flash-attention/assets/59963655/6e49b1a5-c059-44c6-830d-3565f3fc02b7)

How can I solve it? Thanks.

**Comment by tridao** [comment]
I'm not sure what you mean by "it doesn't exist". Does it run at 32k seqlen? Does it return some output or does it error out?

**Comment by whychristy** [comment]
I am trying to look into the GPU Kernel summary through nsys. While testing with other sequences, fmha_fwd_loop_kernel would be in one of the kernels as below:
![image](https://github.com/HazyResearch/flash-attention/assets/59963655/ddf80432-dd37-453a-ab0f-782bb57c6010)
However, for the case of 32k seqlen, this function seems not in used?  But I assume this function should be compulsory during the computation?

**Comment by whychristy** [comment]
> I'm not sure what you mean by "it doesn't exist". Does it run at 32k seqlen? Does it return some output or does it error out?

I am trying to look into the GPU Kernel summary through nsys. While testing with other sequences, e.g. 4K, fmha_fwd_loop_kernel would be in one of the kernels as below:
![image](https://github.com/HazyResearch/flash-attention/assets/59963655/e3a37c62-2078-43e1-a1d4-d7353be15aab)

However, for the case of 32k seqlen, this function seems not in used ( as it is not seen in the kernel summary)? But I assume this function should be compulsory during the computation?

There isn't any error out and I checked the output tensor size being ([1, 32768, 12288]).

Thanks.

**Comment by tridao** [comment]
I'm not sure why it wouldn't show up on nsys. Maybe it errors out, but you said it runs fine.
