### ISSUE TITLE
Can it support the A40?

### ISSUE THREAD

**Issue by iMountTai** [Dao-AILab/flash-attention#276]
Head dimensions that are multiples of 8, up to 128 (e.g., 8, 16, 24, ..., 128). Head dim > 64 backward requires A100 or H100.Can it support the A40?

**Comment by tridao** [comment]
A40 is [sm_86](https://en.wikipedia.org/wiki/CUDA). It'll work for the forward pass head dim up to 128 and backward pass head dim up to 64 as mentioned. It won't work for backward pass with head dim > 64.

**Comment by iMountTai** [comment]
So will the A40 be supported later?

**Comment by tridao** [comment]
I can't say, it depends on my bandwidth.

**Comment by tridao** [comment]
As of v2, we support all head dimensions up to 256. Head dim > 192 backward requires A100/A800 or H100/H800.
