### ISSUE TITLE
Support head_size 256? which is bigger than 128.

### ISSUE THREAD

**Issue by nicknign** [Dao-AILab/flash-attention#277]
Very great work! I want to apply flash-attention in Codegen recently, which has head_size of 256. Is it possible to support head_size 256 in the future?

**Comment by tridao** [comment]
That's not currently supported. There's a chance it'll be implemented in the future, but it depends on my bandwidth.

**Comment by tridao** [comment]
As of v2 we support all head dimensions up to 256. Head dim > 192 backward requires A100/A800 or H100/H800.
