### ISSUE TITLE
Dose flash-attn support H800?

### ISSUE THREAD

**Issue by yingtongxiong** [Dao-AILab/flash-attention#290]
I found some performance degradation in H800. So I want to know whether the flash-attn supports H800? Our cuda version is 11.7

**Comment by tridao** [comment]
It does support H800, in the sense that it should run and give correct results. I don't have access to H800 (or H100) to test. Can you say more what "performance degradation" is in this case?

**Comment by yingtongxiong** [comment]
Sorry, the "performance degradation" is caused by our. And, I have another problem. Dose flash-attn supports 3090? Are there any limitations in model config when I want to use flash-attention in 3090. I have met the "out of memory" problem when I set "head dim" to be 32 in 3090.

**Comment by tridao** [comment]
As mentioned in the README, 3090 is supported. Backward for head dim > 64 requires A100 or H100), so forward for head dim <= 128 and backward for head dim <= 64 will work.

**Comment by yingtongxiong** [comment]
Okay，thank you very much
