### ISSUE TITLE
Unable to successfully install flash_attn package

### ISSUE THREAD

**Issue by Byron1201** [Dao-AILab/flash-attention#297]
<img width="1123" alt="1688543856898" src="https://github.com/HazyResearch/flash-attention/assets/70043407/c5b14059-f47d-4ac8-b703-eee915e3e9ce">

 I tried installing both pip and source, but they couldn't work. Has anyone encountered this situation before?

**Comment by tridao** [comment]
Probably issue with CUDA version / compiler version. We recommend the [Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) container from Nvidia, which has all the required tools to install FlashAttention.
