### ISSUE TITLE
Dataset for FlashSelfAttention and SelfAttention

### ISSUE THREAD

**Issue by yingtongxiong** [Dao-AILab/flash-attention#305]
Hello, I have some questions about using selfattenion with packed dataset. I found that when I fed the packed dataset into SelfAttention, I met some bugs. I want to know the "total" in qkv which is the first dimension is equal to the "B" multiply "S" in SelfAttention. The qkv shape in FlashSelfAttention is (total, 3, num_head, head_dim), and the qkv shape in SelfAttention is (B, S, 3, num_head, head_dim). I consider that the total = B * S. So when I want to use SelfAttention, can I reshape the qkv? Can anyone explain it?

**Comment by tridao** [comment]
You can look at how FlashSelfAttention is implement [here](https://github.com/HazyResearch/flash-attention/blob/72ad03eaa661f6bf3a14c855316c27fbab4f8f4c/flash_attn/modules/mha.py#L39). 
If all the sequences in the same batch have the same length then you can just reshape to combine the (batch, seqlen) dimensions to get the total.

Idk what packed dataset mean.

**Comment by yingtongxiong** [comment]
Thank you for so fast reply. What if the sequences in the same batch have different length, what should I do to convert to SelfAttention?

**Comment by tridao** [comment]
You can remove all the padding tokens and get indices (`cu_seqlens`) to pass to FlashSelfAttention. You can see how we do that in our BERT [implementation](https://github.com/HazyResearch/flash-attention/blob/72ad03eaa661f6bf3a14c855316c27fbab4f8f4c/flash_attn/models/bert.py#L138). 

There's some good diagram about what "unpadding" does from the FasterTransformer [repo](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/bert_guide.md) (Fig 2).

**Comment by yingtongxiong** [comment]
Thank you. In my understanding, I want to use SelfAttention with packed dataset. I think the diversion should be in [here](https://github.com/HazyResearch/flash-attention/blob/72ad03eaa661f6bf3a14c855316c27fbab4f8f4c/flash_attn/models/bert.py#L129C7-L129C7), I haven't seen any transformations in hidden_states. Can you tell me more details?

**Comment by tridao** [comment]
You can read the BERT implementation in details. It works (we test it).

**Comment by yingtongxiong** [comment]
Okay, Thank you very much.
