### ISSUE TITLE
why remove the `transformer.layers.{l}.attention.inner_attention.rope.freqs`

### ISSUE THREAD

**Issue by xueyongfu11** [Dao-AILab/flash-attention#316]
the code is here:
https://github.com/HazyResearch/flash-attention/blob/6d48e14a6c2f551db96f0badc658a6279a929df3/flash_attn/models/llama.py#L71

I cannot understand why remove rotary freqs? 
if remove, the inference results is right?

**Comment by tridao** [comment]
The frequencies are computed instead of loaded from checkpoint.
We do test that the inference results are correct (matching Hugginface's implementation).
