### ISSUE TITLE
System crashing when installing 2.0.0.post1 

### ISSUE THREAD

**Issue by nbroad1881** [Dao-AILab/flash-attention#317]
GPU: 4090
NGC container 23.04
OS: ubuntu 22.04

I upgraded ninja, packaging.

On running `pip install flash-attn --no-build-isolation`, my system freezes. After 5 minutes of waiting, it reboots.

Any suggestions? I'm really looking forward to trying out flash attention 2 :)

**Comment by FrancescoSaverioZuppichini** [comment]
same error, then I fix it by doing this

Dockerfile

```yaml
FROM nvcr.io/nvidia/pytorch:23.06-py3

RUN pip install -U ninja packaging
RUN pip install flash-attn --no-build-isolation

CMD [ "/bin/bash" ]
```


```docker run --rm -it --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
 -v $PWD:/workspace  flash-attention-2 /bin/bash```

**Comment by FrancescoSaverioZuppichini** [comment]
actuall the pip package is for version 1 and I have 64GB of ram 16 cores but I can't build it

**Comment by perone** [comment]
It seems that it is indeed eating a lot of memory during compilation, it is not respecting the jobs specification from `MAKEFLAGS` neither `NINJAOPTS`, which is weird, will take a look w/ more time in the following days.

**Comment by zten** [comment]
I ran into this too just now. I found https://github.com/ttumiel/pytorch/commit/16c57da03e8e3c130aa786a0948b4ccba1235116 added an environment variable, MAX_JOBS, that has reduced the pressure on my system.

Try it out:
```
MAX_JOBS=4 pip install flash-attn --no-build-isolation
```

**Comment by tridao** [comment]
> I ran into this too just now. I found [ttumiel/pytorch@16c57da](https://github.com/ttumiel/pytorch/commit/16c57da03e8e3c130aa786a0948b4ccba1235116) added an environment variable, MAX_JOBS, that has reduced the pressure on my system.
> 
> Try it out:
> 
> ```
> MAX_JOBS=4 pip install flash-attn --no-build-isolation
> ```

This is wonderful, I was just looking for this (I remember there was some env variable :D).
I'll add it to the README soon.
