### ISSUE TITLE
Will there be a triton implementation of Flash Attention 2?

### ISSUE THREAD

**Issue by arnavdantuluri** [Dao-AILab/flash-attention#319]
Hey Tri, just wanted to congratulate you and thank you for this awesome work, I am just wondering whether you will be releasing a triton implementation of Flash Attention 2 or if it is even the works? Again thank you so much for your amazing contributions to the Open Source community

**Comment by FrancescoSaverioZuppichini** [comment]
I think somebody at OpenAI made - need to find the LI post

**Comment by arnavdantuluri** [comment]
would be awesome if you could link me!

**Comment by vadimkantorov** [comment]
Yes, it's in https://github.com/openai/triton/commit/9e3e10c5edb4a062cf547ae73e6ebfb19aad7bdf, but I haven't seen a benchmark :)

**Comment by tridao** [comment]
I've been talking with Phil Tillet, he already starts implementing some of the tweaks mentioned in FlashAttention-2 (and some other tweaks were already in Triton). At least for the forward pass I hope the Triton version will soon be on par in terms of speed.

**Comment by chris-ha458** [comment]
https://github.com/openai/triton/commit/9e3e10c5edb4a062cf547ae73e6ebfb19aad7bdf

It is available in triton (this commit was merged)

**Comment by arnavdantuluri** [comment]
awesome! thank you everyone
