### ISSUE TITLE
Deterministic execution

### ISSUE THREAD

**Issue by artnitolog** [Dao-AILab/flash-attention#321]
Hello! Previously deterministic execution [could be enabled](https://github.com/Dao-AILab/flash-attention/commit/b6aa059bbfee365db7f991db88af99d3d0bf82da#diff-bebc59abf237ecff60cb37613b84719b54350f0c3f1cf1a77f89e6245a31193d) by setting `num_splits=1`. Is it possible to ensure deterministic backward in Flash Attention 2 (maybe with some slowdown)?

**Comment by tridao** [comment]
Yes, there's a code path (not enabled right now) that does it but I'll need to test that more, since sometimes it requires more shared memory that some GPUs don't have.

**Comment by ericheatspersimmons** [comment]
+1 to the feature request!

**Comment by tridao** [comment]
There's an option for deterministic bwd in v2.4.1.
