### ISSUE TITLE
Speedup between Flash-Attn v1 and v2 to expect for LLaMA

### ISSUE THREAD

**Issue by haotian-liu** [Dao-AILab/flash-attention#322]
Hi, thank you for the great work!  Can you please share the speed up we should expect for larger models like LLaMA-13B or larger?

I tried finetuning LLaMA based language models like [Vicuna](https://github.com/lm-sys/FastChat) and multimodal models like [LLaVA](https://github.com/haotian-liu/LLaVA), but do not observe speedups when I switch from v1 to v2. So I am wondering what speedup we should expect and if I am using it correctly.

The way I used flash attention is following Vicuna's implementation,

```python
try:
    from flash_attn.flash_attn_interface import flash_attn_unpadded_qkvpacked_func
except ImportError:
    from flash_attn.flash_attn_interface import flash_attn_varlen_qkvpacked_func as flash_attn_unpadded_qkvpacked_func

# key part only, replace LLaMA attention to use flash attention
output = flash_attn_unpadded_qkvpacked_func(
    qkv, cu_q_lens, max_s, 0.0, softmax_scale=None, causal=True
)
```

Thank you so much!

**Comment by tridao** [comment]
I haven't tried those models, so I don't have end-to-end numbers. You can try benchmarking just the attention layer.

The end-to-end speedup depends on how much time attention is taking. If attention is taking 5% of the time and the rest is matmul / communication etc then you won't see much improvement. This can happen if e.g. you have short sequences, or in some hardware setup where communication is the bottleneck.

**Comment by haotian-liu** [comment]
Thank you for your quick response! This makes sense :)

**Comment by Hap-Zhang** [comment]
@haotian-liu Hi, haotian, may I ask how much training acceleration you have achieved when using flash attention v1 in llama13B?
