### ISSUE TITLE
compiling flash_attn error

### ISSUE THREAD

**Issue by splinter21** [Dao-AILab/flash-attention#331]
![image](https://github.com/Dao-AILab/flash-attention/assets/26759495/3bcb5c2a-7dd6-4453-89c1-95cdb2f73d89)

python setup.py install
torch.__version__  = 2.0.1+cu117
............................
............/csrc/flash_attn/src/flash_bwd_kernel.h:7:10: fatal error: cute/algorithm/copy.hpp: No such file or directory

Driver Version: 510.47.03    CUDA Version: 11.6 
pytorch version 2.0.1
ninja 1.11.1.git.kitware.jobserver-1

**Comment by tridao** [comment]
Strange. `setup.py` should pull `cutlass` (and include `cute`). I'm not sure what happened in this case. Can you try install from PyPI (`pip install flash-attn --no-build-isolation`)?

**Comment by peter-bssf** [comment]
> ![image](https://user-images.githubusercontent.com/26759495/254217526-3bcb5c2a-7dd6-4453-89c1-95cdb2f73d89.png)
> 
> python setup.py install torch.**version** = 2.0.1+cu117 ............................ ............/csrc/flash_attn/src/flash_bwd_kernel.h:7:10: fatal error: cute/algorithm/copy.hpp: No such file or directory
> 
> Driver Version: 510.47.03 CUDA Version: 11.6 pytorch version 2.0.1 ninja 1.11.1.git.kitware.jobserver-1

check your csrc/cutlass dir, it may be empty.
run "git submodule update --init --recursive" in <flash-atten> source dir.

**Comment by mzh1996** [comment]
Same error here! 
pip install flash-attn ------> failed with an error: 
ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects

Then I tried 
python setup.py install
and received same error (flash-attention-main/csrc/flash_attn/src/flash_bwd_kernel.h:7:10: fatal error: cute/algorithm/copy.hpp: No such file or directory)

Does anyone has a solution?

**Comment by timousT** [comment]
> Same error here! pip install flash-attn ------> failed with an error: ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects
> 
> Then I tried python setup.py install and received same error (flash-attention-main/csrc/flash_attn/src/flash_bwd_kernel.h:7:10: fatal error: cute/algorithm/copy.hpp: No such file or directory)
> 
> Then I noticed the suggestion provided by @peter-bssf and I download the cutlass files and rename it as the cutlass directory. Then I retried python setup.py install. Now it is running, but keep reporting (without failing) 26 errors detected in the compilation of flash-attention-main/csrc/flash_attn/src/flash_fwd_hdim160_fp16_sm80.cu
> 
> Let's wait and see.

Where can I download the cutlass and cute files? thank you

**Comment by Dujianhua1008** [comment]
> 文件
cd ./csrc
git clone https://github.com/NVIDIA/cutlass.git
#原因是该文件夹使用链接形式，本地编译时没有该文件夹的内容，需要手动从源连接下载

**Comment by Dujianhua1008** [comment]
> > 文件
> > cd ./csrc
> > git clone https://github.com/NVIDIA/cutlass.git
> > #原因是该文件夹使用链接形式，本地编译时没有该文件夹的内容，需要手动从源连接下载

git submodule update --init --recursive
#或者运行这条命令 会自动下载

**Comment by qijiaxing** [comment]
Solved this problem with `git config --global --add safe.directory <flash-attention-dir>`

Then it can automatically pull cutlass.
