### ISSUE TITLE
pseudo-code of forward pass(algo.1) in Flash-Attention-2 seems wrong？

### ISSUE THREAD

**Issue by FdyCN** [Dao-AILab/flash-attention#333]
I read this paper: https://tridao.me/publications/flash2/flash2.pdf

and I try to use python to implement the forward pass(algo.1) by following the pseudo-code. however the result seems wrong! I reviewed my python code over and over again, and i still cannot find the reason.

Could you help me? Thanks !
algo.1 code:
![image](https://github.com/Dao-AILab/flash-attention/assets/80800417/720d5d14-d14f-4087-8298-093f20c8d0c0)

my python code:
```
def FlashAttentionV2(Q, K, V, scale, M, hd, Br, Bc):
    output = np.zeros(shape=(M,hd))
    for i in range(0,M,Br):
        # load Q_i
        Q_i = Q[i:i + Br,]
        # current sum & max in i-th row.
        l_i = np.zeros(shape=(Br,1))
        m_i = np.zeros(shape=(Br,1)) + float("-inf")
        out_i = np.zeros(shape=(Br,hd))
        for j in range(0,M,Bc):
            # load K\V
            K_j = K[j:j + Bc,]
            V_j = V[j:j + Bc,]
            # compute S_ij
            S_ij = np.matmul(Q_i, K_j.T) * scale
            # compute rowmax m_ij
            m_ij = np.maximum(m_i, (np.max(S_ij, axis=1)[:,None]))
            # compute P_ij
            P_ij = np.exp(S_ij - m_ij)
            # comput current l_ij
            alpha = np.exp(m_i - m_ij) # for reuse
            l_ij = alpha * l_i + (np.sum(P_ij, axis=1)[:,None])

            # compute and update output
            if j != 0:
                out_i = (1 / alpha)  * out_i + np.matmul(P_ij, V_j)
            else:
                out_i = np.matmul(P_ij, V_j)
            # update max & sum
            m_i = m_ij
            l_i = l_ij

        # compute and store output
        output[i:i + Br, ] = (1 / l_i) * out_i
        # compute and store logsumexp L if needed.
        # logsumexp used in Train forward.  

    return output
```

**Comment by tridao** [comment]
Sorry about that, I think there's a typo in the pdf (thanks to Phil Tillet for pointing that out). I've fixed the pdf 8h ago.
For the code I think the only change is this line:
`out_i = (1 / alpha)  * out_i + np.matmul(P_ij, V_j)`
to `out_i = alpha * out_i + np.matmul(P_ij, V_j)`

**Comment by FdyCN** [comment]
> Sorry about that, I think there's a typo in the pdf (thanks to Phil Tillet for pointing that out). I've fixed the pdf 8h ago. For the code I think the only change is this line: `out_i = (1 / alpha) * out_i + np.matmul(P_ij, V_j)` to `out_i = alpha * out_i + np.matmul(P_ij, V_j)`

Thank you for the reply， I checked the fix and it works fine. that's nice.
