### ISSUE TITLE
install failure in ngc-pytorch-2306

### ISSUE THREAD

**Issue by ftgreat** [Dao-AILab/flash-attention#347]
In ngc-pytorch-2306 container, one failure about ninja happend. 
As this container already has flashatten v1, we use the command: pip install flash-attn --no-build-isolation.
Also, tried installation from source, same failure happened.

It seems that the command ninja -v failed.

How to deal with this, thank you very much.

![img_v2_9a8a0d4c-a61c-438c-a8d7-dfd1e90920cg](https://github.com/Dao-AILab/flash-attention/assets/10432020/e525b54a-c4cd-438a-bce8-94fbc57ec9de)
![img_v2_94e083ff-6a85-4e9b-852e-8cb01232a63g](https://github.com/Dao-AILab/flash-attention/assets/10432020/d9227acf-6af8-48a0-a523-31b04b894380)

**Comment by tridao** [comment]
Can you try to uninstall and reinstall ninja (`pip uninstall -y ninja && pip install ninja`) to see if that fixes ninja?

**Comment by ftgreat** [comment]
After reinstall ninja (pip uninstall -y ninja && pip install ninja), failures show as follows:
![image](https://github.com/Dao-AILab/flash-attention/assets/10432020/4fc395c8-03b2-43cd-bf8a-06e8e40ee1e8)

**Comment by tridao** [comment]
It says "Killed" so maybe it's running out of RAM during compilation. Just a guess.
Can you try compiling with `MAX_JOBS=4 pip install flash-attn --no-build-isolation`?

**Comment by ftgreat** [comment]
> 
Yes, that's the cause. Recompiling is successful.
Thanks.
