### ISSUE TITLE
How to run deterministically?

### ISSUE THREAD

**Issue by ksivaman** [Dao-AILab/flash-attention#349]
I noticed that the `deterministic` argument was removed in the FlashAttention2 APIs and there isn't an obvious way to tweak it since the `num_splits` argument was also removed from the python interfaces. How can we make internal changes to achieve a deterministic outcome?

**Comment by tridao** [comment]
The forward pass is deterministic. For the backward pass, there's a code path that's deterministic for the (essentially equivalent to num_split=1) but it's not enabled right now. I plan to test it more to make sure it works on different GPU types and enable that in the next couple of weeks.

**Comment by ksivaman** [comment]
Could you share which path that is?

**Comment by tridao** [comment]
It's this "loop" [kernel](https://github.com/Dao-AILab/flash-attention/blob/b8020d73c9e068665586989883083a4a5429a443/csrc/flash_attn/src/flash_bwd_launch_template.h#L22) where instead of having multiple thread blocks dealing with 1 attention head, we just have 1 thread block that loops over the column blocks.

**Comment by ksivaman** [comment]
Are the changes available in any branch for me to test/modify? Thanks! @tridao

**Comment by tridao** [comment]
No it's just some commented out code for now. I'm focusing on fixing some issues with the backward pass, will have some time next week to test this deterministic code path.

**Comment by ksivaman** [comment]
Is the support/testing for this something I can help with if the code already exists? @tridao

**Comment by cbcase** [comment]
Checking on this issue -- is the plan still to have an option for deterministic backward or to leave it be for now? (We can use `F.scaled_dot_product_attention` for tests that require deterministic grads, but it's a bummer to have the test path and production path run different kernels). Thanks!

**Comment by tridao** [comment]
There's an option for deterministic bwd in v2.4.1.
