### ISSUE TITLE
Do you have a recommended stack of cuda dependencies?

### ISSUE THREAD

**Issue by rahul003** [Dao-AILab/flash-attention#350]
Versions for cuda, cutlass, etc.

**Comment by tridao** [comment]
We recommend the [Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) container from Nvidia. 
The latest [version](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-06.html) (23.06) has CUDA 12.1, Pytorch 2.1.0alpha. We set cutlass to v3.0.0 (this is specified as a submodule in this repo).

**Comment by rahul003** [comment]
Thanks
