### ISSUE TITLE
Obsolete version collected by using "pip install flash-attn"

### ISSUE THREAD

**Issue by yumesann** [Dao-AILab/flash-attention#357]
When I install flash-attn by "pip install flash-attn" without any version restricted I got v0.2.8.
That confuses me a lot at first, because of the interface difference.

**Comment by tridao** [comment]
It's possible that's the version already installed (e.g. in Nvidia's pytorch docker image) and you need to update it (`pip install -U flash-attn`).

**Comment by yumesann** [comment]
> It's possible that's the version already installed (e.g. in Nvidia's pytorch docker image) and you need to update it (`pip install -U flash-attn`).
Thank you, I think maybe that's the reason.I do used Nvidia pytorch docker image.
