### ISSUE TITLE
[V2]Question about the GPU resouce allocation policy？

### ISSUE THREAD

**Issue by FdyCN** [Dao-AILab/flash-attention#361]
in the paper, we can see that Q_i、K_j、V_j is in SRAM，total SRAM size per CTA is：
SRAM_PER_CTA = Br * headDim * sizeof(half) + 2 * Bc * sizeof(half)。// TensorCore support fp16 by default.

BUT, i found that Out_i is in Fragment_C which placed in registers，like the source code says:
https://github.com/Dao-AILab/flash-attention/blob/9ee0ff1d9b6a99630e2a6868b9291dfa32d35abd/csrc/flash_attn/src/flash_fwd_kernel.h#L204

I am not familiar with cutlass & cute, but it seems we allocate [Br, headDim] size of fragment register in a single WARP???

It's really big and seems beyond the limitation easily ? 
(sm_86, max 64KB register per SM, max 255 reg per thread).  In the paper [Br,Bc] will choosed in {64,128}x{64,128}，so we assume that [Br, headDim] = [64, 128]，and the sizeof(acc_o) = 64 * 128 * sizeof(half) = 16KB， 4-warp in a CTA，and total reg will be 64KB，out of resource？

please tell me i‘m wrong, or I can't figure it out. Thanks!

**Comment by tridao** [comment]
if (Br, headDim) = (64, 128), we have 4 warps to hold acc_o of size 64 x 128. Each warp will hold 16 x 128. acc_o is stored in fp32. So each warp uses 8KB of registers, and each CTA uses 32KB of registers for acc_o. 
Each SM has a max of 256KB of registers (64K of registers, each register can hold 32 bits). So we still have registers for other things. And we actually can schedule 2 CTAs per SM.

**Comment by FdyCN** [comment]
> if (Br, headDim) = (64, 128), we have 4 warps to hold acc_o of size 64 x 128. Each warp will hold 16 x 128. acc_o is stored in fp32. So each warp uses 8KB of registers, and each CTA uses 32KB of registers for acc_o. Each SM has a max of 256KB of registers (64K of registers, each register can hold 32 bits). So we still have registers for other things. And we actually can schedule 2 CTAs per SM.

thank you for your reply, that makes sense. Br x headDim register size used in a CTA(4-warps) not just a SINGLE WARP. 

and thank you to point out that acc_o is fp32.

PS: i thought that `partition_fragment_C` is the same as wmma::Fragment which is a warp-level data structure subconsciously. So it's turn out to be wrong. thank you.

**Comment by FdyCN** [comment]
> if (Br, headDim) = (64, 128), we have 4 warps to hold acc_o of size 64 x 128. Each warp will hold 16 x 128. acc_o is stored in fp32. So each warp uses 8KB of registers, and each CTA uses 32KB of registers for acc_o. Each SM has a max of 256KB of registers (64K of registers, each register can hold 32 bits). So we still have registers for other things. And we actually can schedule 2 CTAs per SM.

@tridao i got one more question. "And we actually can schedule 2 CTAs per SM", using 32KB registers / CTA for acc_o，2 CTA will used all registers on SM，and no more registers for other params？ or you mean when there are 2 CTA per SM, each CTA will handle less headDim to use less registers？ otherwise, there will be register limits.

**Comment by tridao** [comment]
There's 256KB of registers per SM.

**Comment by FdyCN** [comment]
> There's 256KB of registers per SM.

@tridao thank you, my bad! overlooked
