### ISSUE TITLE
What's the differences about split_q policy in the fwd pass between flash-1 and flash-2

### ISSUE THREAD

**Issue by endurehero** [Dao-AILab/flash-attention#369]
I saw the following description about Parallelism in the flash-2 paper:
"The first version of FlashAttention parallelizes over batch size and number of heads. We use 1 thread
block to process one attention head, and there are overall batch size · number of heads thread blocks."

But I found that even flash1 took a similar approach: https://github.com/Dao-AILab/flash-attention/blob/v1.0.9/csrc/flash_attn/src/fmha_fwd_launch_template.h#L86

Why is flash-2 more efficient than flash-1 in terms of parallelization?

**Comment by tridao** [comment]
FlashAttention 1 in the paper refers to the version released in May 2022, which didn't have this kind of parallelism.
v1.0.9 has some parallelism, similar idea, but wasn't done very cleanly. We had to decide up front how many thread blocks to split along the seqlen dimension (i.e. num_split), using some heuristic.
v2 has a clean implementation, where each thread blocks just takes care of blocks of length 128 or 64 (depending on head dimension).

The speedup from v1 to v2 is a combination of multiple techniques, not just 1.
