### ISSUE TITLE
Compiling error on H800

### ISSUE THREAD

**Issue by yingtongxiong** [Dao-AILab/flash-attention#371]
Hello, when I compile flash-attn 2.0 on H800. I met the following problem.
![企业微信截图_3fa1c8f6-907f-4171-95d1-777016799e12](https://github.com/Dao-AILab/flash-attention/assets/45058324/d002d229-9e7c-444c-955a-b118085732f2)
Can you help me with this? I think that my nvcc is installed correctly. 
The environment I used:
GCC: 10.2.0
nvcc: 11.8
GPU: H800
torch: 2.0

**Comment by tridao** [comment]
I'm afraid that's not enough information. Can you try with the recommended docker image from nvidia? And maybe set MAX_JOBS=4 as mentioned in the README.

**Comment by yingtongxiong** [comment]
Thank you very much. I finally installed flash-attn 2.0 successfully in pip install way. I do not know why I met this problem when I try to install it from source.
