### ISSUE TITLE
tests/models/test_llama.py::test_llama_state_dict error

### ISSUE THREAD

**Issue by leiwen83** [Dao-AILab/flash-attention#375]
Hi,

I find do below pytest would report error:

```
E       AssertionError: assert odict_keys(['...head.weight']) == {'lm_head.wei....weight', ...}
E         Full diff:
E         + odict_keys(['transformer.embeddings.word_embeddings.weight', 'transformer.layers.0.mixer.Wqkv.weight', 'transformer.layers.0.mixer.out_proj.weight', 'transformer.layers.0.norm1.weight', 'transformer.layers.0.mlp.fc1.weight', 'transformer.layers.0.mlp.fc2.weight', 'transformer.layers.0.norm2.weight', 'transformer.layers.1.mixer.Wqkv.weight', 'transformer.layers.1.mixer.out_proj.weight', 'transformer.layers.1.norm1.weight', 'transformer.layers.1.mlp.fc1.weight', 'transformer.layers.1.mlp.fc2.weight', 'transformer.layers.1.norm2.weight', 'transformer.layers.2.m...
E
E         ...Full output truncated (231 lines hidden), use '-vv' to show
```

I checked state_dict.keys(), and its lack the rotary_emb, which I could see it while I directly print the model.
So it seem to me that rotary_emb has been put into state_dict keys, which lead to this error?

**Comment by tridao** [comment]
Yes, it about the rotary inv_freqs. I've just fixed the test to load the model correctly.

**Comment by leiwen83** [comment]
It is wierd. when I test with latest 4c98d0b41f38ee638a979064856ae06fc1aec8b6,
I find it still error at "    assert state_dict.keys() == pretrained_state_dict.keys()".
but this time, state_dict has the rotary_inv_freq_keys, while pretrained has not...

Do you mind that also provide your test Llama model download place? So that our test could be aligned?

**Comment by tridao** [comment]
`state_dict` shouldn't have the rotary_inv_freq keys since I set that buffer to `persistent=False` [here](https://github.com/Dao-AILab/flash-attention/blob/4c98d0b41f38ee638a979064856ae06fc1aec8b6/flash_attn/layers/rotary.py#L239).

`pretrained_state_dict` is read from LLaMa weights downloaded from Meta. The directory for the 7B model has files `params.json` and `consolidated.0.pth` I think.

**Comment by leiwen83** [comment]
It is my mistake that there is old version in the docker env which is not replaced by the new setup install.
After uninstall the old one[1.0.4], the test passed.

Thx
