### ISSUE TITLE
How to deploy flash-atten to TensorRT?

### ISSUE THREAD

**Issue by 2401ch** [Dao-AILab/flash-attention#378]
This work is really great！I am deploying flash-attention transformer now, convert pytorch model ->onnx ->tensorrt, but failed, do you know how to deploy flash-attention transformer on tensorRT framework?

**Comment by tridao** [comment]
I've never use TensorRT so I've no idea. I assume you'll need to copy the code to TensorRT. Let me know if you figure out.

**Comment by npuichigo** [comment]
@tridao How about onnx conversion? Or are the weights trained with flash-attention compatible with a common transformer model so I can copy the weights?

**Comment by tridao** [comment]
Yes weights are compatible.

**Comment by 543877815** [comment]
> This work is really great！I am deploying flash-attention transformer now, convert pytorch model ->onnx ->tensorrt, but failed, do you know how to deploy flash-attention transformer on tensorRT framework?

Hi, did you solve this problem? @chenghan1995

**Comment by chenghan1995** [comment]
I haven't solved it. Perhaps you can refer this work：https://github.com/DerryHub/BEVFormer_tensorrt. Flash Multi-Head Attention is plugged and it may be useful for you.

**Comment by scuizhibin** [comment]
> This work is really great！I am deploying flash-attention transformer now, convert pytorch model ->onnx ->tensorrt, but failed, do you know how to deploy flash-attention transformer on tensorRT framework?
Did it succeed?
