### ISSUE TITLE
Memory leakage during `Building wheels for collected packages` for flash-attn==2.0.1

### ISSUE THREAD

**Issue by DesperateExplorer** [Dao-AILab/flash-attention#382]
Hi authors,
On a machine with about 39 GB CPU memory, `Building wheels for collected packages` of `flash-attn` 2.0.1 rapidly takes up all the memory and causes the machine to crash. (The CUDA version is 11.0, but I just need to install `flash-attn` to enable related code highlights) It there any workaround?

**Comment by tridao** [comment]
As mentioned in the README, you can set MAX_JOBS.

**Comment by DesperateExplorer** [comment]
Thanks. Solved.
