### ISSUE TITLE
Why is there a difference in the same configuration when using causel at the time

### ISSUE THREAD

**Issue by zte-tcb** [Dao-AILab/flash-attention#384]
I use flash_attn_func to replace the original attention. And set same seed/weights/data and other config. Run many times on the original code, and the training results are exactly the same. However, there are a little difference in the results of running many times after using Flash Attn.  Why?

The difference is as follows, the value in the form is evaluating loss.
                       step2	step4	step6	step8
  flash_attn  14.9453	11.2422	9.0938	7.2852
  flash_attn  14.9531	11.2422	9.1016	7.293
  flash_attn   14.9375	11.2422	9.1016	7.2812

orighin attn  14.9297	11.2734	9.2109	7.2969

**Comment by tridao** [comment]
The backward pass is not deterministic (we're using atomic adds) so small differences are expected.

**Comment by zte-tcb** [comment]
I see it!  Some operations use atomic operations in a way that introduces truly random floating point rounding errors.
Thanks.
 https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#reproducibility
