### ISSUE TITLE
`MAX_JOBS` affects the installation

### ISSUE THREAD

**Issue by BestJuly** [Dao-AILab/flash-attention#389]
Environment: 
- Docker: `nvcr.io/nvidia/pytorch:23.06-py3`
- A100

Installation:
1. `pip uninstall flash_attn`, uninstall because `flash_attn` is already in the docker
2. `MAX_JOBS=4 pip install flash-attn --no-build-isolation`

The above procedure works well. However, it will raise errors for step 2 if using 
- `pip install flash-attn --no-build-isolation`
- `MAX_JOBS=16 pip install flash-attn --no-build-isolation`
- `MAX_JOBS=64 pip install flash-attn --no-build-isolation`

The error log is very long so I do not paste here. Does such case affect by installation dependencies?

**Comment by tridao** [comment]
MAX_JOBS controls how many processes to compile in parallel. With large values of `MAX_JOBS` it might run out of RAM during compilation, hence the error. That's my guess.

**Comment by BestJuly** [comment]
@tridao Thanks for the explanation.

The error log does not provide messages about running out of RAM (maybe it would not even meet this issue).

I monitoring the memory usage
```
top - 01:20:22 up  1:01,  1 user,  load average: 51.09, 19.76, 12.06
Tasks: 525 total,   3 running, 522 sleeping,   0 stopped,   0 zombie
%Cpu(s): 41.7 us, 35.5 sy,  0.0 ni,  8.6 id, 13.8 wa,  0.0 hi,  0.4 si,  0.0 s
MiB Mem : 128686.2 total,    571.3 free, 128028.8 used,     86.1 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.    524.7 avail Mem
```
The number of free memory becomes very small during building. However, the error is trigged when the free memory grows to even 100000+.  Not sure whether there is delay for such error, but I think this should be the root cause.

I will close the issue as we already have the right command to build the package. And I pose this in case others meet similar issue.
