### ISSUE TITLE
Do we have benchmark result, triton version vs cutlass?

### ISSUE THREAD

**Issue by leiwen83** [Dao-AILab/flash-attention#390]
Hi,

I wonder know that whether we have benchmark result for triton version vs cutlass version?
Since both is implemented, it is interesting to know which is better.

Thx

**Comment by tridao** [comment]
The benchmark numbers are in the [README](https://github.com/Dao-AILab/flash-attention/tree/main#performance).

**Comment by leiwen83** [comment]
The README benchmark result only list "flashatten triton", is it implentation for the V1?
What's the performance result for triton version for V2?

**Comment by tridao** [comment]
Idk, I might push some script to run the benchmarks soon. Feel free to run them.

**Comment by tridao** [comment]
I've just add a script to benchmark [here](https://github.com/Dao-AILab/flash-attention/blob/main/benchmarks/benchmark_flash_attention.py). The best way to compare is to run the benchmark yourself.

The Triton implementation is evolving, but you can look at their performance data [here](https://github.com/openai/triton/blob/2689f4a3b01a60a4fb6ec92d94f46e5948682807/python/test/regression/test_performance.py#L156). The last number in each line is the fraction of theoretical max performance, you can take that and multiply by 312 TFLOPs/s (for A100) and compare with the numbers we have for FlashAttention2 in the README. I think technically Triton's data is measured on A100 40GB and our data in the README is measured on A100 80GB, but the two settings should be pretty close.

I think right now Triton forward is on par with CUDA forward for headdim=64 but slower for headdim=128. The Triton backward is still the same as when I benchmarked it 2 weeks ago (shown in the README), so about 2x slower than the CUDA backward. This could change in the future as the Triton version is improved.

**Comment by leiwen83** [comment]
Thx, I would give it a try. ;)
