### ISSUE TITLE
flash_attn_qkvpacked_func support for MQA/GQA

### ISSUE THREAD

**Issue by markelausin** [Dao-AILab/flash-attention#392]
The docstring for flash_attn_qkvpacked_func says that qkv should have the shape: qkv: (batch_size, seqlen, 3, nheads, headdim).

If that is the case, nheads must be the same value for all 3 sub-tensors (Q, K and V). How can we do MQA/GQA with this function if we have to pass a single tensor for all 3, but they have different shapes?

This is not an issue in flash_attn_func because we pass all 3 tensors separately.

**Comment by tridao** [comment]
Right, you'd want to use `flash_attn_func` for MQA/GQA as mentioned in the docstring.

**Comment by markelausin** [comment]
Doesn't the docsting imply that `flash_attn_qkvpacked_func` also supports MQA/GCA?
```
def flash_attn_qkvpacked_func(qkv, dropout_p=0.0, softmax_scale=None, causal=False,
                              return_attn_probs=False):
    """
    ...
    Supports multi-query and grouped-query attention (MQA/GQA) by passing in KV with fewer heads
    than Q. Note that the number of heads in KV must be divisible by the number of heads in Q.
    For example, if Q has 6 heads and K, V have 2 heads, head 0, 1, 2 of Q will attention to head
    0 of K, V, and head 3, 4, 5 of Q will attention to head 1 of K, V.
```

**Comment by tridao** [comment]
Ah that's a mistake. I'll change the docstring.

**Comment by markelausin** [comment]
Thank you for clarifying!
