### ISSUE TITLE
Mistake in flash_attn docstrings?

### ISSUE THREAD

**Issue by hiddefolkertsma** [Dao-AILab/flash-attention#397]
First of all thanks for all your work on speeding up attention!

While adding `flash_attn_func` to my code, I was a bit confused by its docstring: shouldn't the number of heads in `Q` be divisible by the number of heads in `KV` instead of the other way around?

https://github.com/Dao-AILab/flash-attention/blob/184b992dcb2a0890adaa19eb9b541c3e4f9d2a08/flash_attn/flash_attn_interface.py#L349-L351

(This comment appears a few more times, if this is indeed a mistake I'm happy to PR a fix)

**Comment by tridao** [comment]
Thanks for the catch! I've just fixed it
