### ISSUE TITLE
When use flash_attn_func or flash_attn_qkvpacked_func is this now implementing Flash Attention V1 or V2?

### ISSUE THREAD

**Issue by ag583** [Dao-AILab/flash-attention#399]
1.) When use flash_attn_func or flash_attn_qkvpacked_func is this now implementing Flash Attention V1 or V2?

2.) If it is implementing Flash Attention V2 now, is there a way to still run the original Flash Attention implementation for comparison?

**Comment by tridao** [comment]
Both are running FlashAttention v2. I'm not sure there's an easy way to run v1 side by side with v2, maybe install `pip install flash-attn==1.0.9` then somehow install v2 locally under a different package name. If you figure out lmk.
