### ISSUE TITLE
who can develop a update of flash_attn_triton

### ISSUE THREAD

**Issue by janelu9** [Dao-AILab/flash-attention#400]
I want torch 2 support a mask bias

**Comment by jessiewiswjc** [comment]
Isn't mask bias already supported in flash_attn_triton?
https://github.com/Dao-AILab/flash-attention/blob/364a5b4a71203b9977def9829a5c1a6af45468c8/flash_attn/flash_attn_triton.py#L596

**Comment by janelu9** [comment]
> Isn't mask bias already supported in flash_attn_triton?
> 
> https://github.com/Dao-AILab/flash-attention/blob/364a5b4a71203b9977def9829a5c1a6af45468c8/flash_attn/flash_attn_triton.py#L596

Only `triton==2.0.0.dev20221202` was supported

**Comment by jessiewiswjc** [comment]
> > Isn't mask bias already supported in flash_attn_triton?
> > https://github.com/Dao-AILab/flash-attention/blob/364a5b4a71203b9977def9829a5c1a6af45468c8/flash_attn/flash_attn_triton.py#L596
> 
> Only `triton==2.0.0.dev20221202` was supported

Do you want to use it on the release version of triton? do you have a solution now?
