### ISSUE TITLE
does flash attention support attention mask? 

### ISSUE THREAD

**Issue by tiandiao123** [Dao-AILab/flash-attention#409]
Hello friends:
   I am wondering whether current flash attention version supports attention mask? Since I didn't see some arguments in fwd function, so I am really curious. Thank you!
Best

**Comment by tridao** [comment]
No it doesn't support attention mask. We might implement that in the future when we have bandwidth, but right now we have  some other priorities (e.g. H100 optimization).

**Comment by tiandiao123** [comment]
> No it doesn't support attention mask. We might implement that in the future when we have bandwidth, but right now we have some other priorities (e.g. H100 optimization).

Thank you!
