### ISSUE TITLE
Result does not match pytorch implmentation

### ISSUE THREAD

**Issue by CoinCheung** [Dao-AILab/flash-attention#410]
Hi,

I am using version 2.0.1, and my gpu is A100(40G), I am testing with the following code: 
```python
import math
import torch
import torch.nn.functional as F
from flash_attn import flash_attn_func


inten = torch.randn(3, 2, 768, 32, 128).cuda().half()
query_states, key_states, value_states = inten[0], inten[1], inten[2]
inv_norm_factor = 1. / math.sqrt(128)

attn_output_fl = flash_attn_func(
        query_states,
        key_states,
        value_states,
        dropout_p=0., softmax_scale=inv_norm_factor,
        causal=False)

attn = torch.einsum('bihd,bjhd->bhij', query_states, key_states).mul(inv_norm_factor)
attn = F.softmax(attn, dim=-1, dtype=torch.float32).to(query_states.dtype)
attn_output = torch.einsum('bhij,bjhd->bihd', attn, value_states)
print((attn_output_fl - attn_output).abs().sum())

````

And I found the result is not 0, which means that the results of pytorch implementation and flash-atten does not align with each other. What is wrong with my implementation?

**Comment by tridao** [comment]
Some numerical difference is expected. Floating operations aren't exactly associative (e.g. `a + b + c` will give slightly different result compared to `a + c + b`), you can try that out.
I usually compare:
(FlashAttention in bf16/fp16 - standard attention in fp32) vs (standard attention in bf16/fp16 - standard attention in fp32).
This gives you an idea if what's the expected numerical difference.

**Comment by CoinCheung** [comment]
Hi Dao,

Thanks for giving such a quick reply !!!

 I do not think it is numerical difference, I got an result of 199:
![image](https://github.com/Dao-AILab/flash-attention/assets/22693362/b499b39d-0d63-4648-a107-62f6aa1bf30a)
Do you have any insights on this please?

**Comment by tridao** [comment]
Note that you're summing the numerical differences over 6M elements. Sum of differences of 200 means on avg the numerical difference is 3e-5.  What's the numerical error when you compare (standard attention in fp16 - standard attention in fp32)?

**Comment by tridao** [comment]
To clarify: 
standard attention in fp32 means you convert q, k, v to fp32, do all calculation in fp32.
standard attention in fp16 means you keep q, k, v in fp16, do calculations in fp16.

**Comment by CoinCheung** [comment]
Hi Dao,

When I try to use `max()` instead of `sum()`, and I run for several time, the largest different is about `1e-3`:
```python
print((attn_output_fl - attn_output).abs().max())
```
Is this margin of `1e-3` expected?

**Comment by tridao** [comment]
What's the numerical error when you compare (standard attention in fp16 - standard attention in fp32)?

**Comment by CoinCheung** [comment]
Hi,

When I try to run in fp32 mode, I got the error message of:
```
  File "/home/.conda/envs/py39/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 222, in forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = _flash_attn_forward(
  File "/home/.conda/envs/py39/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 42, in _flash_attn_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
RuntimeError: FlashAttention only support fp16 and bf16 data type

```

**Comment by tridao** [comment]
I modified your code to do the comparison:
```
import math
import torch
import torch.nn.functional as F
from flash_attn import flash_attn_func


inten = torch.randn(3, 2, 768, 32, 128).cuda().half()
query_states, key_states, value_states = inten[0], inten[1], inten[2]
inv_norm_factor = 1. / math.sqrt(128)

attn_output_fl = flash_attn_func(
        query_states,
        key_states,
        value_states,
        dropout_p=0., softmax_scale=inv_norm_factor,
        causal=False)

attn = torch.einsum('bihd,bjhd->bhij', query_states, key_states).mul(inv_norm_factor)
attn = F.softmax(attn, dim=-1, dtype=torch.float32).to(query_states.dtype)
attn_output = torch.einsum('bhij,bjhd->bihd', attn, value_states)

attn_ref = torch.einsum('bihd,bjhd->bhij', query_states.float(), key_states.float()).mul(inv_norm_factor)
attn_ref = F.softmax(attn_ref, dim=-1, dtype=torch.float32)
attn_output_ref = torch.einsum('bhij,bjhd->bihd', attn_ref, value_states.float())
print((attn_output_fl - attn_output_ref).abs().max())  # 0.0002
print((attn_output - attn_output_ref).abs().max())  # 0.0012
```
FlashAttention is *more* accurate in this case.

**Comment by CoinCheung** [comment]
Thanks for telling me this!!

I found my code does not converge after switching to flash-attention, I will check my code more carefully.
