### ISSUE TITLE
Would you plan to support Apple mac M1/M2？

### ISSUE THREAD

**Issue by Johnson-yue** [Dao-AILab/flash-attention#412]

**Comment by Johnson-yue** [comment]
@tridao  thanks you

**Comment by okpatil4u** [comment]
@tridao thanks. How would someone replace the current flash attention implementation from [H3](https://github.com/HazyResearch/H3) ? Can you give us some guidelines ?

**Comment by edmondja** [comment]
Sad, not fighting against Nvidia's monopoly xD
