### ISSUE TITLE
Question on How to Modify the Fused_Dense.py file

### ISSUE THREAD

**Issue by macrocredit** [Dao-AILab/flash-attention#413]
Hi - I wanted to add some print statements or modify/add some new classes to the fused_dense.py file. However, I noticed that despite adding those print statements, the print statements won't appear. I tried to add new classes (i.e. class Example) and import it "from flash_attn.ops.fused_dense import FusedDense, FusedMLP, Example
" but there is an error: /ext3/miniconda3/envs/XYZ/lib/python3.11/site-packages/flash_attn-2.0.4-py3.11-linux-x86_64.egg/flash_attn/ops/fused_dense.py.

Therefore, modifying this file fused_dense.py will not change the flash attention's FusedDense class. Hence, I was wondering if there is any way I can directly modify fused_dense.py file and see the changes? I tried python setup.py install (instead of pip install .) in the /flash-attention/csrc/fused_dense_lib but the resulting changes will not take place. Thanks.

**Comment by tridao** [comment]
You'd want an "editable" installation: https://stackoverflow.com/questions/35064426/when-would-the-e-editable-option-be-useful-with-pip-install
