### ISSUE TITLE
Support varlen in RotaryEmbedding

### ISSUE THREAD

**Issue by zhuzilin** [Dao-AILab/flash-attention#422]
Hi! Our team is super excited with your project, and very interested in the varlen version of the attention api. Just like what the [vllm](https://github.com/vllm-project/vllm) team did with inference, we think that varlen in training could bring huge performance improvement, especially during sft, where the training samples are inherently varlen.

Therefore, we hope to train models with varlen end2end and reuse the existing modules in flash_attn as many as possible. And during our experiment, we found that the `RotaryEmbedding` kernel need some changes to accept varlen inputs and submitted a PR related (https://github.com/Dao-AILab/flash-attention/pull/408). The idea is quite simple, when passing `cu_seqlens` to RoPE, we will calculate each sequence with a RoPE cos and sin started from 0:

```
 seq: |         seq0         |         seq1         |          seq2        |
RoPE: |0, 1, ..., len(seq0)-1|0, 1, ..., len(seq1)-1|0, 1, ..., len(seq2)-1|
```

Noted that, maybe training with random starting RoPE offset may help extrapolate RoPE, as some papers claim (e.g. [the compress RoPE one by meta](https://arxiv.org/abs/2306.15595)) that the reason RoPE failed to extrapolate to a longer context length is that the model never met RoPE at that position during training. So maybe we could even do this:

```
 seq: |           seq0           |           seq1           |           seq2           |
RoPE: |r0,r0+1,...,r0+len(seq0)-1|r1,r1+1,...,r1+len(seq0)-1|r2,r2+1,...,r2+len(seq0)-1|

where r0, r1, r2 are random ints.
```

We wonder what's your idea on supporting varlen RotaryEmbedding and if you like it, how shall we implement it?

Thank you for your time on this issue.

**Comment by FrancescoSaverioZuppichini** [comment]
so what was the solution?

**Comment by tridao** [comment]
I think ideally we'd have a rotary kernel that can deal with variable sequence lengths.
