### ISSUE TITLE
Can flash attention be used for inference?

### ISSUE THREAD

**Issue by Shannen3206** [Dao-AILab/flash-attention#427]
I tried inference with and without flash attention in the megatron-deepspeed code and found a difference in inference speed of just 0.2 seconds. 

In addition, in huggingface's openllama model structure, flash attention is also limited to training. 
![image](https://github.com/Dao-AILab/flash-attention/assets/53463361/3bb87730-d47c-41b6-a95a-59b058df9068)

Can flash attention be used for inference acceleration?

**Comment by tridao** [comment]
FlashAttention right now isn't very fast for iterative decoding where Q has seqlen=1 (you can use it for prompt processing). It's ongoing work, we'll eventually make inference fast (idk when yet).

**Comment by 77h2l** [comment]
@tridao hello，can flash_attn only be used for inference, in other word, when a model was trained by standard attention, can it use flash_attn to replace during infernce,thx

**Comment by tridao** [comment]
> @tridao hello，can flash_attn only be used for inference, in other word, when a model was trained by standard attention, can it use flash_attn to replace during infernce,thx

Yes, FlashAttention computes the same attention (up to usual numerical difference). You can also train with FlashAttention and do inference with standard attention.

**Comment by jmzeng** [comment]
Want to follow up on this. I tried to do inference on `longchat-v1.5-7b-32k` with the flash attention patch and was getting OOM on a single inference run with accelerate. Do you know if there is a way to fix this?

**Comment by tridao** [comment]
Yes you can use FlashAttention 2, for both prompt processing and iterative decoding.

**Comment by thusinh1969** [comment]
> > @tridao hello，can flash_attn only be used for inference, in other word, when a model was trained by standard attention, can it use flash_attn to replace during infernce,thx
> 
> Yes, FlashAttention computes the same attention (up to usual numerical difference). You can also train with FlashAttention and do inference with standard attention.

Love you my man (a VN hard core here...!) 

Cheers,
Steve
