### ISSUE TITLE
Complie error while transplanting flash attention2 to AITemplate 

### ISSUE THREAD

**Issue by yumesann** [Dao-AILab/flash-attention#428]
I am trying to transplant flash attention 2 to AITemplate, but got a lot of errors of the function "copy".
Here's details
`/data/AITemplate/3rdparty/../static/include/kernels/flash_attn_2/utils.h(338): error: no instance of function template "flash::copy" matches the argument list
            argument types are: (cute::ThrCopy<cute::TiledCopy<cute::Copy_Atom<cute::SM80_CP_ASYNC_CACHEGLOBAL<cute::uint128_t, cute::uint128_t>, cutlass::half_t>, cute::Layout<cute::tuple<cute::tuple<cute::constant<int, 8>, cute::constant<int, 16>>, cute::_8>, cute::tuple<cute::tuple<cute::_128, cute::_1>, cute::_16>>, cute::tuple<cute::_16, cute::constant<int, 64>>>, int>, cute::Tensor<cute::ViewEngine<cute::gmem_ptr<cutlass::half_t>>, cute::Layout<cute::tuple<cute::tuple<cute::_8, cute::_1>>, cute::tuple<cute::tuple<cute::_1, cute::constant<int, 0>>>>>, cute::Tensor<cute::ViewEngine<cute::smem_ptr<cutlass::half_t>>, cute::Layout<cute::tuple<cute::tuple<cute::_8, cute::_1>>, cute::tuple<cute::tuple<cute::_1, cute::constant<int, 0>>>>>)
                      copy(thr_copy, S(_, m, k), D(_, m, k));`

From the information I guess it is because the compiler considered the cute::copy as the flash::copy.
Here is the complie command. May anyone help me with this ?

`nvcc -t=0 -DCUTLASS_ENABLE_TENSOR_CORE_MMA=1 -w -gencode=arch=compute_80,code=[sm_80,compute_80] -O3 -std=c++17 --expt-relaxed-constexpr  -DNDEBUG --use_fast_math -DCUTLASS_USE_TANH_FOR_SIGMOID=1 -DAIT_USE_FAST_MATH=1 -Xcompiler=-fPIC -Xcompiler=-Wconversion -Xcompiler=-fno-strict-aliasing -Xcompiler -fvisibility=hidden -I/data/AITemplate/3rdparty/../static/include/kernels -I/data/AITemplate/3rdparty/cutlass/include -I/data/AITemplate/3rdparty/cutlass/tools/util/include -I/data/AITemplate/3rdparty/cutlass/examples/35_gemm_softmax -I/data/AITemplate/3rdparty/cutlass/examples/41_fused_multi_head_attention -I/data/AITemplate/3rdparty/cutlass/examples/45_dual_gemm -I/data/AITemplate/3rdparty/cutlass/../../python/aitemplate/backend/cuda/attention/src/./ -c -o flash_attention2_0.obj flash_attention2_0.cu`

**Comment by tridao** [comment]
We've just switched to cutlass 3.1. Can you see if that works with AITemplate?

**Comment by yumesann** [comment]
> We've just switched to cutlass 3.1. Can you see if that works with AITemplate?
@tridao Thank you! I tried and it works with AITemplate cutlass. Looking forward further update.
