### ISSUE TITLE
The output result of _flash_attn_backward in flash_attn_triton.py is random

### ISSUE THREAD

**Issue by t90tank** [Dao-AILab/flash-attention#429]
I use flash attention to train my model multiple times, and get different results when use same seed.
The reason is there will be different results each time when calling _flash_attn_backward.

Here is my code appending in flash_attn_triton.py to confirm it:

```
if __name__ == "__main__":
    batch_size = 32
    seqlen = 1024
    nheads = 32
    headdim = 128
    torch.manual_seed(233)
    q = torch.rand((batch_size, seqlen, nheads, headdim), dtype=torch.bfloat16, device="cuda")
    k = torch.rand_like(q)
    v = torch.rand_like(q)
    bias = torch.rand((1, nheads, seqlen, seqlen), dtype=torch.bfloat16, device="cuda")
    q, k, v = [x if x.stride(-1) == 1 else x.contiguous() for x in [q, k, v]]
    o, lse, softmax_scale = _flash_attn_forward(
        q, k, v, bias=bias, causal=True, softmax_scale=None)
    do = torch.rand_like(o)
    with torch.inference_mode():
        dq = torch.empty_like(q)
        dk = torch.empty_like(k)
        dv = torch.empty_like(v)
        _flash_attn_backward(do, q, k, v, o, lse, dq, dk, dv,
                                bias=bias, causal=True, softmax_scale=None)
    t = {
            "dq" : dq,
            "dk" : dk,
            "dv" : dv
        }
    print(t)
    if False: #True when run in first time
        torch.save(t, "t0.pt")
    t0 = torch.load("t0.pt")
    for key in ["dq", "dk", "dv"]:
        print(torch.abs(t0[key] - t[key]).max())
```
The reuslt: 
```
...
tensor(3.8147e-06, device='cuda:0', dtype=torch.bfloat16)
tensor(0., device='cuda:0', dtype=torch.bfloat16)
tensor(0., device='cuda:0', dtype=torch.bfloat16)
```

**Comment by tridao** [comment]
The backward is non-deterministic because we use atomic adds. This is expected.

**Comment by t90tank** [comment]
> The backward is non-deterministic because we use atomic adds. This is expected.

Thank you for reply. May I ask if there is any solution? The inability to reproduce the experiment has caused some difficulties for our team.

**Comment by tridao** [comment]
Yes there'll be a "deterministic" option later on (hopefully in 2-3 weeks, but I can't promise). The tradeoff is that it'll be slower (potentially quite a bit slower for long sequences).

**Comment by t90tank** [comment]
> Yes there'll be a "deterministic" option later on (hopefully in 2-3 weeks, but I can't promise). The tradeoff is that it'll be slower (potentially quite a bit slower for long sequences).

Great! Thank you so much. I really appreciate it and I'm looking forward to your solution.

**Comment by t90tank** [comment]
> The backward is non-deterministic because we use atomic adds. This is expected.

Today I find it is also random in flash attention2, is this expected?

**Comment by tridao** [comment]
Yes

**Comment by tridao** [comment]
There's an option for deterministic bwd in v2.4.1.
