### ISSUE TITLE
where can i download this whl file

### ISSUE THREAD

**Issue by forbiddenmouth** [Dao-AILab/flash-attention#455]
running bdist_wheel
      Guessing wheel URL:  https://github.com/Dao-AILab/flash-attention/releases/download/v2.0.7/flash_attn-2.0.7+cu117torch2.0cxx11abiFALSE-cp311-cp311-linux_x86_64.whl
      error: <urlopen error [Errno 110] Connection timed out>

**Comment by tridao** [comment]
I'll add python 3.11 to CI for the next release (probably this week).

**Comment by github-luffy** [comment]
> The newest version (2.0.8) has wheels for python 3.11 now.

flash_attn-2.2.1+cu118torch2.0cxx11abiFALSE-cp310-cp310-linux_x86_64.whl  is ok?

**Comment by tridao** [comment]
Yes.
