### ISSUE TITLE
Why layout in `SmemLayoutAtomVtransposed` has to be kBlockN?

### ISSUE THREAD

**Issue by linbinskn** [Dao-AILab/flash-attention#456]
Hello, amazing performance of flash2~ I am reading the source code and I found that layout in `SmemLayoutAtomVtransposed` has been set as Layout<Shape<Int<kBlockKSmem>, Int<kBlockN>>. However, the reference layout in cutlass 3.0 default_gemm_configuration.hpp is Layout<Shape<Int<kBlockKSmem>, Int<8>>. I have verified the kernel result after replacing kBlockN with 8 and get wrong result. It is so strange and I would like to ask you for the reason of this phenomenon.

**Comment by tridao** [comment]
I don't know tbh. It was trial-and-error. I think it has to do with V being transposed.

**Comment by linbinskn** [comment]
I see, thank you~
