### ISSUE TITLE
What's the difference between  `cxx11abiFALSE`  and  `cxx11abiTRUE` ?

### ISSUE THREAD

**Issue by janelu9** [Dao-AILab/flash-attention#457]

**Comment by tridao** [comment]
You can read about it [here](https://discuss.pytorch.org/t/as-i-downloaded-libtorch-i-have-two-choices-pre-cxx11-abi-and-cxx11-abi-the-question-is-that-what-is-the-difference-between-them/159473).
Some Pytorch wheels are compiled with `-D_GLIBCXX_USE_CXX11_ABI=0` (e.g. downloaded from pytorch.org), some are compiled with `-D_GLIBCXX_USE_CXX11_ABI=1` (e.g. from nvcr docker image). FlashAttention is a Pytorch extension so we have 2 different wheels with 2 options, and will download whichever option that is compatible with the local Pytorch version by checking `torch._C._GLIBCXX_USE_CXX11_ABI`.
