### ISSUE TITLE
Flash attention cannot be fully leveraged with use_cache during inference

### ISSUE THREAD

**Issue by siddartha-RE** [Dao-AILab/flash-attention#466]
I am working on patching Llama to use Flash attention. As expected it is working well for training but I am running into one limitation that makes it hard to leverage fully for usage during generation at inference time. I wanted to leverage Flash attention for doing the reduced computation of just computing attention for the new query tokens against the full set of past and current kv tokens. However, because of how flash-attn interprets the causal mask arg this does not work

```
First pass - Works fine
q: 1 2 3 4
k: 1 2 3 4

Second pass
q.          5 6 7 8
k.  1 2 3 4 5 6 7 8

Flash attn treats this as
q: 1 2 3 4
k: 1 2 3 4 5 6 7 8
```

I would think that when causal=True it would make sense to by default treat the query and key as right aligned. In the PR linked below I have added an implementation where I just left pad the query sequence with zeros to achieve the same result. Except it ends up doing a lot of throw away computation (in the common case new q tokens << cached kv tokens)

Alternately to keep it flexible perhaps the varlen methods could accept an optional query offset parameter that would shift the first index for the purpose of causality enforcement. If either of these seem reasonable I am happy to take a crack at a PR.

Please see this PR to see the issue and workaround:
https://github.com/siddartha-RE/FastChat.flashpatch/commit/e2ee3d47e48009691ad43635405e7a8fea3ee3e9

**Comment by tridao** [comment]
I'm planning to change the behavior of "causal=True" when seqlen_q != seqlen_k to do right padding, so that it's more useful during inference.

**Comment by leizhao1234** [comment]
> I am working on patching Llama to use Flash attention. As expected it is working well for training but I am running into one limitation that makes it hard to leverage fully for usage during generation at inference time. I wanted to leverage Flash attention for doing the reduced computation of just computing attention for the new query tokens against the full set of past and current kv tokens. However, because of how flash-attn interprets the causal mask arg this does not work
> 
> ```
> First pass - Works fine
> q: 1 2 3 4
> k: 1 2 3 4
> 
> Second pass
> q.          5 6 7 8
> k.  1 2 3 4 5 6 7 8
> 
> Flash attn treats this as
> q: 1 2 3 4
> k: 1 2 3 4 5 6 7 8
> ```
> 
> I would think that when causal=True it would make sense to by default treat the query and key as right aligned. In the PR linked below I have added an implementation where I just left pad the query sequence with zeros to achieve the same result. Except it ends up doing a lot of throw away computation (in the common case new q tokens << cached kv tokens)
> 
> Alternately to keep it flexible perhaps the varlen methods could accept an optional query offset parameter that would shift the first index for the purpose of causality enforcement. If either of these seem reasonable I am happy to take a crack at a PR.
> 
> Please see this PR to see the issue and workaround: [siddartha-RE/FastChat.flashpatch@e2ee3d4](https://github.com/siddartha-RE/FastChat.flashpatch/commit/e2ee3d47e48009691ad43635405e7a8fea3ee3e9)

Sorry, i have one question, why in the second pass, there are 4 tokens in query? Usually, shouldn't the query only contain one token?

**Comment by siddartha-RE** [comment]
> Sorry, i have one question, why in the second pass, there are 4 tokens in query? Usually, shouldn't the query only contain one token?

Oh that was just to clarify the issue. During generation there is generally only one new token per call but that does not have to be the case. It is quite possible to have a generation strategy that passes more than one token.

**Comment by tridao** [comment]
This is now implemented.
