### ISSUE TITLE
The scenario is the inference optimization implementation when q is 1

### ISSUE THREAD

**Issue by donglc20** [Dao-AILab/flash-attention#476]
hi dao ,I have a issue.
now， inference wil split kv at hidden size dimension and sent them to different blocks. so that every block need to calculate qkv which shape like [seq_len , 1] .
so can flash attention V2 add a circulation at outside?
there will be three circulations in inference.
h :hidden size
s : context length
q is [1, h]; k is [s, h] ; v is [s, h]
for i in h:
    load q , k , v from HBM and split into different block ,  so  br will be M/4, if s <= br,  load qkv into SRAM , else, load qkv[:br+1] into SRAM
     for j in q:
         .....
         for k in k,v:
             ....
in inference q circulation will only happen once.
if s <= br   , kv circulation will only happen once. else just like flash attention v2 did.

**Comment by donglc20** [comment]
Is it feasible? and is there a significant gap between your expected revision ideas and yours? @tridao

**Comment by tridao** [comment]
There's inference optimization in the work, we hope to release next week or the week after.

**Comment by shiqingzhangCSU** [comment]
It sounds like this release will improved inference. Is there any progress?


> There's inference optimization in the work, we hope to release next week or the week after.

**Comment by tridao** [comment]
Yes. Code is actually ready, blogpost will be out soon.
