### ISSUE TITLE
Question with masking in Flash-Attention when query and key lengths differ

### ISSUE THREAD

**Issue by JinuJeong** [Dao-AILab/flash-attention#481]
I noticed that the masking operation performed before the softmax in the self-attention mechanism might not be handling the case when the query and key lengths differ. Based on my understanding, the masking needs to be adjusted according to the differing lengths of the query and key.

Could you please verify if this is indeed the case? If so, it seems like there might be an issue in the current implementation.
https://github.com/Dao-AILab/flash-attention/blob/main/csrc/flash_attn/src/softmax.h#L159

Looking forward to your feedback.

**Comment by tridao** [comment]
Yup, I'm gonna push some changes tomorrow to address this case.

**Comment by JinuJeong** [comment]
Thank you for your reply. I am looking forward to it.

**Comment by siddartha-RE** [comment]
Funny, all of a sudden it seems like there is a lot of interest in this support!

https://github.com/Dao-AILab/flash-attention/issues/466
https://github.com/Dao-AILab/flash-attention/issues/476

**Comment by tridao** [comment]
This is now implemented.
