### ISSUE TITLE
triton version:  RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Codesticker** [Dao-AILab/flash-attention#500]
I run my training using the flash_attn_func in flash_attn_triton.py and this problem occurred. My language model has head dim of 128 and head num of 32. My query seq length and key seq length are equal. I don't think this is due to OOM because it only took up 56G in each of  80G A100 GPU when this error happened. My seq length is 4096 and this only happens when the batch size is larger than 2.
![image](https://github.com/Dao-AILab/flash-attention/assets/84182788/7e47ce49-149b-4525-b04b-55b2f6372ea0)

**Comment by tridao** [comment]
I'm not sure what the issue is. The Triton implementation is experiment and not actively maintained. You can play around with it (it's just a self-contained Python file). Lmk if you find the issue.

**Comment by Codesticker** [comment]
@tridao Thanks. I use it because I have the alibi bias in my network. Hope the cuda version for  alibi bias is coming soon.

**Comment by wangjingyeye** [comment]
I have the same problem, my sequence length is 8192, batch size is 1 and head dimension is 128. May I ask if this is caused by insufficient memory in SRAM? What should I do?

**Comment by tridao** [comment]
> I have the same problem, my sequence length is 8192, batch size is 1 and head dimension is 128. May I ask if this is caused by insufficient memory in SRAM? What should I do?

I'm not sure about the problem. Can you run just the attention part to make sure that's the issue?

**Comment by tridao** [comment]
Alibi is supported in FlashAttention as of v2.4.0
