### ISSUE TITLE
What is the difference between gpt2_non_optimized and gpt2_optimized in tests？

### ISSUE THREAD

**Issue by qingwan7** [Dao-AILab/flash-attention#503]

**Comment by tridao** [comment]
As shown in the code, gpt2_optimized has these optimizations enabled:
```
    config.use_flash_attn = True
    config.fused_bias_fc = True
    config.fused_mlp = True
    config.fused_dropout_add_ln = True
    config.residual_in_fp32 = True
```

**Comment by qingwan7** [comment]
Why is test_gpt2_optimized slower than test_gpt2_non_optimized? Is it normal?

**Comment by tridao** [comment]
It's testing correctness, not speed. The tests are also running other stuff. It doesn't measure speed.

**Comment by qingwan7** [comment]
But surely these operations such fused should speed up the inference of the model?

**Comment by tridao** [comment]
Yes, you can also write your own benchmark to measure the speed. You shouldn't rely on how long the tests take to finish.

**Comment by qingwan7** [comment]
Get,Thank you very much!
