### ISSUE TITLE
[Question] Which version of FlashAttention-1 is used in the benchmarking of FlashAttention-2's paper?

### ISSUE THREAD

**Issue by umiswing** [Dao-AILab/flash-attention#505]
Hello! [FlashAttention-2's paper](https://arxiv.org/pdf/2307.08691.pdf) reports that FlashAttention-2 is around 2× faster than FlashAttention-1. However, I remember in some versions of FlashAttention-1, parallelizing over the sequence length dimension has been implemented. So I want to know which version of FlashAttention-1 is used in the benchmarking of FlashAttention-2's paper.

**Comment by tridao** [comment]
It's the newest v1 version (v1.0.9).

**Comment by umiswing** [comment]
Thanks!
