### ISSUE TITLE
Why n_positions cannot be set?

### ISSUE THREAD

**Issue by redagavin** [Dao-AILab/flash-attention#510]
The first screenshot is the GPT2Config I used to initialize a gpt model with flash-attn.
The secon screenshot is the output of `print(model.config)`
I set n_positions to 2048, but it becomes 0 after model is initialized.
![image](https://github.com/Dao-AILab/flash-attention/assets/39891180/6029e894-d6ab-4930-a6e1-39bf4f8f4af1)
![image](https://github.com/Dao-AILab/flash-attention/assets/39891180/9a053b9d-8e88-4ec3-b0e2-cb93c1c03488)

**Comment by tridao** [comment]
Because `max_position_embeddings=0`. You can read the code in `gpt.py`.
