### ISSUE TITLE
Question about tensor scores_max in kernel code

### ISSUE THREAD

**Issue by PeterBaelish** [Dao-AILab/flash-attention#513]
Flash-attention is a great work! When I was reading the kernel code, I felt a little confused about the size of the tensor scores_max, [here ](https://github.com/Dao-AILab/flash-attention/blob/main/csrc/flash_attn/src/flash_fwd_kernel.h#L273) exactly. My understanding is scores_max corresponds to m<sub>i</sub> in paper, so the size is R<sup>B<sub>r</sub></sup>. But the code is 2*size<1>(acc_o), it seems the size is R<sup>2B<sub>r</sub></sup>. Why the size in code is twice larger? Do I misunderstand your code? Thanks for your reply!

**Comment by tridao** [comment]
acc_o has shape (4, B_r / 2, B_c / 2) since that's the layout of the accumulator for the mma (tensor core) instruction. So 2 * size<1>(acc_o) = B_r.

**Comment by PeterBaelish** [comment]
I understand. Thank you very much!
