### ISSUE TITLE
 what tools you used to create the Figure 1?

### ISSUE THREAD

**Issue by Seauagain** [Dao-AILab/flash-attention#514]
Dear authors,
I'm writing to compliment you on the excellent images in your article. The visuals were very striking and enhanced the information you presented. I was wondering if you might be able to share **what tools you used to create fig.1** ?

**Comment by tridao** [comment]
Thanks! 
For the FlashAttention v1 paper, Fig 1 was from Adobe Illustrator.
For FlashAttention v2 tech report, Fig 1 was from Powerpoint.
