### ISSUE TITLE
from flash_attn.ops.triton.rotary import apply_rotary doesn't exist anymore

### ISSUE THREAD

**Issue by gikok** [Dao-AILab/flash-attention#518]
This import fails because `ops.triton.rotary` does not exist anymore.

I removed the import statement from `flash_attn.layers.rotary.py ` and replaced `apply_rotary()` with `apply_rotary_emb()` that was defifned in the same file. It seems to have worked.

**Comment by tridao** [comment]
Should be fixed in v2.2.0 (might take CI 9-10 hours to finish compiling all the CUDA wheels).

**Comment by gikok** [comment]
Awesome :)
