### ISSUE TITLE
Does flash attention not support v100 ?

### ISSUE THREAD

**Issue by empty2enrich** [Dao-AILab/flash-attention#524]
When using it, a problem occurs:

**GPU with CUDA capability 7 0 is not supported！**

**Comment by tridao** [comment]
No V100 isn't supported.

**Comment by shanguanma** [comment]
will it be support V100 in the future? Have you any plan for this?

**Comment by tridao** [comment]
No I don't have bandwidth for V100. We welcome community contributions.

**Comment by tmm1** [comment]
You could use xformers for V100 support

**Comment by shanguanma** [comment]
> You could use xformers for V100 support

Thanks for your reply, your means that xformers's flash_attention support V100 gpu?
