### ISSUE TITLE
 CUDA extension of layer_norm for 16k length

### ISSUE THREAD

**Issue by ShomyLiu** [Dao-AILab/flash-attention#537]
Firstly, thanks a lot for your Flash Attention. It has significantly helped our project.

I am interested in utilizing the RMSNorm ops and noticed that this requires the CUDA extensions for layer norm located in csrc/layer_norm/. However, the current implementation supports sequences up to only 8k in length.

Would it be possible to extend the capability to accommodate 16k sequence lengths? 

Thanks again.

**Comment by tridao** [comment]
It supports all sequence lengths. The limitation is in the hidden dimension.

**Comment by ShomyLiu** [comment]
Oh, I see, thanks. I initially misunderstood the README.
