### ISSUE TITLE
No performance boost with extra linear layers

### ISSUE THREAD

**Issue by garrett4wade** [Dao-AILab/flash-attention#538]
Hi, thanks for releasing this amazing repo!

While I can indeed reproduce the performance boost of the attention function, the performance drops as "slow" as PyTorch when I tried to add projection layers before and after the attention. The full benchmarking code is here: https://github.com/garrett4wade/attn_layer_test/blob/main/main.py.

## Environment

+ PyTorch NGC 23.08 docker image with the latest `flash_attn` installed via `pip3 install flash-attn --no-build-isolation`.
+ The GPU is a PCIe A100 80G.
+ `nvidia-smi` gives "Driver Version: 535.54.03 CUDA Version: 12.2".

## Reproduce the results

By running `python3 main.py`, the output is something like
```
flash-func - Forward + Backward pass
  3.61 ms
  1 measurement, 100 runs , 16 threads
torch-func - Forward + Backward pass
  28.78 ms
  1 measurement, 100 runs , 16 threads
flash-layer - Forward + Backward pass
  33.58 ms
  1 measurement, 100 runs , 16 threads
torch-layer - Forward + Backward pass
  33.62 ms
  1 measurement, 100 runs , 16 threads
```

The descriptor `*-func` indicates that given q, k, and v, only the attention function is performed to compute the attention score, while the descriptor `*-layer` indicates that the code runs a standard attention layer, with two linear and dropout layers added to produce qkv and project to a new hidden state.

The results of attention function is expected and aligns with the benchmark results of `benchmarks/benchmark_causal.py`. However, the performance boost seems to disappear with additional linear layers. Why is this happening? Is it expected?

**Comment by tridao** [comment]
That doesn't make sense. You should check that FlashAttention is actually running :D
Attention layer time is: inner attention time + projection time. You're saying inner attention time is much faster, and projection is using the same code, so presumably projection time is the same.

**Comment by garrett4wade** [comment]
Thank you for your response! I found that it is due to a ridiculous mistake made by me 😅 The actual fwd+bwd time of a flash-attention-layer should be about 8.5ms in my environment.

Closing this issue.

**Comment by cv-small-snails** [comment]
@garrett4wade I encountered the same problem， can you tell me what your problem is? how did you solve it？

**Comment by garrett4wade** [comment]
> @garrett4wade I encountered the same problem， can you tell me what your problem is? how did you solve it？


Hi, as Tri said, you may need a double-check to ensure that your code actually invokes the flash-attn function.

**Comment by cv-small-snails** [comment]
Thank you for your response! I found my mistake！
