### ISSUE TITLE
Question: unsupport type `5120BFloat16FloatFloatFloatFloat`

### ISSUE THREAD

**Issue by LZY-the-boys** [Dao-AILab/flash-attention#549]
When I set torch_dtype=bfloat16, it occurs it don't support `5120BFloat16FloatFloatFloatFloat`. What does this mean?  The readme said it supports `Datatype fp16 and bf16 (bf16 requires Ampere, Ada, or Hopper GPUs).`
```
<class 'RuntimeError'> FWD: Unsupported hidden_size or types: 5120BFloat16FloatFloatFloatFloat
> /home/xx/miniconda3/envs/lla/lib/python3.9/site-packages/flash_attn/ops/layer_norm.py(33)_dropout_add_layer_norm_forward()
-> zmat, xmat, dmask, mu, rsigma = dropout_layer_norm.dropout_add_ln_fwd(
```

**Comment by tridao** [comment]
bf16 input should work. The error message means that if weight_dtype=bf16, input_dtype=fp32, residual_dtype=fp32, output_dtype=fp32, then it's not supported.
So you'd need to cast input to bf16 if you want to use weight_dtype=bf16.

Personally I keep weights in fp32 and inputs in bf16.
