### ISSUE TITLE
Questions about dropout_add_rms_norm

### ISSUE THREAD

**Issue by yingtongxiong** [Dao-AILab/flash-attention#554]
Hello, I want to use the function in [here](https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/ops/rms_norm.py#L20). However, I do not know the meanings and dtype of these parameters. For example, the second parameters residual, is it a bool value? I send a bool value and met some bugs. At the same time, I want to know whether this function fused the dropout, residual and rms norm together? Can I use it to replace my function as following.
def _dropout_and_norm_attn(_hidden_states):
        _dropped = self.dropout1(_hidden_states)
        _residual = _dropped
        _hidden_states = self.norm1(_residual.float())
        return _residual, _hidden_states
if it does, how can I adopt my code? Maybe, it is better to give some explanations for these parameters. Looking forward for your reply.

**Comment by tridao** [comment]
You can look at the tests [here](https://github.com/Dao-AILab/flash-attention/blob/main/tests/ops/test_dropout_layer_norm.py) and how it's used [here](https://github.com/Dao-AILab/flash-attention/blob/364a5b4a71203b9977def9829a5c1a6af45468c8/flash_attn/modules/block.py#L126C11-L126C11).
It fuses:
```
dropped = self.dropout1(hidden_states)
residual = (dropped + residual) if residual is not None else dropped
hidden_states = self.norm1(residual)
```

**Comment by yingtongxiong** [comment]
Okay, thank you very much.

**Comment by yingtongxiong** [comment]
Another question about pre_norm. I found that if I set pre_norm is True, the function will return a tuple, which means (hidden_states, residual)?

**Comment by tridao** [comment]
Yes that's right, that's how it's used [here](https://github.com/Dao-AILab/flash-attention/blob/364a5b4a71203b9977def9829a5c1a6af45468c8/flash_attn/modules/block.py#L139).
