### ISSUE TITLE
PR #465 #446 breaks Python <= 3.8

### ISSUE THREAD

**Issue by icyblade** [Dao-AILab/flash-attention#560]
## Description
In #465 and #446, subscription on `dict`/`list` are introduced in `state_dict: dict[str, torch.Tensor]` and `def state_dicts_from_checkpoint(checkpoint_path: Union[str, os.PathLike], model_name: str) -> list[dict]:`

However, this is a new feature in Python 3.9: [Type Hinting Generics in Standard Collections](https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections).

In Python 3.7 and 3.8, `TypeError` will be raised when encountering this file path.

## Repro
`python -c 'from flash_attn.models.llama import remap_state_dict_meta_llama'` gives:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<REDACTED>/python3.8/site-packages/flash_attn/models/llama.py", line 18, in <module>
    state_dict: dict[str, torch.Tensor], config: GPT2Config
TypeError: 'type' object is not subscriptable
```

## Scope
This issue affects `flash-attn>=2.0.8` including `main` branch.

**Comment by tridao** [comment]
Thanks for the report. I'm not super knowledgeable about Python type hinting :D 
Do you know how it should be fixed?
