### ISSUE TITLE
Attention Map

### ISSUE THREAD

**Issue by HSquare2** [Dao-AILab/flash-attention#561]
Hi, thanks for this amazing work! 
Here is a question about the attention map in MHA. I want to do some visualization work after training, how to get the attention map for each head?

**Comment by tridao** [comment]
FlashAttention doesn't return the attention probability matrix (the point is to avoid extra memory reading/writing). You can just run standard attention after training to get the attention map. FlashAttention and standard attention are compatible (they give the same outputs up to numerical precision).
