### ISSUE TITLE
Local attention with two-sided window (non-causal)

### ISSUE THREAD

**Issue by samvanstroud** [Dao-AILab/flash-attention#576]
Hi! 

Thanks for adding causal local attention (left)! Would it be possible to support local attention with both `window_size_left > 0` and `window_size_right > 0` (right)? For the case where `window_size_left == window_size_right`.

This would be incredibly useful for large input sets where causality is not requred.

Many thanks.

<img width="300" alt="Screenshot 2023-09-27 at 18 07 19" src="https://github.com/Dao-AILab/flash-attention/assets/16232199/c0f874af-4843-43c8-ac4d-c7ef2f233ad2">
<img width="300" alt="Screenshot 2023-09-27 at 18 05 30" src="https://github.com/Dao-AILab/flash-attention/assets/16232199/81828e38-cb99-4d74-9012-3c06bf62763e">

**Comment by tridao** [comment]
It's already supported. You can just pass in `window_size=(3, 3)` for the example on the right.

**Comment by samvanstroud** [comment]
Great thank you for the clarification. I read the `or` [here](https://github.com/Dao-AILab/flash-attention/blob/083e8f525f1f8e1dde5044afdac79f9588302207/csrc/flash_attn/flash_api.cpp#L110) as exclusive.
