### ISSUE TITLE
Is there a good place to see a support matrix of what head dimensions are supported on various architectures?

### ISSUE THREAD

**Issue by parthmannan** [Dao-AILab/flash-attention#579]
It would be great if there was a central location where support for various head dimensions was documented against different architectures (A40, A100, H100 etc.)

**Comment by tridao** [comment]
It's in the README
"FlashAttention-2 currently supports:
- Ampere, Ada, or Hopper GPUs (e.g., A100, RTX 3090, RTX 4090, H100).
- All head dimensions up to 256. Head dim > 192 backward requires A100/A800 or H100/H800"

**Comment by parthmannan** [comment]
My apologies for missing that. Thanks for the prompt response! Closing this.
