### ISSUE TITLE
FA2 + Triton DSL

### ISSUE THREAD

**Issue by david-macleod** [Dao-AILab/flash-attention#582]
Hi, I was curious if the Triton implementation of FA2 is being actively maintained (here or anywhere else)? The comments suggests the forward at least has comparable performance to the CUDA implementation under certain conditions,

https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/flash_attn_triton.py

**Comment by tridao** [comment]
I haven't touched it in a while. You should also refer to the tutorial on Triton [repo](https://github.com/openai/triton/blob/main/python/tutorials/06-fused-attention.py).

**Comment by david-macleod** [comment]
Thanks!
