### ISSUE TITLE
would 2.0 support 2080?

### ISSUE THREAD

**Issue by laoda513** [Dao-AILab/flash-attention#588]
Just curious is the support of 2080 still in the plan? Thanks

**Comment by laoda513** [comment]
Just curious is the support of 2080 still in the plan? Thanks

**Comment by tjbortz1s** [comment]
There are a few open issues about this:

https://github.com/Dao-AILab/flash-attention/issues/542

Is the big one with talk about "turing" support (turing = 2080)

But there is a second currently open as well.

https://github.com/Dao-AILab/flash-attention/issues/562

**Comment by tridao** [comment]
Yeah it'll just take some time.

**Comment by laoda513** [comment]
thanks！
