### ISSUE TITLE
Do you have perf benchmarks for much shorter lengths ?

### ISSUE THREAD

**Issue by vince62s** [Dao-AILab/flash-attention#591]
like sequence length of: 64, 128, 256 tokens

if not, what should be expected (ballpark numbers) in terms of speedup and memory reduction.

thanks

**Comment by tridao** [comment]
I don't have the numbers off the top of my head, you can run the [benchmark](https://github.com/Dao-AILab/flash-attention/blob/main/benchmarks/benchmark_flash_attention.py).

**Comment by vince62s** [comment]
FYI I added PT2 scaled_dot_product (flash 1? difficult to say) but there is a sweet spot around 150-200 tokens for which flash2 speed is the same as scaled_dot_product. For shorter sequences, scaled_dot_product is faster.

**Comment by tridao** [comment]
Thanks! I haven't run the benchmark myself but that probably makes sense. It might come down to the choice of block sizes. FA1 uses block size 16x256 for headdim 64 and 16 x 128 for headdim 128. FAv2 uses block size 128x128 for headdim 64 and 128 x 64 for headdim 128.
If seqlen <= 256 things might just fit in 1 block for FA1 and that might simplify things.
