### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by autumn-moon-py** [Dao-AILab/flash-attention#592]
torch
```
torch                         2.1.0+cu118
torchaudio                    2.1.0+cu118
torchvision                   0.16.0+cu118
packaging                     23.2
ninja                         1.11.1
```
cuda version 11.8
python version 3.11.5
ninja version 1.11.1

[log.txt](https://github.com/Dao-AILab/flash-attention/files/12823213/log.txt)

**Comment by tridao** [comment]
I've just clarified in the README that Windows is not supported. If you have ideas on how to modify the code to support Windows, we'd love to get help there.

**Comment by autumn-moon-py** [comment]
sorry
