### ISSUE TITLE
Flash-attention Installation Failed 

### ISSUE THREAD

**Issue by smth-27** [Dao-AILab/flash-attention#597]
Trying to run: pip install flash-attn --no-build-isolation
System build:
Cuda : 12.2
Linux : Ubuntu 20.04
Python : 3.10.12
Pytorch : 2.0.1+cu117
pip : 23.2.1

pip install flash-attn --no-build-isolation

Defaulting to user installation because normal site-packages is not writeable
Collecting flash-attn
  Using cached flash_attn-2.3.1.post1.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2m2j8ref/flash-attn_c35a1707629840c39ad89958b7891230/setup.py", line 117, in <module>
          raise RuntimeError(
      RuntimeError: FlashAttention is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.
      
      
      torch.__version__  = 2.0.1+cu117
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by tridao** [comment]
Do you have nvcc? 
From the error message: "make sure nvcc has a supported version by running nvcc -V."

**Comment by smth-27** [comment]
Thanks for your reply @tridao 
 nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

**Comment by tridao** [comment]
We need nvcc 11.6 or above for installation.

**Comment by SingL3** [comment]
@tridao I have the same issue here and my nvcc is 11.8:
```
Building wheels for collected packages: flash-attn
  Building wheel for flash-attn (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      fatal: not a git repository (or any of the parent directories): .git


      torch.__version__  = 2.0.1+cu118


      running bdist_wheel
      Guessing wheel URL:  https://github.com/Dao-AILab/flash-attention/releases/download/v2.3.1.post1/flash_attn-2.3.1.post1+cu118torch2.0cxx11abiFALSE-cp39-cp39-linux_x86_64.whl
      error: Remote end closed connection without response
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash-attn
  Running setup.py clean for flash-attn
Failed to build flash-attn
ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects
```
nvcc:
```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by tridao** [comment]
I just `wget https://github.com/Dao-AILab/flash-attention/releases/download/v2.3.1.post1/flash_attn-2.3.1.post1+cu118torch2.0cxx11abiFALSE-cp39-cp39-linux_x86_64.whl` and it works.

**Comment by Julianvaldesv** [comment]
I have the same issue, I run the wget you suggested above , but still same error when I run pip install flash-attn.       error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin\\nvcc' failed with exit code 4294967295
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash_attn
  Running setup.py clean for flash_attn
Failed to build flash_attn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (flash_attn)
PS C:\Users\15023\Documents\Models\Florence> 

C:\Users\15023>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by AryaK19** [comment]
> I have the same issue, I run the wget you suggested above , but still same error when I run pip install flash-attn. error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc' failed with exit code 4294967295 [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for flash_attn Running setup.py clean for flash_attn Failed to build flash_attn ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (flash_attn) PS C:\Users\15023\Documents\Models\Florence>
> 
> C:\Users\15023>nvcc -V nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2022 NVIDIA Corporation Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022 Cuda compilation tools, release 11.8, V11.8.89 Build cuda_11.8.r11.8/compiler.31833905_0

did you solved it ?

**Comment by mcskware** [comment]
In case others find this, here's one more thing you can try:

I was able to resolve this by first fully upgrading torch (it had been using a cached, older torch install). I used: `pip install --upgrade torch` and then the `flash_attn` install proceeded without error.

**Comment by Rain1213** [comment]
pip install wheel
pip install flash-attn --no-build-isolation --no-cache-dir


worked for me.

**Comment by ould-amine** [comment]
Hi,
I'm trying to install flash-attn (v2.8.1) on a cluster system with:

- Python 3.10

- PyTorch 2.5.1 + CUDA 11.8 (installed via conda)

- nvcc version 12.9


I install via:

`pip install --no-build-isolation flash-attn`

But the build fails at the wheel stage:

> Building wheel for flash-attn (setup.py): finished with status 'error'
> Failed to build flash-attn
> ERROR: Failed to build installable wheels for some pyproject.toml based projects


Later, when trying to import:
`import flash_attn_2_cuda`

I get:

> ModuleNotFoundError: No module named 'flash_attn'


Has anyone faced a similar issue? Could this be related to the CUDA version or PyTorch mismatch?

Any suggestion appreciated (maybe @tridao ?).

Thanks!
