### ISSUE TITLE
cannot find -lcuda

### ISSUE THREAD

**Issue by lkluo** [Dao-AILab/flash-attention#599]
Successfully install it but got this error when running the model.

<img width="1023" alt="image" src="https://github.com/Dao-AILab/flash-attention/assets/26020832/18d93596-dfa6-49d3-a56d-9baccae8ed46">

**Comment by tridao** [comment]
You should use triton 2.1.0.

**Comment by lkluo** [comment]
@tridao thanks for the prompt reply. upgraded triton to 2.1 but the error still persists.
<img width="925" alt="image" src="https://github.com/Dao-AILab/flash-attention/assets/26020832/42f9b3b1-955b-417b-97c9-d47f7b611b0d">

**Comment by tridao** [comment]
You'll also need to run `ldconfig` before running the script so that it cna find cuda.so.

**Comment by lkluo** [comment]
@tridao Still not able to get it work. I did the following step by step:
- run `ldconfig`
- install package from source `python3 setup.py install`

the error is same as above.

**Comment by tridao** [comment]
I run `ldconfig` before running the triton code. This is more of a triton issue. I'm not sure what else to fix.

**Comment by ShinyWey** [comment]
> I run `ldconfig` before running the triton code. This is more of a triton issue. I'm not sure what else to fix.

You can try:

1. Adding the following content to the .bashrc file:

```
export LIBRARY_PATH="/usr/local/cuda/lib64/stubs:$LIBRARY_PATH"
```

2. Sourcing the .bashrc file.
```
source .bashrc
```
