### ISSUE TITLE
Wheel for CUDA 12.1 for releases 2.2.3 onwards

### ISSUE THREAD

**Issue by rishsriv** [Dao-AILab/flash-attention#602]
Thank you for the incredible work on Flash Attention and FA2!

I noticed that wheels for CUDA12.1 have been missing after v2.2.2. Would you happen to know how to add these back in?

Thank you!

**Comment by tridao** [comment]
It's because of nvcc 12.1 segfaults when compiling the code. If you're on CUDA 12.1, setup.py will automatically download wheel for 12.2 and use that (it's compatible).

**Comment by rishsriv** [comment]
Sweet, thank you!
