### ISSUE TITLE
FlashAttention actual test speed comparison

### ISSUE THREAD

**Issue by nanmi** [Dao-AILab/flash-attention#607]
I found that in the FasterTransformer framework, after using FlashAttention and not using FA, the speed did not improve particularly quickly, and the acceleration was not obvious when the prompt length was short, but the acceleration was more obvious when the prompt length was longer.

**Comment by nanmi** [comment]
Is the following conclusion that I have drawn correct?
* The essence is hardware acceleration and softmax acceleration optimization of matrix multiplication and addition, but when seqlen is small, the matrix size is small, and the intermediate result of the matrix is read and written directly from global memory, which is not much different from the matrix multiplication and addition optimized by block, so when batch_size x  seqlen is larger, the acceleration effect will be obvious.

**Comment by tridao** [comment]
For short sequence length, attention doesn't take much time relative to the other parts of the model, so speeding up attention will not change end-to-end speed much. For long sequence length, attention takes more time relatively, so attention speedup is more noticable.
