### ISSUE TITLE
Question about Number of Splits in Flash-Decoding Technique

### ISSUE THREAD

**Issue by JinuJeong** [Dao-AILab/flash-attention#609]
Hi there,

First off, I want to thank you for this incredible project. I've been exploring the codebase and I'm particularly interested in understanding the flash-decoding technique more deeply.

While going through the code, I noticed that the flash-decoding process accepts a parameter for the number of splits. I'm curious about the design decision behind this. Specifically, why does the kernel split keys and values based on the predetermined number of splits, regardless of the sequence length? Is there a specific optimization or computational advantage in doing this?

Thank you in advance for your time and help.

**Comment by tridao** [comment]
By default, splits=0, and we use a heuristic to determine the number splits. This heuristic depends on the GPU, batch size, and number of heads.
Each GPU has many streaming multiprocessors (SMs) working in parallel. E.g. A100 has 108 SMs. We want enough parallel work to use most of these SMs. For example, if batch=1 and nheads=12, and if we have 9 splits along the seqlen dimension, then we would have 12 x 9 = 108 pieces of parallel work for all the 108 SMs, and we're fully utilizing the GPU.
On H100 SXM there are 132 SMs (and H100 PCIe has 114 SMs), so it would be better to increase the number of splits to maybe 11 for H100 SXM.

**Comment by JinuJeong** [comment]
I appreciate the quick response.  I noticed a heuristic for determining the number of splits. I'm curious about its behavior when the batch size x nheads exceeds the number of SMs. In this scenario, does the split method still have an effect or impact on the decoding process?

**Comment by tridao** [comment]
In that case the heuristic will pick num_splits=1, i.e. no splitting.

**Comment by JinuJeong** [comment]
Okay, thank you.

**Comment by Birdylx** [comment]
@tridao @JinuJeong , hi, how can I use flash decoding? I didn't find any interface for it?

**Comment by tridao** [comment]
You just have to call FlashAttention as usual, it will dispatch to flash decoding for short seqlen_q and long seqlen_k. You can also use the function `flash_attn_with_kvcache` function as mentioned in the README.

**Comment by 500kg** [comment]
I have a question about seqlenq_ngroups_swapped.
For A100 which has 108 SMs, if batch=1 and nheads=12, we should have 9 splits along the seq_k dimension. But if seq_q is 1, this might trigger seqlenq_ngroups_swapped to be TRUE. In this case, nheads turn into num_heads_k, which might be 2. So num_splits might be larger than 9, leading to larger use of SM. Is this behavior by design?

**Comment by tridao** [comment]
> I have a question about seqlenq_ngroups_swapped. For A100 which has 108 SMs, if batch=1 and nheads=12, we should have 9 splits along the seq_k dimension. But if seq_q is 1, this might trigger seqlenq_ngroups_swapped to be TRUE. In this case, nheads turn into num_heads_k, which might be 2. So num_splits might be larger than 9, leading to larger use of SM. Is this behavior by design?

The number of splits is chosen by some heuristic, which probably works well for some cases but not all. Are you saying there's a case where the heuristic doesn't work well? Can you benchmark by passing in nsplits?

**Comment by 500kg** [comment]
> > I have a question about seqlenq_ngroups_swapped. For A100 which has 108 SMs, if batch=1 and nheads=12, we should have 9 splits along the seq_k dimension. But if seq_q is 1, this might trigger seqlenq_ngroups_swapped to be TRUE. In this case, nheads turn into num_heads_k, which might be 2. So num_splits might be larger than 9, leading to larger use of SM. Is this behavior by design?
> 
> The number of splits is chosen by some heuristic, which probably works well for some cases but not all. Are you saying there's a case where the heuristic doesn't work well? Can you benchmark by passing in nsplits?

I appreciate your quick response and I found I have made mistakes about this. For the case when seqlenq_ngroups_swapped is TRUE, the actual grid size should be (num_m_block, num_splits, batch * **num_heads_k**), but I initially thought it was (num_m_block, num_splits, batch * **num_heads**).

**Comment by izhuhaoran** [comment]
@tridao  I am testing flash_attn_with_kvcache and faced num_splits configuration problem. I want to compare the performance of using page attention versus non-page. My call is as follows:
```
# non-page
flash_attn_with_kvcache(
    q=decode_query.unsqueeze(1),            # q: (batch_size, seqlen=1, nheads, headdim)
    k_cache=key_cache,                      # k_cache: (batch_size_cache, max_seqlen_cache, nheads_k, headdim)
    v_cache=value_cache,                    # v_cache: (batch_size_cache, max_seqlen_cache, nheads_v, headdim)
    cache_seqlens=decode_meta.seq_lens_tensor, # cache_seqlens: (batch_size_cache, ) the cur length of each sequence in cache
    cache_batch_idx=decode_meta.cache_batch_idx,
    softmax_scale=self.scale,
    causal=True,
    alibi_slopes=self.alibi_slopes,
    out=output[num_prefill_tokens:].unsqueeze(1),
    num_splits=num_splits,
)
# page
flash_attn_with_kvcache(
    decode_query.unsqueeze(1),      # (batch_size, 1, nheads, headdim]
    key_cache,                                    # (num_blocks, page_block_size, nheads_k, headdim)
    value_cache,
    block_table=decode_meta.block_tables,
    cache_seqlens=decode_meta.seq_lens_tensor,
    softmax_scale=self.scale,
    causal=True,
    alibi_slopes=self.alibi_slopes,
    out=output[num_prefill_tokens:].unsqueeze(1),
    num_splits=num_splits,
)
```

Specifically, I use nvidia H20 GPU(sm nums= 78), batchsize=16, seqlen_q=1, seqlen_k=131072, nheads=16, nheads_kv_cache=2, and when I default num_splits=0, (I think num_splits_heuristic func will choose num_splits=1), the performance of non-page is not good at this time, there is a certain gap compared to page, which is not in line with my expectations, but when I manually changed the num_splits for non-page to 3, There was some improvement in performance, and almost no difference compared to page (num_splits=0), I have read [issue #841](https://github.com/Dao-AILab/flash-attention/issues/841), but I still have the following questions:

- I think excluding some special cases, non-page will be page better performance, I called flash_attn_with_kvcache parameter num_splits=0, batch-size * nheads > sm_nums, num_splits_heuristic func I feel that the recommended num_splits=1 is calculated (maybe I am wrong). Why is page better than non-page? But when I forced page and non-page calls with the parameter num_splits=1, there was no difference, and non-page was slightly better.

- When nheads and nheads_kv_cache are inconsistent, when GQA is involved, num_splits_heuristic func still uses nheads to determine whether there is a problem? Can I use the nheads_cache to choose num_splits?

- I have tried num_splits =3 for non-page, which should be more than sm nums, why is it better than the default num_splits=0? How do I choose the best num_splits in my situation?
