### ISSUE TITLE
support Baichuan2-13B-Chat?

### ISSUE THREAD

**Issue by xuxiangqian** [Dao-AILab/flash-attention#610]
whether support or not Baichuan2-13B-Chat?

**Comment by tridao** [comment]
Does it use Alibi or rotary? If Alibi then it's not supported.

**Comment by DoverDW** [comment]
> whether support or not Baichuan2-13B-Chat?您好，请问有答案了吗

**Comment by DoverDW** [comment]
> whether support or not Baichuan2-13B-Chat?

请问您用baichuan2-chat成功了吗

**Comment by tridao** [comment]
Alibi is supported in FlashAttention as of v2.4.0, so Baichuan2-13B should work.

**Comment by xs1997zju** [comment]
@tridao For Baichuan2-13B, compared to xformers' attention-bias, alibi flash attention doesn't seem to have the significant speed improvement as demonstrated in this document https://pli.princeton.edu/blog/2024/alibi-flashattention-speeding-alibi-3-5x-hardware-efficient-implementation (which mentions a 3.0x speed increase compared to torch’s SDPA/xformers).

**Comment by xs1997zju** [comment]
There seems to be no significant speed improvement on baichuan2-13b.
