### ISSUE TITLE
How can you make sure the dropout_mask  of forward & backward same?

### ISSUE THREAD

**Issue by gaodaheng** [Dao-AILab/flash-attention#612]
I want to know, How can you make sure the dropout_mask  of forward & backward same? Your block and random_seed one-to-one correspondence.

**Comment by tridao** [comment]
It's explained [here](https://github.com/Dao-AILab/flash-attention/blob/02ac572f3ffc4f402e4183aaa6824b45859d3ed3/csrc/flash_attn/src/flash_fwd_kernel.h#L1142).
```
    // We want the fwd and bwd to generate the same dropout pattern (RNG), without restricting
    // them to have the same number of threads or have to traverse the attention matrix
    // in the same order.
    // In the Philox RNG, we use the offset to store the batch, head, and the lane id
    // (within a warp). We use the subsequence to store the location of the 16 x 32 blocks within
    // the attention matrix. This way, as long as we have the batch, head, and the location of
    // the 16 x 32 block within the attention matrix, we can generate the exact same dropout pattern.
```
You can look at the philox RNG [implementation](https://github.com/Dao-AILab/flash-attention/blob/main/csrc/flash_attn/src/philox.cuh) and how it's called [here](https://github.com/Dao-AILab/flash-attention/blob/02ac572f3ffc4f402e4183aaa6824b45859d3ed3/csrc/flash_attn/src/softmax.h#L237).
