### ISSUE TITLE
Why did you choose float32 in softmax?

### ISSUE THREAD

**Issue by gaodaheng** [Dao-AILab/flash-attention#613]
I want to know, why did you choose float32 in softmax part, why not fp16/bf16 instand？

**Comment by tridao** [comment]
Just to be safe on numerical error, since we take the softmax of each block and rescale by some factor which can be quite small. I didn't try, but keep softmax in fp16/bf16 could cause underflow (rounding to zero). I don't think it affects speed much.

**Comment by gaodaheng** [comment]
> Just to be safe on numerical error, since we take the softmax of each block and rescale by some factor which can be quite small. I didn't try, but keep softmax in fp16/bf16 could cause underflow (rounding to zero). I don't think it affects speed much.

I known QK/S maybe exceed the expression range of fp16, but, in some other hardware, if softmax is compute bottleneck？Do you have some proposal，to rescale the input of QK/S for softmax？

**Comment by gaodaheng** [comment]
I known QK/S maybe exceed the expression range of fp16, but, in some other hardware, if softmax is compute bottleneck？Do you have some proposal，to rescale QK/S of the input of softmax？

**Comment by tridao** [comment]
Idk I didn't experiment too much. There are probably ways to rescale. There are 2 things: overflow (does some value exceed the range of fp16 and become inf) and underflow (e.g., some small values might get rounded to zero).

**Comment by gaodaheng** [comment]
Thank you, Do you think underflow may don't make much difference, otherwise gemm comput_type(bf16) may have same affect.

**Comment by tridao** [comment]
I don't really know, maybe it's ok.

**Comment by gaodaheng** [comment]
OK,  Thank you again for your excellent job, it have good performance(in other hardware too) especially in attention_bwd.
