### ISSUE TITLE
Using flash-attention v2 with float32 

### ISSUE THREAD

**Issue by YoelShoshan** [Dao-AILab/flash-attention#622]
The documentation says:

"FlashAttention-2 currently supports: ... **Datatype fp16 and bf16** ..."

If I'm using "standard" float32 - what is the expected behavior?
Is it supported?

(or, is the intention in the text that *within* the lower precision formats that are out there, fp16 and bf16 are the only ones that are currently supported, but it also supports the "basic"/standard float32 format)

**Comment by tridao** [comment]
fp32 is not supported.

**Comment by chricro** [comment]
Hey @tridao do you think fp32 flash-attention2 could give better latency than without flash-attention? cheers mate I appreciate your work
