### ISSUE TITLE
Whether Flash and Flash Attention 2 both support MQA backward pass?

### ISSUE THREAD

**Issue by CanyonWind** [Dao-AILab/flash-attention#623]
Hi, I noticed that it was mentioned that FA supports MQA. Would like to get some understanding of whether FA2 also supports it and whether both FA/FA@ support backward passes of MQA?

This would help a lot with large-scale model training and inference. Thanks a lot!

**Comment by tridao** [comment]
Yes it's supported, both forward and backward.
