### ISSUE TITLE
During training, will flash attention be saved in the computation graph? 

### ISSUE THREAD

**Issue by loredunk** [Dao-AILab/flash-attention#626]
During training, if I add flash attention, will this operation be saved in the computation graph? So that during inference, I can directly call the inference with flash attention included?

**Comment by tridao** [comment]
I don't understand. It's all just pytorch code (calling CUDA kernels). You can choose to run FlashAttention during training or inference.
If you're asking about exporting to ONNX, then that's probably not supported (though I've never tried).
Ultimately it's just doing attention, you can call whichever code to do attention.
