### ISSUE TITLE
MHA contains Nan or Inf weights at initialization

### ISSUE THREAD

**Issue by Amutheezan** [Dao-AILab/flash-attention#628]
I am creating ```MHA``` using following code block, but when I set the data-type to ```torch.float16```, some of the weights are either ```nan``` or ```-/+inf```

att = MHA(
      embed_dim=1,
      num_heads=1,
      dropout=0.0,
      use_flash_attn=True,
      cross_attn=True,
      dtype=torch.float16,
      device="cuda"
)

Are there anything, I am missing here ?

**Comment by tridao** [comment]
I just tried, all the weights and biases are fine. None of them are nan of inf.

**Comment by Amutheezan** [comment]
I was only able to do overwrite the weights manually, but when I do a backward step it again results in nan or inf ? Only thing is, I set rest of the layers to float32 and leave the MHA to float16 and perform the backward pass ? Alternatively I tried all the layers with float16 and do the backward pass but it throws the RuntimeError: Found dtype Half but expected Float

**Comment by tridao** [comment]
You shouldn't need to pass in the dtype.
You should just use pytorch [AMP](https://pytorch.org/docs/stable/amp.html) to do all this dtype conversion automatically.
