### ISSUE TITLE
Does flash-attention support GPUs with the Pascal architecture?

### ISSUE THREAD

**Issue by nj159** [Dao-AILab/flash-attention#629]
Excuse me, do all flash-attention currently only support GPUs with the Ampere architecture? Is there any support for Pascal?

**Comment by tridao** [comment]
No we don't support Pascal.

**Comment by nj159** [comment]
> No we don't support Pascal.

Thank you very much, may I ask, will I make a mistake installing flash_attn-2.3.2+cu116torch1.13cxx11abiFALSE-cp310-cp310-linux_x86_64 in the environment of cuda=11.8?

**Comment by tridao** [comment]
setup.py will download the right wheel. If it detects cuda 11.8 then it should download the wheel for cuda11.8

**Comment by nj159** [comment]
> setup.py will download the right wheel. If it detects cuda 11.8 then it should download the wheel for cuda11.8

excuse me ,i have run the setup.py but output the error:
![image](https://github.com/Dao-AILab/flash-attention/assets/144583677/c38062d8-474a-4616-b3b8-a5b00e95ffd2)


so how can we deal with it?

**Comment by tridao** [comment]
As mentioned in the README, you might want to limit the number of compilation processes by setting `MAX_JOBS`.

**Comment by nj159** [comment]
> As mentioned in the README, you might want to limit the number of compilation processes by setting `MAX_JOBS`.

thank you,i have solved it
