### ISSUE TITLE
Error when running the Tests

### ISSUE THREAD

**Issue by lsl036** [Dao-AILab/flash-attention#630]
Hi Dao,

Thanks for your great work! 

I have installed the flash-attention package 2.3.2, and executed an example found in #410  successfully:
![image](https://github.com/Dao-AILab/flash-attention/assets/34669680/06a82776-7b6d-41e1-a18c-aa51f5ddb621)

Now I want to run the Tests shown in README.
I execute: `pytest -q -s tests/test_flash_attn.py` and the ERRORS occurs:
![image](https://github.com/Dao-AILab/flash-attention/assets/34669680/c36bef1e-3ba7-4f06-9557-12f58b1cd2c8)

Here is my Software environment:
-Python = 3.7.10
-Torch = 1.12.1
-Nvcc and CUDA = 11.7
-Pytest = 7.1.2

I find similar questions in [StackOverflow](https://stackoverflow.com/questions/49582183/pythonl-invalid-syntax-file-fstring-line-1), which says it might be a Python 3.8 compatible way of string formatting. But I have no idea how to locate the bug.

**Comment by lsl036** [comment]
I'm looking forward to any reply from you!

**Comment by tridao** [comment]
Can you try python 3.8?

**Comment by lsl036** [comment]
Yeah, I tried with python 3.9 and it runs smoothly.
But I still suggest this as a compatibility issue to consider, since it will affect py3.7's user testing.

**Comment by lsl036** [comment]
Thank you for the help.
I will close this issue.
