### ISSUE TITLE
Ask for aarch64

### ISSUE THREAD

**Issue by wangxidong06** [Dao-AILab/flash-attention#644]
Can you please release the compiled version for ARM architecture

**Comment by knotgrass** [comment]
flash attention algorithm is designed for nvidia gpu, and depend on it. So compile for Arm architecture is imposible

**Comment by tridao** [comment]
We currently have no plan for FlashAttention on ARM.

**Comment by wangxidong06** [comment]
I have A100 40G GPU but my CPU's architecture is ARM, how can I use FlashAttention

**Comment by tridao** [comment]
Theoretically that should work (only the GPU should matter). I have no experience compiling on ARM CPU however. You can try using the pytorch docker image from [Nvidia](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) which seems to have a version for ARM.
