### ISSUE TITLE
What does True/False mean in a WHL file name?

### ISSUE THREAD

**Issue by kgboyko** [Dao-AILab/flash-attention#652]
flash_attn-2.3.3+cu122torch2.1cxx11abi**TRUE**-cp310-cp310-linux_x86_64.whl

**Comment by tridao** [comment]
It's the c++11abi flag from Pytorch, [here's](https://github.com/Dao-AILab/flash-attention/blob/83aef842beec1037eb8c1d9c3ef3ed8aae80b091/setup.py#L245) how it's used in setup.py.
