### ISSUE TITLE
[Feature Request]: flash decoding++ optimization

### ISSUE THREAD

**Issue by BarfingLemurs** [Dao-AILab/flash-attention#653]
Hello, any thoughts on adding further optimizations such as  https://arxiv.org/abs/2311.01282 flash-decoding++ ?

many users benefit from upstream here to run LLMs, thank you for maintaining this!

**Comment by tridao** [comment]
We welcome PRs :D

**Comment by cableyang** [comment]
flash attention has been a useful tool for llm train and inference, hope the flash decoding++ can release their code ASAP
