### ISSUE TITLE
How to implement example packing with flash_attn v2?

### ISSUE THREAD

**Issue by cwallenwein** [Dao-AILab/flash-attention#654]
Hi Friends 👋
To increase training efficiency, I would like to pack multiple examples into the same input sequence and separate them with EOS tokens. The attention mask will probably have to look like this:
![image](https://github.com/Dao-AILab/flash-attention/assets/40916592/aff969ac-7ec0-4348-9f2c-4eb73283f24a)

Is there a simple way to implement this using flash attention? If yes, how?

**Comment by tridao** [comment]
You can try the `varlen` variants. The QKV will contain embeddings for ['a', 'b, 'c', 'eos', 'd', 'e', 'f', 'eos'] and you pass in cu_seqlens = [0, 4, 8] to tell the function that there are 2 sequences, one from position 0 to 3, and one from position 4 to 7.

**Comment by cwallenwein** [comment]
Okay, thank you very much. Can I also pass multiple samples as a batch? And is there documentation for those functions anywhere?

**Comment by tridao** [comment]
Should be in the [docstring](https://github.com/Dao-AILab/flash-attention/blob/83aef842beec1037eb8c1d9c3ef3ed8aae80b091/flash_attn/flash_attn_interface.py#L843).

**Comment by cwallenwein** [comment]
Okay, so if I have a batch [['a', 'b, 'c', 'eos', 'd', 'e', 'f', 'eos'], ['a', 'eos', 'b', 'eos', 'c', 'd', 'e', 'eos']], cu_seqlens would be [[0,4, 8], [0,2, 4, 8]] but I can't put these values into a tensor. Will it be [[0,4, 8, 8], [0,2, 4, 8]] or [[0,4, 8, -1], [0,2, 4, 8]] or something different?

**Comment by tridao** [comment]
You can just have a batch with 5 examples `['a', 'b, 'c', 'eos'] ['d', 'e', 'f', 'eos'] ['a', 'eos'] ['b', 'eos'] ['c', 'd', 'e', 'eos']`
cu_seqlens = [0, 4, 8, 10, 12, 16].

**Comment by sz128** [comment]
See https://github.com/Dao-AILab/flash-attention/issues/432#issuecomment-1698610752
