### ISSUE TITLE
Performance degradation in recent versions when causal=True

### ISSUE THREAD

**Issue by shcho1118** [Dao-AILab/flash-attention#669]
I recently noticed that the forward function is quite a bit slower (avg -30 tflops/s) when `causal=True` compared to previous versions.
My guess is that this is due to the use of local attention logic in the causal mask in recent versions, but do you have any ideas?
My environment is A10080G, CUDA 11.7, PyTorch 2.0.1 
![benchmark_flash_attention py, headdim=64, causal=True](https://github.com/Dao-AILab/flash-attention/assets/20601334/bbbe1b47-7b3a-4f35-9109-84952e6b12d9)
![benchmark_flash_attention py, headdim=128, causal=True](https://github.com/Dao-AILab/flash-attention/assets/20601334/6ef9b1a6-a69b-4a88-876d-5251375eefb8)

**Comment by tridao** [comment]
Thanks for the report, the speed regression is not intended. We template on causal / not causal and local / not local, so the ideally the speed should be the same as before. I must have done sth wrong then.

**Comment by vgoklani** [comment]
@shcho1118 Thank you for pointing out the speed regression, we noticed the same issue ...

**Comment by MarshtompCS** [comment]
Thank you for the report! I wonder if the issue is sloved in the latest version v2.3.4?

**Comment by tridao** [comment]
Thanks again @shcho1118, it's indeed an issue with local and causal. We were using the "local" implementation when causal=True, which still gives the right result but slightly slower. I've since fixed it in v2.3.5 (might take several hours for CUDA wheels to compile).
Can you test the new version?

**Comment by shcho1118** [comment]
@tridao Yes I'll test with the latest version and share.

**Comment by shcho1118** [comment]
After comparing it with the previous version 2.3.3, the issue seems to be resolved.
Thanks @tridao!
![benchmark_flash_attention py, headdim=64, causal=True (1)](https://github.com/Dao-AILab/flash-attention/assets/20601334/a30d90eb-a687-4bd1-be2a-02f9151bc728)
![benchmark_flash_attention py, headdim=128, causal=True (1)](https://github.com/Dao-AILab/flash-attention/assets/20601334/a9c20733-66aa-4487-b68c-bbcec1248fe0)
