### ISSUE TITLE
Out of bounds CUDA error

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [Dao-AILab/flash-attention#670]
Using compute-sanitizer, I encounter the error that I have distilled into a log I provide. 
[error (1).log](https://github.com/Dao-AILab/flash-attention/files/13342821/error.1.log)

The repro script requires LongLoRA's shifted short attention modifications.
the `llama_attn_replace.py`` file can be found [here](https://github.com/dvlab-research/LongLoRA/blob/b5c6809515d47ef4be34bd86b2074d540a1b897a/llama_attn_replace.py).

```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from datasets import load_dataset
from torch.utils.data import DataLoader
from transformers import AutoModelForCausalLM, AutoTokenizer

from llama_attn_replace import replace_llama_attn

replace_llama_attn()

tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path="meta-llama/Llama-2-7b-chat-hf")
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-7b-chat-hf", torch_dtype=torch.float16, device_map="auto")

model.resize_token_embeddings(len(tokenizer))
optimizer = torch.optim.AdamW(model.parameters())

dataset = load_dataset("databricks/databricks-dolly-15k", split="train", streaming=True)
dataset = dataset.map(lambda x: tokenizer([x["instruction"]], truncation=True, padding='max_length', max_length=4096, return_tensors="pt"))
train_dataloader = DataLoader(dataset)

model.train()

for step, batch in enumerate(train_dataloader):
    output = model(
        input_ids=batch["input_ids"].to(model.device).squeeze(1), attention_mask=batch.get("attention_mask").to(model.device).squeeze(1)
    )
    loss = torch.sum(output.logits - output.logits)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    print("step: ", step)
```

I'm running this on 8xA100s with CUDA 12.1 if that helps.
Let me know if more info or further experiments on my side are needed to sort this one out!
Thanks for providing this library.

**Comment by tridao** [comment]
Thanks for the bug report, let me investigate. Does it crash with the provided script? Do you know the shape of the tensors (batch, seqlen, nhead, headdim) that cause the crash?

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for the quick response @tridao 
It crashes with the provided script on my end.
I'll come back with the tensor shapes in a bit.

**Comment by ArturNiederfahrenhorst** [comment]
Just reran the code. It crashes on the first call.
The shapes are the following:
```
** qkv:  torch.Size([16, 3, 16, 128])
** cu_seqlens:  torch.Size([4])
** max_seqlen:  1024
```

**Comment by ArturNiederfahrenhorst** [comment]
@tridao Sorry for the ping, do you need more info?

**Comment by tridao** [comment]
I just tried to run the script and it didn't crash (i waited till step 400).
Do you have the cmd to run `compute-sanitizer` that produces that error log?

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for responding @tridao ! 
I'm using. `compute-sanitizer --target-processes=all python repro.py`

Heads up: With the newest transformers commits, they also changed how they treat the attention mask in the flash attention 2/non-flash attention case is that there is now use a utility called `_prepare_4d_causal_attention_mask`, so setting
`transformers.models.llama.modeling_llama.LlamaModel._prepare_decoder_attention_mask` like LongLoRA does, has no effect now. You can just set `transformers.models.llama.modeling_llama.LlamaFlashAttention2.forward` instead of `transformers.models.llama.modeling_llama.LlamaAttention.forward` and enable flash attention 2 in the llama 2 config and it should be fine if you are running into this.

**Comment by ArturNiederfahrenhorst** [comment]
I can still reproduce with the script I posted and the newest HF transformers version btw.

**Comment by ArturNiederfahrenhorst** [comment]
Did you use the provided code as-is? I wonder what the cap between our runs of this script is.

**Comment by tridao** [comment]
I got it to crash now. However, it seems it's because the cu_seqlens are wrong.
I put a breakpoint to print out:
```
     79     breakpoint()
---> 80     print(cu_seqlens_q, cu_seqlens_k)
     81     out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.varlen_fwd(

ipdb> cu_seqlens_q
tensor([  0,   8, 520,  16], device='cuda:0', dtype=torch.int32)
ipdb> (q).shape
torch.Size([16, 16, 128])
```
In this case Q has total of 16 tokens. However, cu_seqlens_q is telling the flash-attention kernel that there are 3 sequences, from indices 0 to 7, from 8 to 519(?!?), then from 520 to 16 (?!?). This causes flash-attention kernel to try to read elements beyond the 16 tokens provided, and hence memory error.

I think the problem is in producing the cu_seqlens that are wrong.

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for spotting this. This appears to be an issue with the LongLoRA forward function used here.
