### ISSUE TITLE
Support ALiBi - attention with linear biases

### ISSUE THREAD

**Issue by Bruce-Lee-LY** [Dao-AILab/flash-attention#671]
If you encounter ALiBi inference scenarios, you can refer to [flash_attention_inference](https://github.com/Bruce-Lee-LY/flash_attention_inference) whether it is flash attention or flash attention v2.

https://github.com/Bruce-Lee-LY/flash_attention_inference/blob/master/src/flash_attn/fmha/alibi.h

https://github.com/Bruce-Lee-LY/flash_attention_inference/blob/master/src/flash_attn_v2/alibi.h

**Comment by tridao** [comment]
Alibi is supported in FlashAttention as of v2.4.0
