### ISSUE TITLE
Unexpect inference result with flash_attn_triton

### ISSUE THREAD

**Issue by jchuai** [Dao-AILab/flash-attention#702]
Hi, thanks for the great work! I met a problem with flash_attn_triton.py.

This is the result with flash_attn_cuda, as it show well.
![image](https://github.com/Dao-AILab/flash-attention/assets/3783205/461a228a-87de-4f83-bce7-81933a9e7460)

However, when I replaced with flash_attn_triton, it seems the result went to strange as below.
![image](https://github.com/Dao-AILab/flash-attention/assets/3783205/e1295459-eef1-4215-897e-c4b5ede16e97)

this is how I use flash_attn_triton with hf transformers lib. Just enter the same parameters with flash_attn_cuda. 
![image](https://github.com/Dao-AILab/flash-attention/assets/3783205/6803fcd2-c2c4-41c7-8d83-081657d62635)

Is this right? does flash_attn_triton and flash_attn_cuda have the same parameters? Or the have the different shape of matrix?

**Comment by tridao** [comment]
Idk how those are called in HF, you can put a breakpoint or print out values to check of the outputs of the two implementations are close.

**Comment by jchuai** [comment]
![image](https://github.com/Dao-AILab/flash-attention/assets/3783205/6d2c11fc-8616-4bb8-b342-00776ad7243a)
hi, I have try to print out the result. It seems not quit equal/close
![image](https://github.com/Dao-AILab/flash-attention/assets/3783205/ea015218-5c39-4242-9b2e-4c0033cdc62d)


 Do you have any test about this in the project ? Maybe I can try the test firstly.

**Comment by tridao** [comment]
You want to compare the difference between the two, compared to e.g. difference between standard attention in fp32 vs standard attention in fp16. Otherwise it's hard to say if things are "close".

I think we used to have tests for the triton impl but idk where they went :D

**Comment by jchuai** [comment]
Ok I see... Just find the output is little strange... I will try myself. Thanks for you reply.

**Comment by juewang-amazon** [comment]
Hi @jchuai is there any updates regarding this thread? I also face the same issue that the inference results is bad when enabling flash attention. Thanks

**Comment by zhuconv** [comment]
Hi, sorry for bringing up this issue,  but I've recently encountered a similar problem and was wondering if you were able to resolve the inconsistency
