### ISSUE TITLE
Compile error on cuda 12.3

### ISSUE THREAD

**Issue by MikeChenfu** [Dao-AILab/flash-attention#727]
Hello, I try compiling the flash atten on the cuda 12.3 and got the error of segmentation default. It works well with cuda 11.8. I located the error on this function. https://github.com/Dao-AILab/flash-attention/blob/main/csrc/flash_attn/src/flash_fwd_kernel.h#L139

Appreciate it if anyone has an idea about it.  Many thanks!

**Comment by stevezhangzA** [comment]
How do you solve this, decrease the version of CUDA or find a right version of flash_attention? Thank you.

**Comment by HelloWorldLTY** [comment]
Hi, would you please let me know how to resolve it? Thanks!
