### ISSUE TITLE
Question on flash_attn_with_kvcache

### ISSUE THREAD

**Issue by vince62s** [Dao-AILab/flash-attention#731]
Hello @tridao ,

Got 2 questions:

1) can this function be used for prefill at step=0 hence cache_seqlens=0 ? it seems to have trouble to handle this.

2) even though this is quite fast for the LLM case (batch_size 1, prompt, decoding steps 256) it seems to be slower than the regular `flash_attn_func` when used for the self-attention part of an encoder-decoder architecture. (large batch size, limited sequence length)

**Comment by tridao** [comment]
flash_attn_with_kvcach is optimized for the decoding phase (short seqlen_q). It might work for prompt processing but I've never tried.
As mentioned in the doc string, flash_attn_with_kvcach backward pass is not supported.

**Comment by vince62s** [comment]
I'm not trying to train with it, just saying for inference of an encoder-decoder it seems slower than the `flash_attn_func` when using a large batch size and limited seq length.

**Comment by tridao** [comment]
Yeah you can use whichever is faster for your case.
