### ISSUE TITLE
Solution to most of the Windows build issues... 

### ISSUE THREAD

**Issue by NeedsMoar** [Dao-AILab/flash-attention#735]
First off I built wheels of the standard xformers build (which builds flash attention 2 in-tree on linux but hasn't had that config available on Windows for a while (or ever?) that are on my git.  They contain device code only assuming something didn't override that for sm_86 (ampere consumer) and sm_89 (ada consumer), since I think people with those will have the biggest issues with ram usage and building.   I didn't build the A100 & H100 device code because it would have doubled size / time, and since those modules and cards need at least 1.5x their vram per card and are usually installed in Epycs anyone who needs it can find the CPU time to do so.  If you're still on torch 2.1.1-cu121 the initial wheels I built have A100 / H100 support via device code and PTX so you can grab them and prebuilt xformers if you want and it should work the same, this is just more convenient.  
[Unofficial Build of XFormers dev + flash-attention for torch 2.1.2-cu121](https://github.com/NeedsMoar/flash-attention-2-builds/releases/tag/xformers-0.0.24-trunk_with_flash-attention-v2.3.6)

Memory cuts I found

## The NVCC --threads option
```python
def append_nvcc_threads(nvcc_extra_args):
    return nvcc_extra_args + ["--threads", "4"]
```

This is supposed to be setting nvcc to compile for up to 4 architectures in parallel...   Even though flash attention only builds for two by default, it became clear to me when messing with it at --threads 2 that it wasn't working correctly.  NVCC doesn't create threads on Windows, it just spawns more compilers / subprocesses (or the threads do, I didn't bother debugging), and there were an obscene number of them, upwards of 250 for a 2 arch build of just flash attention. 

## The bigger, stupider one
I noticed that aside from the hundreds of compiler processes being spawned directly and indirectly, the memory curve of the build would skyrocket, stay there, then slowly begin dropping off with the processor use dropping faster.  There was also an enormous amount of kernel time on one of the cores.  I thought that nvcc might be blocking until it can call its own link phase since it was acting as a compiler driver by that point but the solution is stupider.

The Windows cmd shell normally orders output as it was received, and follows the std::cout convention of "\n" not normally flushing to the buffer and std::endl flushing which is all well and good, it gets spammed with so much during a build run here there it takes a while before it gets the output from the builds it needs to display first because they're longer running, where the small files just tend to complete rapidly.  

The issue there was that _Python itself_ buffers output, is apparently kinda bad at it, and is seemingly what keeps the process doing the output in memory until after the print / flush can finish.   That's an OS detail if you've sent everything in a single chunk and so my guess was that like too much software it was doing stupid second guessing that made things worse.  

So I tried turning it off:
```python
python -u setup.py bdist_wheel
```
MAX_JOBS was 64
Maximum memory use was 70GB (system + compilers).  It took 5 minutes which was ~3 longer than transformers but probably about on par with what XFormers + flash + sputnik + a bunch of arbitrary chunks of cutlass and cute targeting CPU.  I'd imagine most people can just leave MAX_JOBS alone and let ninja handle the threading and turn off the threads argument up top and and python buffering when you call the build (to keep it from continuing to grow).   With 48 for MAX_JOBS, threads 1, but no -u option on python the ram use was over 100GB at one point and 150 processes (mixed cudafe++, nvcc, and ptxas) just hanging around not doing much of but sucking down memory and waiting in spinlocks or possibly deadlocked in places.  . 

## XFormers building
There's some kind of weirdness in the setup.py for that library;  aside from needing to add --threads==1 to the compiler flags, the parts of cutlass::cute it builds with cl.exe using c++17 use automatic template return type deductions that aren't allowed by standard C++, so the following -Xcompiler flags needed to be added to that build:

/permissive /std:c++17 /Zc:preprocessor

The first one sets everything to non-compliant modes.  It's possible C++20 would build it as-is, I didn't feel like messing with it, and even more confusingly it was originally set to zero tolerance with /permissive-.  It's possible I'll narrow this down to 1 or 2 force disabled compliance options...  If anyone knows where to file nvcc bug reports I think threads' behavior is one despite the -u option 

Anwyay hopefully that helps somebody, it should keep things low ram enough to build on git without dropping to so few threads that it takes forever.  In the meantime I'll be building wheels for new versions every so often, but I'm moving over into learning Houdini so it's likely I won't be checking in as often.  Torch is shipping nightly builds with this enabled on linux but not windows now. The same changes minus the CL.exe  specific flags should let people build more easily on Linux as well.  

Running with the regular pytorch 2 cross attention model can handle a tiny fraction of the data flash attention can, and xformers without it isn't nearly the speed, so I'd hope some of the bigger companies using it as a major part of their projects might volunteer some time to get a wheel going.  Even though the single Xformer + package is more convenient being able to drop-install an arbitrary flash attention and have xformers pick it up is handy.

**Comment by NeedsMoar** [comment]
Looks like xformers is building flash_attn for windows releases again on their own so you can just pull their build, much easier and you don't have to rely on my janky repo.  I might keep putting the ada-only builds of flash-attention I make for personal use there but I'm probably going back to trying to make TransformerEngine work on Windows instead.

**Comment by biship** [comment]
> xformers

Where?
