### ISSUE TITLE
Question about FlashDecoing on Chatglm2

### ISSUE THREAD

**Issue by wics1224** [Dao-AILab/flash-attention#737]
Dear @tridao, I have migrated FlashDecoing in FasterTransformer decoding phase on chatglm2 model, I just replaced ft_attention with mha_fwd_kvcache  , but inference speed becoming much slower than ft_attention, the gpu utilization rate only up to about 60%，can you analyze the reasons for the slower speed?I am very confused now...

**Comment by tridao** [comment]
Can you benchmark just the 2 functions (ft_attention and flash_attn_with_kv_cache) and post the results here?

**Comment by wics1224** [comment]
Thank you for your reply！I will conduct a comparative test later

**Comment by wics1224** [comment]
Dear @tridao,The test results are as follows,warmup time set to 1000， and speed test time is 1000 too:

ft_attention:
![ft_speed](https://github.com/Dao-AILab/flash-attention/assets/46515805/96ccd3da-4342-4ca6-a2e9-3af63e58fd30)
![ft_attn_gpu](https://github.com/Dao-AILab/flash-attention/assets/46515805/3524530f-16f4-4e2f-b57d-e0396457b4ec)

flash_decoding:
![flash_decoding_speed](https://github.com/Dao-AILab/flash-attention/assets/46515805/d3b613a1-b2f5-4e36-80e8-d4ab1dbd419a)
![flash_decoding_gpu](https://github.com/Dao-AILab/flash-attention/assets/46515805/72a3cb7e-8a8e-47b6-88ee-448b64b461d7)

The test code is as follows：
ft_attn:
![ft_code_1](https://github.com/Dao-AILab/flash-attention/assets/46515805/1b183646-d499-4a76-b214-5e1bb462bd43)
![ft_code_2](https://github.com/Dao-AILab/flash-attention/assets/46515805/e1d4e645-7606-42cd-b0f8-4c9cbebb46b3)
![ft_code_3](https://github.com/Dao-AILab/flash-attention/assets/46515805/2d8112f0-220a-4b9b-b5a8-11cdf860591c)

flash_decoding:
![flash_code_1](https://github.com/Dao-AILab/flash-attention/assets/46515805/9dd6be20-e809-4983-bc8b-3cd43d7b5191)
![flash_code_2](https://github.com/Dao-AILab/flash-attention/assets/46515805/d5699573-76a8-4e9e-9a2f-ab12a7d67b09)
![flash_code_3](https://github.com/Dao-AILab/flash-attention/assets/46515805/1d4920d4-1dc7-4e5c-b887-a59d5fa5a5cb)

**Comment by wics1224** [comment]
Dear @tridao, I extracted the code of flashdecoding,and removed torch related interfaces ,then compile them to static library,will this be a problem?

**Comment by wics1224** [comment]
Here is the code I invoked, I just passed in the relevant parameters:
![1](https://github.com/Dao-AILab/flash-attention/assets/46515805/9e11f78f-03c0-4aab-9b4c-523d16bbe616)
![2](https://github.com/Dao-AILab/flash-attention/assets/46515805/61b5d69d-4fd4-4082-85d2-63f2afb380a0)

**Comment by tridao** [comment]
There's a memcpy within "invoke_flash_decoding", that's probably what's slowing you down. You'd want cache_seqlens to be a tensor already on GPU.

**Comment by wics1224** [comment]
Dear @tridao, Thank you for your reply！I found out it was because I invoked "cudaGetDeviceProperties(&properties, device_idx)" to avoid invoke at::cuda::getCurrentDeviceProperties()。After repair this problem, the speed is indeed faster than FasterTransformer.Thank you again!!!
