### ISSUE TITLE
[QST] Maybe there's not bank conflict between thread 0-7 and thread 8-15 as described in kernel_traits?

### ISSUE THREAD

**Issue by umiswing** [Dao-AILab/flash-attention#738]
According to this [gtc slides](https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9593-cutensor-high-performance-tensor-operations-in-cuda-v2.pdf), when accessing shared memory in 128bits, thread 0-7 belongs to phase 1, thread 8-15 belongs to phase 2, and bank conflict occurs between threads in the same phase, not the same warp.
![image](https://github.com/Dao-AILab/flash-attention/assets/37094513/db0034c3-bf3e-47b5-8d99-384a0458bb37)

I'm confused about the comment in [kernel_traits.h](https://github.com/Dao-AILab/flash-attention/blob/main/csrc/flash_attn/src/kernel_traits.h#L127-L131) which describes bank conflicts between threads from different phases and the performance gained from eliminating the conflicts.

**Comment by tridao** [comment]
Oh then I must be mistaken, GTC slides are probably more trustworthy.
