### ISSUE TITLE
 from flash_attn.flash_attention import FlashAttention  does not work 

### ISSUE THREAD

**Issue by thwgithub** [Dao-AILab/flash-attention#739]
Hi all,
After pip install flash_attn(latest),  ''from flash_attn.flash_attention import FlashAttention''  does not work, I donot know the reason. In flash_attn2.4.2, What is the substitute function of the FlashAttention.

**Comment by tridao** [comment]
You can use the functions mentioned in the README

**Comment by thwgithub** [comment]
@tridao 
Thank you for your instant reply. I try it again

**Comment by thwgithub** [comment]
@tridao 
when I run "from flash_attn.flash_attention import FlashAttention",  error as follows:
Traceback (most recent call last):
  File "/home/hwtan/anaconda3/envs/pytorch/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-7cccac35350c>", line 1, in <module>
    from flash_attn.flash_attention import FlashAttention
  File "/home/hwtan/pycharm/pycharm-community-2023.2.4/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'flash_attn.flash_attention'

**Comment by thwgithub** [comment]
class QKVFlashAttention(nn.Module):
    def __init__(
        self,
        embed_dim,
        num_heads,
        batch_first=True,
        attention_dropout=0.0,
        causal=False,
        device=None,
        dtype=None,
        **kwargs,
    ) -> None:
        from einops import rearrange
        from flash_attn.flash_attention import **FlashAttention**
        assert batch_first
        factory_kwargs = {"device": device, "dtype": dtype}
        super().__init__()
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.causal = causal

        assert (
            self.embed_dim % num_heads == 0
        ), "self.kdim must be divisible by num_heads"
        self.head_dim = self.embed_dim // num_heads
        assert self.head_dim in [16, 32, 64], "Only support head_dim == 16, 32, or 64"

        self.inner_attn = **FlashAttention**(
            attention_dropout=attention_dropout, **factory_kwargs
        )
        self.rearrange = rearrange

    def forward(self, qkv, attn_mask=None, key_padding_mask=None, need_weights=False):
        qkv = self.rearrange(
            qkv, "b (three h d) s -> b s three h d", three=3, h=self.num_heads
        )
        qkv, _ = self.inner_attn(
            qkv,
            key_padding_mask=key_padding_mask,
            need_weights=need_weights,
            causal=self.causal,
        )
        return self.rearrange(qkv, "b s h d -> b (h d) s")

codes above are complete. I'm not familiar with flash attention, can you help me correct it? import flast_attn is ok.

**Comment by tridao** [comment]
You might want to look at flash_attn.modules.mha.MHA

**Comment by thwgithub** [comment]
@tridao Thans for your suggestion.

**Comment by Tranquil1ty** [comment]
I encountered the same problem, in fact, pip install flash.attn=0.2.8 can solve the problem
