### ISSUE TITLE
fused dense layer heuristics

### ISSUE THREAD

**Issue by wearegolden** [Dao-AILab/flash-attention#744]
Hello, I have a question regarding the heuristics in fused_dense_layer.

Here, it says for cuda 11.7 and under, heuristic=-1 is fastest for bf16. (https://github.com/Dao-AILab/flash-attention/blob/1a2c3e8c25251fa30ebee074c27ecbf69c2bad2b/flash_attn/ops/fused_dense.py#L555C1-L562C52)

Indeed though some experiments I observed that setting heuristic to -1 was faster than setting it to 0 or 1 in my case(cuda 11.7, bfloat16).

Can anyone provide me with insight as to why in some cases the fused kernel is slower than the non-fused ones?
Thanks a lot in advance!

**Comment by tridao** [comment]
I think it's just a matter of how much work has been spent on optimizing each case. Early version of fused gemm + bias + activation (e.g. cuda 11.7) wasn't very optimized, and later on the cublas team optimized it more.

**Comment by wearegolden** [comment]
Thanks for the swift reply!
