### ISSUE TITLE
Question regarding PILE Dataset Loading

### ISSUE THREAD

**Issue by LeoXinhaoLee** [Dao-AILab/flash-attention#750]
Hi, thank you so much for releasing code for this great work! I have 3 questions as follows:

(1) The data preparation script seems to process the whole PILE dataset into a single file, and the program seems to load it at once into memory for training. I am wondering if this poses a challenge to servers with a relatively small RAM.

(2) If we cannot fit PILE into memory at once, I am wondering if we need to manually shuffle PILE before tokenizing it, since streaming from disk is sequential (cannot work with DistributedSampler) ?

(3) Besides, for distributed training, I am wondering if it's better to divide PILE into multiple partitions and let each node read from some particular ones. Are there any references for this practice?

Thank you very much for your time and help!

**Comment by tridao** [comment]
The dataset is loaded using mmap so it actually stays on disk. Whenever a block is accessed, that block is fetched from disk to memory.

**Comment by LeoXinhaoLee** [comment]
Thank you for your kind reply. I am also wondering could `DistributedSampler` lead to incontiguous read of the mmap dataset, which could be slow. If that is the case, it is better to pre-shuffle the entire dataset after tokinization, and then read it sequentially.

**Comment by tridao** [comment]
It's been fine for me, but you can try if it's slow.

**Comment by LeoXinhaoLee** [comment]
I see. Thank you very much for your time and help!
