### ISSUE TITLE
GPUA10：QWenLMHeadModel does not support Flash Attention 2.0 yet

### ISSUE THREAD

**Issue by PolarPeak** [Dao-AILab/flash-attention#758]
ValueError: QWenLMHeadModel does not support Flash Attention 2.0 yet. Please open an issue on GitHub to request support for this architecture: https://github.com/huggingface/transformers/issues/new

my GPU is A10

![image](https://github.com/Dao-AILab/flash-attention/assets/44831329/aead195b-4a07-4d80-967f-3919527b56ce)

**Comment by tridao** [comment]
You'd have better luck opening an issue on `transformers` repo.
