### ISSUE TITLE
The layer_norm module compiled incorrectly

### ISSUE THREAD

**Issue by yumianhuli1** [Dao-AILab/flash-attention#759]
I encounter the following warning when using LLM inference：
        CUDA extension not installed.
        CUDA extension not installed.
        Try importing flash-attention for faster inference...
        Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
        Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm

 So I downloaded the source code for flash-attn and compiled the source code including rotary and layer_norm.The flash-attn and rotary modules compile without problems .However, compiling the layer_norm module failed, reported more than 100 compile errors and then automatically terminated the compilation, I used win11, cuda12.1, pytorch2.1.1.

**Comment by tridao** [comment]
I don't know much about compiling on Windows.
As mentioned in the layer_norm README, `this extension is no longer used in the FlashAttention repo. We've instead switched to a Triton-based [implementation](https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/ops/triton/layer_norm.py)`. However, I also don't know if Triton is supported on Windows.

**Comment by yumianhuli1** [comment]
> I don't know much about compiling on Windows. As mentioned in the layer_norm README, `this extension is no longer used in the FlashAttention repo. We've instead switched to a Triton-based [implementation](https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/ops/triton/layer_norm.py)`. However, I also don't know if Triton is supported on Windows.

got it

**Comment by LPZliu** [comment]
I'm having the same problem as you, layer_norm keeps compiling unsuccessfully

**Comment by LPZliu** [comment]
how to address it?

**Comment by sipie800** [comment]
same here. flash_atten and rotary are right. layernorm fail. IMO there are something wrong with MAX_JOBS. but can't get it work
