### ISSUE TITLE
Has anyone gotten flash-attn to work on google colab?

### ISSUE THREAD

**Issue by CedricSimon** [Dao-AILab/flash-attention#761]
For context, I am trying to fine-tune Mistral-7b on Colab, using the A100. There are no issues during the install, packaging and ninja --version seem to work as intended.
However, when loading the model with flash_attention2 enabled or when trying to import flash_attn, I get this error:

![grafik](https://github.com/Dao-AILab/flash-attention/assets/23502133/c9470a4b-de93-45ab-9fdc-614d7e272604)

Would appreciate any help!

**Comment by samedovzaur1** [comment]
Did you get it solve? cuz i get the error rn that is due to A100 is not working even though i choose A100 it uses V100 always!

**Comment by CedricSimon** [comment]
> Did you get it solve? cuz i get the error rn that is due to A100 is not working even though i choose A100 it uses V100 always!

Google colab has a limited number of A100s at their disposal, so if they are all being used it will automatically give you a V100. There is not much you can do about it apart from spending more money on credits (as far as i know, users with more credits get priotity on A100 usage).

However, I think it will be difficult to use the flash-attn library on colab, it requires fairly specific setup. I ended up using the pytorch container they recommend on aws sagemaker. Colab does not have docker-container support though, so you should probably either switch cloud environment or train your model without flash-attn.
