### ISSUE TITLE
RuntimeError: FlashAttention only supports Ampere GPUs or newer.

### ISSUE THREAD

**Issue by bilalghanem** [Dao-AILab/flash-attention#762]
### System Info

I am trying to run the following code:

```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# Configs
device = "cuda:7"
model_name = "openchat/openchat_3.5"
model = AutoModelForCausalLM.from_pretrained(model_name, device_map=device, load_in_4bit=True, bnb_4bit_quant_type="nf4", bnb_4bit_use_double_quant=True, 
                                             bnb_4bit_compute_dtype=torch.bfloat16, attn_implementation="flash_attention_2")
tokenizer = AutoTokenizer.from_pretrained(model_name, padding_side='left')

```

I can load the model completely fine, but when I want to generate, I get this error:

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> Cell In[3], [line 76](vscode-notebook-cell:?execution_count=3&line=76)
>      [74](vscode-notebook-cell:?execution_count=3&line=74) model_input_text = template.format(start, html_, end)
>      [75](vscode-notebook-cell:?execution_count=3&line=75) model_inputs = tokenizer([model_input_text], return_tensors="pt", padding=False).to(device)
> ---> [76](vscode-notebook-cell:?execution_count=3&line=76) generated_ids = model.generate(**model_inputs, do_sample=True, top_p=1.0, temperature=0.8, top_k=50, max_new_tokens=1024)
>      [77](vscode-notebook-cell:?execution_count=3&line=77) model_outputs_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
>      [78](vscode-notebook-cell:?execution_count=3&line=78) print(model_outputs_text[model_input_text.rindex("GPT4 Correct Assistant:")+10:])
> 
> File [~/PATH/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py:115](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py:115), in context_decorator.<locals>.decorate_context(*args, **kwargs)
>     [112](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py:112) @functools.wraps(func)
>     [113](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py:113) def decorate_context(*args, **kwargs):
>     [114](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py:114)     with ctx_factory():
> --> [115](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py:115)         return func(*args, **kwargs)
> 
> File [~/PATH/venv/lib/python3.8/site-packages/transformers/generation/utils.py:1764](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/transformers/generation/utils.py:1764), in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, **kwargs)
>    [1756](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/transformers/generation/utils.py:1756)     input_ids, model_kwargs = self._expand_inputs_for_generation(
>    [1757](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/transformers/generation/utils.py:1757)         input_ids=input_ids,
>    [1758](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/transformers/generation/utils.py:1758)         expand_size=generation_config.num_return_sequences,
>    [1759](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/transformers/generation/utils.py:1759)         is_encoder_decoder=self.config.is_encoder_decoder,
>    [1760](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/transformers/generation/utils.py:1760)         **model_kwargs,
>    [1761](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/transformers/generation/utils.py:1761)     )
>    [1763](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/transformers/generation/utils.py:1763)     # 13. run sample
> -> [1764](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/transformers/generation/utils.py:1764)     return self.sample(
>    [1765](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/transformers/generation/utils.py:1765)         input_ids,
> ...
>      [58](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py:58)     None,
>      [59](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py:59) )
>      [60](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22544e414970726d676d743031227d.vscode-resource.vscode-cdn.net/PATH/notebooks/~/PATH/venv/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py:60) return out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state
> 
> RuntimeError: FlashAttention only supports Ampere GPUs or newer.

I am working on Ubuntu 20.04 with NVIDIA Quadro RTX 5000.
Cuda version: 12.2
NVIDIA-SMI 535.129.03
torch==2.1.2
transformers==4.36.2

**Comment by tridao** [comment]
Yup Quadro RTX 5000 is Turing card, not Ampere and not currently supported.

**Comment by bilalghanem** [comment]
> Yup Quadro RTX 5000 is Turing card, not Ampere and not currently supported.

thank you!

**Comment by TheJason1997** [comment]
Hi @tridao, all of my GPUs are Tesla T4, but I still encountered this issue. I tried to load `Mistral-7B-Instruct-v0.2` in the following code:
```
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    load_in_8bit=False,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    attn_implementation="flash_attention_2",
)
```
<img width="672" alt="image" src="https://github.com/Dao-AILab/flash-attention/assets/34732604/b9497c37-add3-41e4-a79c-cbf28f362898">
<img width="1105" alt="image" src="https://github.com/Dao-AILab/flash-attention/assets/34732604/607f8425-868e-4b5c-bd16-55e2383ef41c">
