### ISSUE TITLE
Does flash_atth has a interface like xformers's BlockDiagonalCausalMask?

### ISSUE THREAD

**Issue by janelu9** [Dao-AILab/flash-attention#765]
![image](https://github.com/Dao-AILab/flash-attention/assets/24219258/f97b376e-4d75-4435-8e32-af339a286518)

**Comment by janelu9** [comment]
It flats the batch_size dim to the seq_len dim

**Comment by tridao** [comment]
Take a look at [flash_attn_varlen_func](https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/flash_attn_interface.py). This is what xformers calls I think.

**Comment by janelu9** [comment]
> Take a look at [flash_attn_varlen_func](https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/flash_attn_interface.py). This is what xformers calls I think.

thanks, I think so.
