### ISSUE TITLE
Does this project support Apple seliicon(mps)?

### ISSUE THREAD

**Issue by hsiunien** [Dao-AILab/flash-attention#770]
I want to run some project which depending on this project, but I got the error as follows

/private/var/folders/0d/nlqzghcs12q82rwb1_z20ktr0000gn/T/pip-install-nq6jv898/flash-attn_ed1432964b3e4136b15c946130da60c8/setup.py:78: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0d/nlqzghcs12q82rwb1_z20ktr0000gn/T/pip-install-nq6jv898/flash-attn_ed1432964b3e4136b15c946130da60c8/setup.py", line 133, in <module>
      
so I thought  it is this project depend on the suda, is there any way to support apple seliicon(mps)? so that I can use GPU resource form my laptop.

**Comment by tridao** [comment]
No we only support GPUs with CUDA capability.
