### ISSUE TITLE
The results obtained from Flash attention differ from those of my self-implemented and pytorch version when set dropout_p != 0

### ISSUE THREAD

**Issue by jarun-title** [Dao-AILab/flash-attention#771]
I don't understand why dropout_p affect the results.

![image](https://github.com/Dao-AILab/flash-attention/assets/133948063/5fd32312-a468-4b43-8dd3-2b380f115886)

![image](https://github.com/Dao-AILab/flash-attention/assets/133948063/344012ff-c6f8-4a78-8edd-6c4f521df07e)

**Comment by jarun-title** [comment]
So, are you saying that  FlashAttention implementation uses a different dropout implementation compared to the one in PyTorch?

**Comment by tridao** [comment]
Yup

**Comment by jarun-title** [comment]
Okay, thanks for explaining that!
