### ISSUE TITLE
Since yesterday getting ImportError: undefined symbol: _ZN2at4_ops15sum...

### ISSUE THREAD

**Issue by CedricSimon** [Dao-AILab/flash-attention#784]
As the title says, last week I was using the exact same setup and everything was working correctly.
I am running on the latest nvidia pytorch container (23.12), so:
Ubuntu 22.04
CUDA 12.3.2
Pytorch 2.2.0a0+81ea7a4

I am using this command to install:
RUN MAX_JOBS=4 pip install --upgrade flash-attn --no-build-isolation

This is the full error message:
>>> from flash_attn import flash_attn_qkvpacked_func, flash_attn_func
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/flash-attention/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/workspace/flash-attention/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_IntList_out4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbSt8optionalINS5_10ScalarTypeEERS2_

I saw there was a thread with a similar error message a while ago: https://github.com/Dao-AILab/flash-attention/issues/667
However, installing from source as described in the thread did not work.

**Comment by tridao** [comment]
Right, nvcr 23.12 uses pytorch 2023.11.06 and that version of pytorch nightly is no longer available to download (https://download.pytorch.org/whl/nightly/torch/), so our CI has to use pytorch 2023.11.30 to compile. And there are differences between the 2 versions of pytorch that the CUDA wheel compiled for pytorch 2023.11.30 is not compatible with pytorch 2023.11.06 :(
You can use a earlier version of flash-attn or wait for nvcr 24.01.

**Comment by CedricSimon** [comment]
That explains it, thank you! In case anyone else looks at this thread, I am now using the nvidia pytorch container 23.12 with flash-attn version 2.4.2, which seems to be working fine :)
