### ISSUE TITLE
Flash Attention Support for Pytorch 2.3

### ISSUE THREAD

**Issue by KuuCi** [Dao-AILab/flash-attention#790]
Hi! Wondering if there were any plans on building wheels for pytorch 2.3. As of right now pip installing will cause us to have to build from source, which is extremely slow with limited hardware.

**Comment by tridao** [comment]
i don't think it's out?

**Comment by KuuCi** [comment]
Sorry -- pytorch nightly

**Comment by tridao** [comment]
Sure, do you want to send a PR?

**Comment by KuuCi** [comment]
yup!

**Comment by j316chuck** [comment]
@tridao mind linking an example pytorch bump PR?

**Comment by tridao** [comment]
https://github.com/Dao-AILab/flash-attention/commit/43ceab630bc6c27712428da5a33fc9cb5c369d91

**Comment by ckadner** [comment]
@j316chuck @KuuCi -- sorry for preempting you with a PR https://github.com/Dao-AILab/flash-attention/pull/793 but we recently started using PyTorch 2.3 and our Docker builds / pip installs for flash-attention went from seconds to more than an hour.
