### ISSUE TITLE
May support headdim>256? such as 512.

### ISSUE THREAD

**Issue by DefTruth** [Dao-AILab/flash-attention#801]

**Comment by tridao** [comment]
Are there any model using head dim 512?

**Comment by tridao** [comment]
with numhead = 1 and large headdim i think it's faster to compute attention naively rather than using flash-attn.

**Comment by DefTruth** [comment]
> with numhead = 1 and large headdim i think it's faster to compute attention naively rather than using flash-attn.

many thanks
