### ISSUE TITLE
[Bug] Undefined symbol when executing `import flash_attn` after installing on recommended NVIDIA container

### ISSUE THREAD

**Issue by jaanphare** [Dao-AILab/flash-attention#808]
Thank you so much for this library! :) Really excited to test it for our research in the health care + LLM domain.

Any ideas on how to debug this? 

Running into a bug when installing this on Amazon Web Services `g5.xlarge` instances on EC2 with A10 GPUs that should support the `flash_attn` library: 

```
>>> import flash_attn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_IntList_out4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbSt8optionalINS5_10ScalarTypeEERS2_
>>> 
```

This is using the recommended NVIDIA container:
* https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch

The following commands can be executed in this container to reproduce this bug: 
```
docker run --gpus all -it --rm nvcr.io/nvidia/pytorch:23.11-py3
pip uninstall flash_attn  # uninstall the older 2.0.2 version of flash_attn that ships with the container
MAX_JOBS=4 pip install flash-attn --no-build-isolation 
python
>>> import flash_attn
```

**Comment by tridao** [comment]
Try flash-attn=2.5.1? nvcr now uses pytorch 2.2.0.dev20231106 but our CI now compiles for torch 2.2.0 official, and the wheel compiled for the 2 versions are not compatible.
