### ISSUE TITLE
What not swap the for loop order of QKV for bwd pass in FA2 paper? confuse.

### ISSUE THREAD

**Issue by DefTruth** [Dao-AILab/flash-attention#815]

**Comment by DefTruth** [comment]
In FA2:  
- fwd: first Q, and then K, V - vs FA1 first K, V, and then Q
- bwd: first K, V, and then Q - same as FA1

**Comment by DefTruth** [comment]
@tridao 

个人理解是由于原子通信数量的原因？调换循环顺序后，需要的原子通信的操作将会增加：1 -> 4
原先只有dQi需要通信，如果调换循环顺序，会导致dV,dP,dS,dK需要通信？

Personal understanding is due to the number of atomic communications? After changing the loop order, the required atomic communication operations will increase: 1 -> 4
Originally, only dQi needed to communicate. If the cycle order was changed, would dV, dP, dS, and dK need to communicate?

**Comment by tridao** [comment]
For bwd you either need to do atomic adds on dQ, or atomic adds on dK and dV. The current loop order means we're using atomic adds on dQ, and that's a little bit faster than the other way.

**Comment by DefTruth** [comment]
Got it, thank you very much!
