### ISSUE TITLE
I would like to understand why rotary_dim has to be divisible by 16 in flash_attn_with_kvcache.

### ISSUE THREAD

**Issue by cyfwry** [Dao-AILab/flash-attention#817]
Thank you for your outstanding work. I have a question about flash_attn_with_kvcache. Why is there a restriction that rotary_dim is divisible by 16? I have a model whose rotary_dim is not divisible by 16. I want this model to also use flash_attn_with_kvcache. Is this feasible?

**Comment by tridao** [comment]
It's for ease of implementation in loading the cos/sin. We welcome contribution to extend it.

**Comment by cyfwry** [comment]
您好，您发给我的邮件已收到！
