### ISSUE TITLE
Allowing providing `cos` and `sin` as float instead of same as input

### ISSUE THREAD

**Issue by adefossez** [Dao-AILab/flash-attention#823]
Hello Tri,
Thanks a lot for all the great contributions you made for building efficient transformers. I'm trying to use your custom Rope implementation, and I was surprised to see you enforce the `cos` and `sin` param to be provided with the same `dtype` as the input. However, according to my test, while that leaves little error for `float16`, it seems to lead to as much as 24% relative error in my use case when using `bfloat16`. I've tried modifying the implementation in [rotary_cuda.cu](https://github.com/Dao-AILab/flash-attention/blob/main/csrc/rotary/rotary_cuda.cu#L25) to accept bfloat16 for the input and float for `cos` and `sin`, and it seems to have little impact on speed, but allows to get the exact same output as doing everything in float32 then casting to bfloat16 (our reference implementation).

I wanted to double check with you if that was intended.

**Comment by adefossez** [comment]
After further experimenting, it seems under a real life workload, the extra bandwidth used for loading the `cos` and `sin` values as float32 still seems detrimental to getting the largest possible speed. Maybe some kernel leveraging the fact that `cos` and `sin` are repeated across heads and batch size might improve things...

**Comment by tridao** [comment]
I've switched to the rotary implementation in Triton: https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/ops/triton/rotary.py

If you pass in cos and sin in float32 it should work. There's an assert right now to check x.dtype == cos.dtype but you can comment that out to see.

**Comment by adefossez** [comment]
Thanks @tridao, I've just tried that but I wasn't able to get any speed up compared to the naive implementation sadly. I do know that rope is taking a significant amount of time as switching to additive pos embedding on the very first layer is much faster. I would have to investigate this more at some point.

**Comment by adefossez** [comment]
my initial benchmark were faulty due to other issues with some of our GPUs, closing the issue!
