### ISSUE TITLE
Why does paged KV Attention block size have to be at least a multiple 256?

### ISSUE THREAD

**Issue by ramyaprabhu-alt** [Dao-AILab/flash-attention#828]
Hi! I really appreciate the fact that you've added paged attention here!

I was just wondering why the page_block_size is set such that it must be a multiple of 256? Because according to the paper that introduced [Paged Attention](https://arxiv.org/pdf/2309.06180.pdf), it is best to have a block size of ~16 and higher block size leads to latency increase in end to end time.

**Comment by zhaoyang-star** [comment]
Same question. `page_block_size` which is a multiple of 256 may cause memory suboptimal. @tridao

**Comment by neeldani** [comment]
Was anyone able to find an answer to this?

**Comment by tridao** [comment]
The reason is that it's easier to implement with block size multiple of 256. For smaller block size we'd need someone to implement that :D

**Comment by neeldani** [comment]
Gotcha! Thanks for the quick response 😄
