### ISSUE TITLE
Q: Support for Nvidia L4

### ISSUE THREAD

**Issue by HitSakhavala** [Dao-AILab/flash-attention#830]
I do not own Nvidia L4 but I am considering renting it from GCP or other cloud platforms.
But selecting L4 depends upon whether it has the support of FlashAttention or not, since L4 have Ada Lovelace Architecture I was assuming that FlashAttention2 is supported in it. but [this discussion](https://github.com/Dao-AILab/flash-attention/issues/158) made it clear that not all the GPUs with Ampere, Ada, or Hopper are supported.

I would like to know whether RN L4 support FlashAttention2 or not.

and It would be great if you could add GPU names in documentation instead of architecture for more clarification

**Comment by Qubitium** [comment]
L4 is supported. The discussion you mentioned was about a training on a model with too large of a head that is not supported on L4 or most gpus that is not A100/H100 level spec (vram). 

If you want to train a model with headdim=128, you must have A100 or H100 level gpu. For inference, it doesn't matter and L4 will run just fine. 

`backward for headdim=128 requires A100 or H100 GPU`

https://github.com/Dao-AILab/flash-attention/issues/158#issuecomment-1516286929
