### ISSUE TITLE
RuntimeError: `<class 'flash_attn.layers.rotary.RotaryEmbedding'>' was not properly set up for sharding by zero.Init()

### ISSUE THREAD

**Issue by dayL-W** [Dao-AILab/flash-attention#835]
使用DeepSpeed+flash atten做训练提示如下错误：

[rank0]: RuntimeError: `<class 'flash_attn.layers.rotary.RotaryEmbedding'>' was not properly set up for sharding by zero.Init(). A subclass of torch.nn.Module must be defined before zero.Init() where an instance of the class is created.

![image](https://github.com/Dao-AILab/flash-attention/assets/29191972/91713608-5906-40d1-8a31-250336314216)

环境情况如下

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.37.2
- Platform: Linux-3.10.0-1160.108.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.11.5
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: 0.26.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.3.0.dev20240205+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by Qubitium** [comment]
1. Disable sharding. Does it work without sharding?
2. Check deepspeed config and start with a base ds config to start then add more zero configs such as sharding. 

I think this is more a deepspeed issue  or ds usage issue than fa.

**Comment by dayL-W** [comment]
> 1. Disable sharding. Does it work without sharding?
> 2. Check deepspeed config and start with a base ds config to start then add more zero configs such as sharding.
> 
> I think this is more a deepspeed issue or ds usage issue than fa.

Thanks for your reply, I found that this is the problem of Deepspeed, I upgraded Deepspeed and the problem was fixed
