### ISSUE TITLE
Bug in loading of pretrained BERT weights

### ISSUE THREAD

**Issue by kklemon** [Dao-AILab/flash-attention#864]
If I load a pretrained BERT model from HF like this

```python
import torch

from transformers import BertTokenizer, BertModel, BertConfig

tokenizer = BertTokenizer.from_pretrained('google-bert/bert-base-uncased')
config = BertConfig.from_pretrained('google-bert/bert-base-uncased')
model = BertModel.from_pretrained("google-bert/bert-base-uncased", config=config)
model.eval()
model.cuda()

input_ids = torch.randint(0, tokenizer.vocab_size, (1, 512)).cuda()

logits = model(input_ids)['last_hidden_state']
```

I would expect to get approximately the same result as from a FlashAttn BertModel loaded with the same weights:

```python
from flash_attn.models.bert import BertModel

config.use_flash_attn = True

model = BertModel.from_pretrained('google-bert/bert-base-uncased', config=config)
model.eval()
model.cuda()

with torch.autocast('cuda'):
    logits_fa = model(input_ids)['last_hidden_state']
```

But `torch.allclose` gives `False`;

```python
>>> torch.allclose(logits_fa, logits, atol=1e-4)
False
```

Upon close inspection, it turns even out that the difference in outputs is non-deterministic with respect to model initializations:

```python
for i in range(10):
    model = BertModel.from_pretrained('google-bert/bert-base-uncased', config=config).cuda()
    model.eval()

    with torch.autocast('cuda'):
        logits_fa = model(input_ids)['last_hidden_state']

    print(float((logits_fa - logits).abs().sum()))
```

gives

```
340247.3125
336003.46875
335443.8125
342978.3125
348175.34375
336785.28125
338270.5625
339818.8125
339333.34375
340444.90625
```

This suggests that some weights are probably not loaded from the pretrained weights and thus randomly initialized.

If I construct and load the pretrained weights manually, as in https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/models/bert.py#L332 but with `strict=False`, the problem becomes apparent:

```python
from flash_attn.models.bert import BertModel, BertPreTrainedModel, remap_state_dict
from flash_attn.utils.pretrained import state_dict_from_pretrained

model = BertModel(config=config)

state_dict = remap_state_dict(
    state_dict_from_pretrained('google-bert/bert-base-uncased'),
    config
)

model.load_state_dict(state_dict)
```

gives

```python
RuntimeError: Error(s) in loading state_dict for BertModel:
	Missing key(s) in state_dict: "embeddings.word_embeddings.weight", "embeddings.position_embeddings.weight", ...
        Unexpected key(s) in state_dict: "bert.embeddings.word_embeddings.weight", "bert.embeddings.position_embeddings.weight", ...
```

It seems like the loading and mapping function was written for the `BertForPreTraining` class where the `BertModel` instance is present as `bert` attribute. It could therefore be seen as _expected behavior_. However, since `BertModel` also inherits from `BertPreTrainedModel` and provides a `from_pretrained()` method, I assumed that it can be used in the same way. As `strict=False` is used for loading weights, this doesn't result in an exception if the weights are not properly mapped and loaded.

I would either expect to have an error raised in this case or have the mapping of the weights handled transparently. The current behavior can easily lead to unexpected behavior that is notoriously difficult to debug.

**Update:**

Apparently, the problem even occurs when I load the weights to `BertForPreTraining`:

**Comment by congvmit** [comment]
Hello @kklemon how did you solve this problem?
