### ISSUE TITLE
Allow `return_softmax` when dropout is disabled

### ISSUE THREAD

**Issue by marcelroed** [Dao-AILab/flash-attention#871]
Hi! I'm using FlashAttention, and for certain bio-tasks it's useful to get the attention maps.

Is there a reason why this feature is gated behind having `p_dropout > 0.0`? If I call `flash_attn_qkvpacked_func` with `return_attn_probs=True` with `p_dropout`, I get `(out, softmax_lse, S_dmask) = (..., ..., None)`.

I'm not seeing how it would reduce compilation time if it's an opt-in feature and the C-code is precompiled anyway. Additionally, this warning/error is not printed when I call `flash_attn_qkvpacked_func` or its varlen counterpart.

https://github.com/Dao-AILab/flash-attention/blob/6c9e60de566800538fedad2ad5e6b7b55ca7f0c5/csrc/flash_attn/flash_api.cpp#L423-L427

I'd be happy to contribute a fix if this is something that you think should change.

Thank you!

**Comment by robflynnyh** [comment]
+1 if this is going to be kept like this should at least be clear from docstrings in the interface

**Comment by tridao** [comment]
If you want the attention maps then it's better to just call a standard attention implementation. The main point of flash-attention is to avoid having to write the attention maps (which takes a lot of memory and time). `return_attn_probs` is just there for debugging (as stated in the docstring).
