### ISSUE TITLE
Explanation of batch_size+1 on cu_seqlen for flash_attn_varlen_qkvpacked_func

### ISSUE THREAD

**Issue by rafaelvalle** [Dao-AILab/flash-attention#880]
The documentation for `flash_attn_varlen_qkvpacked_func` states that [cu_seqlens](https://github.com/Dao-AILab/flash-attention/blob/6c9e60de566800538fedad2ad5e6b7b55ca7f0c5/flash_attn/flash_attn_interface.py#L863C1-L865C1) should be of shape (batch_size + 1, ). I copy the excerpt below:
```
        cu_seqlens: (batch_size + 1,), dtype torch.int32. The cumulative sequence lengths
           of the sequences in the batch, used to index into qkv.
```           

What value is the + 1 item supposed to carry?

**Comment by tridao** [comment]
It starts with 0, so equivalent to F.pad(seqlens.cumsum(), 1, 0).

**Comment by rafaelvalle** [comment]
Thank you!
