### ISSUE TITLE
[Question] Support for Varlen Seqs with causal=False

### ISSUE THREAD

**Issue by Infi-zc** [Dao-AILab/flash-attention#881]
Hi,
I am inquiring about the forward/backward functionality in the FA1.0.7 (or later) and FA2.2 (or later) versions. Specifically, do these versions support varlen sequences when causal=False is set, and the query sequence length (seqlen_q) is not equal to the key sequence length (seqlen_k)?
Thanks!

**Comment by tridao** [comment]
Yes

**Comment by Infi-zc** [comment]
> Yes

Thanks!
