### ISSUE TITLE
[Question] Why isn't 32fp supported?

### ISSUE THREAD

**Issue by taewan2002** [Dao-AILab/flash-attention#882]

**Comment by tridao** [comment]
Because implementing fp32 takes time (there's a lot of low-level details to get right), and most folks who want fast attention already run in fp16/bf16.

**Comment by taewan2002** [comment]
Thank you for your reply.

Flash attention 2 is very fast, which is surprising and satisfying.
I hope one day we will be able to learn with higher precision, such as 32fp.
