### ISSUE TITLE
Interesting observations.

### ISSUE THREAD

**Issue by plusgrey** [Dao-AILab/flash-attention#894]
## I have observed some interesting things with flash-attention. Can anyone answer about this?

Firstly, my code for attention is:
![image](https://github.com/Dao-AILab/flash-attention/assets/56119958/dfa8488c-e684-4181-8656-58c1da11b5ed)

The test code is below:
![image](https://github.com/Dao-AILab/flash-attention/assets/56119958/59cbea1b-04bf-464a-8ca6-aa39dc780ea0)

1. One interesting thing is the second run time will be significantly small:
![image](https://github.com/Dao-AILab/flash-attention/assets/56119958/2baca4be-c836-4bf8-859a-b85cdbcd9b53)

Hope anyone can help me about these findings.

**Comment by tridao** [comment]
Benchmarking CUDA code in Pytorch requires synchronization: https://pytorch.org/tutorials/recipes/recipes/benchmark.html

**Comment by tridao** [comment]
There's no reason for two ways to compute attention to give exactly the same output since floating point arithmetic is not associative. Changing the order of operation will give a slightly different answer (up to numerical precision). 

```
In [1]: import torch

In [2]: a = torch.randn(10)

In [3]: a = torch.randn(10, dtype=torch.float16)

In [4]: (a + 0.3 - 0.3 - a).abs().max()
Out[4]: tensor(0.0005, dtype=torch.float16)
```

**Comment by plusgrey** [comment]
> There's no reason for two ways to compute attention to give exactly the same output since floating point arithmetic is not associative. Changing the order of operation will give a slightly different answer (up to numerical precision).
> 
> ```
> In [1]: import torch
> 
> In [3]: a = torch.randn(10, dtype=torch.float16)
> 
> In [4]: (a + 0.3 - 0.3 - a).abs().max()
> Out[4]: tensor(0.0005, dtype=torch.float16)
> ```

Thanks for your answer, I have acknowledged this now. Is the time variance caused by the absence of benchmark synchronizing?

**Comment by tridao** [comment]
Yes

**Comment by plusgrey** [comment]
> Yes

Thanks so much for your answer.
