### ISSUE TITLE
How to compute the exact activation memory by formula?

### ISSUE THREAD

**Issue by Ethan-yt** [Dao-AILab/flash-attention#899]
In the traditional attention, the activation memory can be computed in $11sbh+5as^2b$ bytes. (from paper https://arxiv.org/pdf/2205.05198.pdf)

My question is: How to compute the exact activation memory in flash attention?

In my experiment, I got around $11sbh$ bytes increment in memory. I know it needs to store the input, q, k, v, totally $8sbh$. What did I missed?

**Comment by tridao** [comment]
Idk how the numbers 11sbh and 5as^2b are derived, so it's hard for me to say. Might need to read the paper ^^ closely. My first reaction is that there'll be no term that's quadratic in s, so the 5as^2b term should be gone.

**Comment by Ethan-yt** [comment]
> Idk how the numbers 11sbh and 5as^2b are derived, so it's hard for me to say. Might need to read the paper ^^ closely. My first reaction is that there'll be no term that's quadratic in s, so the 5as^2b term should be gone.

Thanks for your reply!
I did an experiment and measure memory usage by torch.cuda.memory_allocated.
I got a number around 11sbh. I am not sure it's correct with theory.

**Comment by Ethan-yt** [comment]
I found the answer: $12sbh + 4sbh_a$

```
from flash_attn.flash_attn_interface import flash_attn_qkvpacked_func
import torch
from einops import rearrange

    
s = 4096
b = 1
h = 8192 # hidden
ah = 256 # attention head hidden
nh = h//ah # attention heads

class Attention(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.query_key_value = torch.nn.Linear(h, 3*h, bias=False)
        self.dense = torch.nn.Linear(h, h, bias=False)
    
    
    def forward(self, hidden_states):
        mixed_x_layer = self.query_key_value(hidden_states)
        mixed_x_layer = mixed_x_layer.view(b, s, 3, nh, ah)
        output = flash_attn_qkvpacked_func(mixed_x_layer, causal=True)
        output_reshape = rearrange(output, 'b s h d -> b s (h d)')
        dense_output = self.dense(output_reshape)
        return dense_output
```
And then print the memory usage
```
def print_memory():
    model = Attention().bfloat16().cuda()
    torch.cuda.synchronize()
    m = torch.cuda.memory_allocated()
    hidden = torch.rand((b,s,h), requires_grad=True).bfloat16().cuda()
    output = model(hidden)
    torch.cuda.synchronize()
    print(torch.cuda.memory_allocated() - m)
```
Outputs:
> 403177984

403177984 - (12*s*b*h + 4*b*s*nh)
> 512


* Hidden and output: $2\times 2sbh$ (bf16)

According to:
https://github.com/Dao-AILab/flash-attention/blob/36587c01cb4390de0a590b2131e3fcc4859ba09c/flash_attn/flash_attn_interface.py#L237

which saves `q`, `k`, `v`, `o`, `softmax_lse`, `rng_state`
* `q`, `k`, `v`, `o` 's size is $4\times 2sbh$ (bf16)
* softmax_lse's size $4bsh_a$ (float32)
* rng_state's size $2*4$ (int64)

in total, $12sbh + 4sbh_a$
