### ISSUE TITLE
How to specify cuda 1 when finetuning?

### ISSUE THREAD

**Issue by karry5921** [Dao-AILab/flash-attention#901]
The cuda 0 I am using has no memory, so I need to specify cuda 1. I tried two ways: CUDA_VISIBLE_DEVICES=1 deepspeed ${deepspeed_args} and deepspeed --include="localhost:1" ${deepspeed_args} , but it seemed that both ways didn't work out .
The log error is as below:
<img width="1002" alt="截屏2024-03-25 17 40 41" src="https://github.com/Dao-AILab/flash-attention/assets/47595077/aa2dadac-df4f-47b8-89a0-8eaa508ba1a0">
Could you please tell me how to specify cuda 1?

**Comment by tridao** [comment]
I think you meant to post this to another repo?
