### ISSUE TITLE
What is the difference between abiTRUE.whl and abiFALSE.whl?

### ISSUE THREAD

**Issue by uRENu** [Dao-AILab/flash-attention#903]
I don't know what the difference is between these two installation packages. Will installing different packages affect the model accuracy?
<img width="712" alt="企业微信截图_bcbafd15-8a8e-4ec7-94e7-f6911c904929" src="https://github.com/Dao-AILab/flash-attention/assets/54517380/81afac21-4d3d-4ce1-bf85-6ef6228d37d5">

**Comment by tridao** [comment]
setup.py picks the right wheel for you
https://github.com/Dao-AILab/flash-attention/blob/23e8fa5a263d1c7122bc46a86ef32030ee7130f9/setup.py#L243
