### ISSUE TITLE
Feature request: make build PEP 517 compatible

### ISSUE THREAD

**Issue by wjn0** [Dao-AILab/flash-attention#955]
I tried to run:

    $ pip wheel --no-cache-dir --use-pep517 "flash-attn (==2.5.8)"

and this failed with

    ModuleNotFoundError: No module named 'packaging'

Is there anything in the build process preventing compatibility with PEP 517 (which prevents the use of dependency managers like Poetry which are quite helpful)?

**Comment by wjn0** [comment]
Duplicate of #927. But I did want to share this workaround for Poetry users (namely, use the GitHub wheel release). Tailor your CUDA, PyTorch, and CPython version accordingly of course:

    poetry add "flash-attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.8/flash_attn-2.5.8+cu122torch2.3cxx11abiFALSE-cp310-cp310-linux_x86_64.whl"

**Comment by tridao** [comment]
I haven't found a satisfactory way to make it PEP 517 compatible. If we include pytorch in the setup requirements, it might download a different pytorch version than what users already have, just to build the extension. This can make installation very slow for some users.

**Comment by wjn0** [comment]
Yeah, that makes sense. I appreciate your response! Thanks for a great package. I'll close this as a dup of #927 for now.
