### ISSUE TITLE
DropoutAddRMSNorm using triton backend

### ISSUE THREAD

**Issue by fferroni** [Dao-AILab/flash-attention#973]
Hello,
I was wondering if there is a DropoutAddRMSNorm equivalent that uses the triton backend in `flash_attn/ops/triton/layer_norm.py` ? Is it LayerNormFn with is_rms_norm=True ?
Trying to refactor some code to avoid `DropoutAddRMSNorm ` so I can avoid `import dropout_layer_norm`.
Thanks!

**Comment by tridao** [comment]
Yes

**Comment by fferroni** [comment]
OK thanks! :)

**Comment by tridao** [comment]
Please see the tests: https://github.com/Dao-AILab/flash-attention/blob/main/tests/ops/triton/test_layer_norm.py
