### ISSUE TITLE
Installation:cannot import name 'packaging' from 'pkg_resources

### ISSUE THREAD

**Issue by Dionysos-o** [Dao-AILab/flash-attention#981]
Hi, when i tried to install the flash-attention, i met the problem:
cannot import name 'packaging' from 'pkg_resources
![image](https://github.com/Dao-AILab/flash-attention/assets/68541740/0b5b008c-c851-4339-944e-8090878e4c07)

**Comment by Tellterubouzu** [comment]
I ran into the same error you did.

**Comment by Tellterubouzu** [comment]
I solved this problem by following command
```
pip uninstall setuptools
pip install setuptools==69.5.1
```

**Comment by Dionysos-o** [comment]
> I solved this problem by following command
> 
> ```
> pip uninstall setuptools
> pip install setuptools==69.5.1
> ```

Thanks so much!! I also solved by this way.

**Comment by zhengyuan-xie** [comment]
> pip install setuptools==69.5.1

Thanks
