### ISSUE TITLE
Windows, no docker, CUDA 12.1, Python 3.10.  HOW to install this thing?

### ISSUE THREAD

**Issue by DarkAlchy** [Dao-AILab/flash-attention#983]
As the title asks...how do I install this?  I am not going to use docker nor roll back my CUDA to 11.8 as that would break too much which would nullify the need for it then.

**Comment by dillfrescott** [comment]
Weird, you are specifically asking for the exact version I compile prebuilt wheels for on windows.

I compile it myself and on my 5800X cpu it takes about an hour IIRC.

https://github.com/dillfrescott/flash-attn-windows-wheels

**Comment by dillfrescott** [comment]
When a new version of flash attention comes out, if im not on vacation or something I try to build the windows wheel in at least 48 hours.

**Comment by bdashore3** [comment]
FA2 is only supported for cuda 12 and up. You can get prebuilt wheels from my fork https://github.com/bdashore3/flash-attention/releases

There should probably be a separate issue for creating build actions for windows

**Comment by dillfrescott** [comment]
@bdashore3 I have [these](https://github.com/dillfrescott/flash-attn-windows-wheels/releases/tag/v2.5.9.post1).

**Comment by DarkAlchy** [comment]
I compiled flash-attn on my machine due to another project (took almost an hour), but would I gain anything by switching to FA2?

**Comment by bdashore3** [comment]
FA2 is an abbreviation for "flash-attention v2.0" which is this repository. I build prebuilts on my own fork since there's no windows wheels on this repo.

So, no you won't gain or lose anything. You will only be saving time on compilation since I already compiled the wheels for everyone using GitHub actions.

**Comment by 394988736** [comment]
> FA2 is only supported for cuda 12 and up. You can get prebuilt wheels from my fork https://github.com/bdashore3/flash-attention/releases
> 
> There should probably be a separate issue for creating build actions for windows

cu123是指cuda12.3吗，pytorch官网好像没有支持12.3的版本
