### ISSUE TITLE
Deterministic Disscusion

### ISSUE THREAD

**Issue by YizhouZ** [Dao-AILab/flash-attention#988]
Hi @tridao, I am looking into flash attention backward deterministic feature. Would like to hear your thoughts on my understanding of this feature.
From previous chat, original implementation of backward kernel was non-deterministic. My understanding is due to seqK parallel, the parallel sum of dQi would in different order every run and causes result different every time.
And to be deterministic, kernels need to avoid seqK parallelism and loop it sequentially instead, which makes sure that dQi will be wrote back in a certain order (j = 0, 1, 2, ...). 
Please let me know if above theories are right or wrong. Thank you so much for your time!

**Comment by tridao** [comment]
Yes that's right

**Comment by YizhouZ** [comment]
Thanks! Is dQi only or others like dK, dV would also be affected?

**Comment by tridao** [comment]
Only dQ

**Comment by YizhouZ** [comment]
> Only dQ

understand. Thanks again!
