### ISSUE TITLE
[QST] Question about the Dropout

### ISSUE THREAD

**Issue by flytigerw** [Dao-AILab/flash-attention#993]
Hey~, I got some problems with Dropout in the FA2 codes. It would be appreciated if you could help me out. <br>
As far as I know, Philox RNG is used to produce 4 random 32-bit integers. But it seems that FA2 reinterprets them as 16 8-bit integers, as the following codes show:
<img width="1083" alt="image" src="https://github.com/Dao-AILab/flash-attention/assets/48581026/90276c36-e3d9-4228-affc-fb3f73196f68">
Are the upper 16 bits or lower 16 bits of a 32-bit random integer still random? What's the mechanism behind this handling ?

**Comment by flytigerw** [comment]
I am wondering if partial bits of the random 32-bit integer reamin randomness. And it seems that the space of a random integer with 8 bits is small, why is it reasonable ?

**Comment by tridao** [comment]
Yes it's random.

**Comment by flytigerw** [comment]
Thanks a lot !!
